/*
 * Who Did It? - the deck.
 *
 * A DEED someone in the Bible did goes on the projector; the room shouts who
 * did it. Four clicks: the deed, the verse, a clue, then the name.
 *
 *   answer     the person, revealed last
 *   quote      the DEED, in our own words. The field is named `quote` because
 *              this game reuses the quote renderer wholesale - same four
 *              beats, same two-language handling - and inventing a `deed`
 *              type that was a copy of it would have bought nothing.
 *   verse      where it happened. Shown BEFORE the clue, on purpose: the
 *              reference is itself a hint for whoever has read the passage.
 *   clue       one image about the person that does not name them
 *   lang       'en' or 'fil', on the VARIANT - so one person is one puzzle
 *   answer     on a variant, the name in that language
 *
 * WHAT MAKES THIS DIFFERENT FROM Who Said It?
 *
 * Nothing here is scripture. The deed is our sentence, so there is no wording
 * to verify against a Bible and no copyrighted translation to license - the
 * Tagalog is a translation of our own words. Only the REFERENCE is a claim
 * about the text, and a reference is right or wrong at a glance.
 *
 * That is also why the game exists alongside its sibling rather than instead
 * of it: a deed can be pictured. A young person who does not read much can see
 * someone climbing a tree or opening a roof, where a quotation gives them
 * nothing to hold on to.
 *
 * TAGALOG
 *
 * Every deed exists twice: an English variant and a Tagalog one carrying
 * lang: 'fil' and the name in that language. They are variants of ONE puzzle
 * because PEDRO and PETER are one person - which is what stops a Tagalog round
 * and an English round both drawing him.
 *
 * Unlike Who Said It?, this side needed no licence and no fetching. There the
 * line is scripture, so a Tagalog deck meant either public-domain text or the
 * Philippine Bible Society's permission. Here the sentence is ours, so the
 * Tagalog is simply a translation of it. Adding a person means writing two
 * variants, not one.
 *
 * THE RULE THAT COSTS THE MOST REWORK
 *
 * A deed must not point harder at somebody ELSE in the deck. Checking that it
 * does not NAME the answer is a string comparison, and passes happily on a
 * puzzle that is still wrong. Jesus absorbs anyone who shares a scene with
 * him; Elijah and Elisha absorb each other. Read a new deed as a whole and ask
 * which name the room actually shouts.
 */
window.DECK = {
  id: 'who-did-it',
  title: 'Who Did It?',
  idPrefix: 'wd',   // shown on the projector, so it must never hint the answer
  shuffle: true,
  sessionSize: 20,
  languages: ['en', 'fil'],
  // The text on screen is ours, not a quotation, so it is shown without
  // quotation marks - marks around it would send the room hunting a speaker.
  spoken: false,
  // The words are ours, so the only checkable claim is the reference.
  // validate.js says so rather than asking for a wording audit this deck does
  // not need.
  quoteNoun: 'deeds',
  verifyJob: 'check each reference points at the right passage',
  // No `credits` and no `versions`, unlike Who Said It? - deliberately. That
  // deck puts a translation's name and copyright line on the screen because
  // it PRINTS that translation's words. This one quotes nothing: the deed is
  // ours in both languages, and a chapter-and-verse reference belongs to
  // nobody. The Tagalog book names follow Ang Dating Biblia (1905) only so
  // that a Filipino congregation recognises them.
  howToPlay: [
    'Something someone in the Bible did. The room says who did it.',
    'Stuck? The next click gives the verse, then a clue.',
  ],
  puzzles: [
    {
      id: 'wd-01', answer: 'NOAH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Built a giant boat far from the sea',
          verse: 'Genesis 6:22',
          clue: 'he was six hundred years old when the water finally came' },
        { type: 'quote', lang: 'fil', answer: 'NOE',
          flag: 'unverified', difficulty: 1,
          quote: 'Gumawa ng higanteng barko na malayo sa dagat',
          verse: 'Genesis 6:22',
          clue: 'anim na raang taong gulang na siya nang dumating ang tubig' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Sent a raven, then a dove, out through a window',
          verse: 'Genesis 8:6-8',
          clue: 'the second bird came back holding a fresh olive leaf' },
        { type: 'quote', lang: 'fil', answer: 'NOE',
          flag: 'unverified', difficulty: 2,
          quote: 'Nagpalipad ng uwak, tapos kalapati, sa bintana',
          verse: 'Genesis 8:6-8',
          clue: 'ang pangalawang ibon ay bumalik na may sariwang dahon ng olibo' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Planted a vineyard, drank the wine, and passed out',
          verse: 'Genesis 9:20-21',
          clue: 'two of his sons walked in backwards to cover him up' },
        { type: 'quote', lang: 'fil', answer: 'NOE',
          flag: 'unverified', difficulty: 3,
          quote: 'Nagtanim ng ubasan, ininom ang alak, at nalasing',
          verse: 'Genesis 9:20-21',
          clue: 'dalawa sa mga anak niya ang pumasok nang paatras para takpan siya' },
      ],
    },
    {
      id: 'wd-02', answer: 'CAIN', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Killed his own brother out in a field',
          verse: 'Genesis 4:8',
          clue: 'his gift from the ground had been passed over for a lamb' },
        { type: 'quote', lang: 'fil', answer: 'CAIN',
          flag: 'unverified', difficulty: 1,
          quote: 'Pinatay ang sarili niyang kapatid sa gitna ng bukid',
          verse: 'Genesis 4:8',
          clue: 'hindi tinanggap ang handog niyang galing sa lupa, kundi ang kordero' },
      ],
    },
    {
      id: 'wd-03', answer: 'ABRAHAM', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Raised a knife over his tied-up son on a mountain',
          verse: 'Genesis 22:10',
          clue: 'a ram stuck in a thicket died in the boy\'s place' },
        { type: 'quote', lang: 'fil', answer: 'ABRAHAM',
          flag: 'unverified', difficulty: 1,
          quote: 'Itinaas ang kutsilyo sa nakagapos niyang anak sa bundok',
          verse: 'Genesis 22:10',
          clue: 'isang lalaking tupang nasabit sa palumpong ang namatay kapalit ng bata' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Chased four kings by night to rescue his nephew',
          verse: 'Genesis 14:14-16',
          clue: 'he armed 318 trained men born in his own household' },
        { type: 'quote', lang: 'fil', answer: 'ABRAHAM',
          flag: 'unverified', difficulty: 3,
          quote: 'Hinabol ang apat na hari sa gabi para iligtas ang pamangkin',
          verse: 'Genesis 14:14-16',
          clue: 'nagdala siya ng 318 sanay na lalaking ipinanganak sa sarili niyang bahay' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Killed a calf and served three strangers under a tree',
          verse: 'Genesis 18:7-8',
          clue: 'his wife laughed inside the tent at what they promised' },
        { type: 'quote', lang: 'fil', answer: 'ABRAHAM',
          flag: 'unverified', difficulty: 3,
          quote: 'Kumatay ng guya at naghain sa tatlong dayuhan sa ilalim ng puno',
          verse: 'Genesis 18:7-8',
          clue: 'tumawa ang asawa niya sa loob ng tolda sa ipinangako nila' },
      ],
    },
    {
      id: 'wd-04', answer: 'JACOB', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Wrestled a stranger all night until his hip gave out',
          verse: 'Genesis 32:24-25',
          clue: 'he limped away at sunrise with a brand-new name' },
        { type: 'quote', lang: 'fil', answer: 'JACOB',
          flag: 'unverified', difficulty: 1,
          quote: 'Nakipagbuno sa di-kilalang lalaki buong gabi hanggang mapilay ang balakang',
          verse: 'Genesis 32:24-25',
          clue: 'umalis siyang pilay pagsikat ng araw, may bagong pangalan' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Poured oil on the stone he had slept on',
          verse: 'Genesis 28:18',
          clue: 'he had dreamed of a stairway crowded with angels' },
        { type: 'quote', lang: 'fil', answer: 'JACOB',
          flag: 'unverified', difficulty: 2,
          quote: 'Binuhusan ng langis ang batong pinag-unan niya',
          verse: 'Genesis 28:18',
          clue: 'napanaginipan niya ang hagdang punong-puno ng mga anghel' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Peeled stripes into branches and stood them in the troughs',
          verse: 'Genesis 30:37-39',
          clue: 'he was outsmarting the uncle who kept changing his wages' },
        { type: 'quote', lang: 'fil', answer: 'JACOB',
          flag: 'unverified', difficulty: 3,
          quote: 'Tinalupan ng guhit ang mga sanga at itinayo sa inuman ng hayop',
          verse: 'Genesis 30:37-39',
          clue: 'dinaya niya ang tiyuhing paulit-ulit na binabago ang sahod niya' },
      ],
    },
    {
      id: 'wd-05', answer: 'JOSEPH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Stored up grain in Egypt through seven good years',
          verse: 'Genesis 41:48-49',
          clue: 'he had read a dream about fat cows and thin ones' },
        { type: 'quote', lang: 'fil', answer: 'JOSE',
          flag: 'unverified', difficulty: 1,
          quote: 'Nag-imbak ng butil sa Egipto sa pitong taon ng kasaganaan',
          verse: 'Genesis 41:48-49',
          clue: 'naipaliwanag niya ang panaginip tungkol sa matatabang baka at sa payat' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Ran out of a house and left his coat in her hand',
          verse: 'Genesis 39:12',
          clue: 'she kept the garment and used it to accuse him' },
        { type: 'quote', lang: 'fil', answer: 'JOSE',
          flag: 'unverified', difficulty: 2,
          quote: 'Tumakbo palabas ng bahay at naiwan ang damit niya sa kamay ng babae',
          verse: 'Genesis 39:12',
          clue: 'itinago ng babae ang damit at ginamit para paratangan siya' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Hid a silver cup in his youngest brother\'s grain sack',
          verse: 'Genesis 44:2',
          clue: 'he was testing brothers who still did not recognise him' },
        { type: 'quote', lang: 'fil', answer: 'JOSE',
          flag: 'unverified', difficulty: 3,
          quote: 'Itinago ang pilak na kopa sa sako ng butil ng bunsong kapatid',
          verse: 'Genesis 44:2',
          clue: 'sinusubok niya ang mga kapatid na hindi pa siya nakikilala' },
      ],
    },
    {
      id: 'wd-06', answer: 'MOSES', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Struck a rock with his staff and water poured out',
          verse: 'Exodus 17:6',
          clue: 'a whole nation and all their animals drank from it' },
        { type: 'quote', lang: 'fil', answer: 'MOISES',
          flag: 'unverified', difficulty: 1,
          quote: 'Hinampas ang bato ng tungkod at bumulwak ang tubig',
          verse: 'Exodo 17:6',
          clue: 'buong bayan at lahat ng hayop nila ay uminom doon' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Smashed two stone tablets at the foot of a mountain',
          verse: 'Exodus 32:19',
          clue: 'he came down to find a golden calf and dancing' },
        { type: 'quote', lang: 'fil', answer: 'MOISES',
          flag: 'unverified', difficulty: 1,
          quote: 'Binasag ang dalawang tapyas na bato sa paanan ng bundok',
          verse: 'Exodo 32:19',
          clue: 'pagbaba niya, may gintong guya at may sayawan' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Killed an Egyptian and buried the body in the sand',
          verse: 'Exodus 2:12',
          clue: 'the next day two quarrelling men let him know they had seen' },
        { type: 'quote', lang: 'fil', answer: 'MOISES',
          flag: 'unverified', difficulty: 2,
          quote: 'Pumatay ng isang taga-Egipto at ibinaon ang bangkay sa buhangin',
          verse: 'Exodo 2:12',
          clue: 'kinabukasan, ipinaalam ng dalawang nag-aaway na nakita nila iyon' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Lifted a bronze snake up on a pole in the desert',
          verse: 'Numbers 21:9',
          clue: 'anyone bitten who looked up at it stayed alive' },
        { type: 'quote', lang: 'fil', answer: 'MOISES',
          flag: 'unverified', difficulty: 3,
          quote: 'Itinaas ang tansong ahas sa isang poste sa ilang',
          verse: 'Mga Bilang 21:9',
          clue: 'sinumang natuklaw na tumingin doon ay nanatiling buhay' },
      ],
    },
    {
      id: 'wd-07', answer: 'AARON', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Melted the people\'s gold earrings into a calf',
          verse: 'Exodus 32:2-4',
          clue: 'he blamed the crowd when his brother came down the mountain' },
        { type: 'quote', lang: 'fil', answer: 'AARON',
          flag: 'unverified', difficulty: 2,
          quote: 'Tinunaw ang gintong hikaw ng bayan at ginawang guya',
          verse: 'Exodo 32:2-4',
          clue: 'sinisi niya ang mga tao nang bumaba ang kapatid niya sa bundok' },
      ],
    },
    {
      id: 'wd-08', answer: 'JOSHUA', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Marched an army around a walled city for seven days',
          verse: 'Joshua 6:3-4',
          clue: 'on the last day they went round seven times, then shouted' },
        { type: 'quote', lang: 'fil', answer: 'JOSUE',
          flag: 'unverified', difficulty: 1,
          quote: 'Pinalibot ang hukbo sa napapaderang lungsod sa loob ng pitong araw',
          verse: 'Josue 6:3-4',
          clue: 'sa huling araw ay pitong ikot sila, tapos sumigaw' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Set up twelve stones carried out of a dried-up riverbed',
          verse: 'Joshua 4:8-9',
          clue: 'one man from each tribe lifted a stone off the Jordan floor' },
        { type: 'quote', lang: 'fil', answer: 'JOSUE',
          flag: 'unverified', difficulty: 3,
          quote: 'Nagtayo ng labindalawang batong kinuha sa natuyong ilog',
          verse: 'Josue 4:8-9',
          clue: 'isang lalaki sa bawat lipi ang pumulot ng bato sa ilalim ng Jordan' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Sealed five captured kings inside a cave with big stones',
          verse: 'Joshua 10:26-27',
          clue: 'that was the day the sun stood still over Gibeon' },
        { type: 'quote', lang: 'fil', answer: 'JOSUE',
          flag: 'unverified', difficulty: 3,
          quote: 'Isinara sa yungib ang limang nadakip na hari, tinakpan ng malalaking bato',
          verse: 'Josue 10:26-27',
          clue: 'iyon ang araw na huminto ang araw sa Gabaon' },
      ],
    },
    {
      id: 'wd-09', answer: 'RAHAB', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Hid two spies under stalks of flax on her roof',
          verse: 'Joshua 2:6',
          clue: 'a scarlet cord hung from her window when the walls fell' },
        { type: 'quote', lang: 'fil', answer: 'RAHAB',
          flag: 'unverified', difficulty: 2,
          quote: 'Itinago ang dalawang tiktik sa ilalim ng mga lino sa bubong niya',
          verse: 'Josue 2:6',
          clue: 'may pulang lubid na nakasabit sa bintana niya nang bumagsak ang pader' },
      ],
    },
    {
      id: 'wd-10', answer: 'GIDEON', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Laid a wool fleece on the threshing floor two nights running',
          verse: 'Judges 6:37-39',
          clue: 'one morning it was soaked with dew, the next it was dry' },
        { type: 'quote', lang: 'fil', answer: 'GEDEON',
          flag: 'unverified', difficulty: 1,
          quote: 'Naglatag ng balahibo ng tupa sa giikan nang dalawang magkasunod na gabi',
          verse: 'Mga Hukom 6:37-39',
          clue: 'isang umaga basang-basa iyon sa hamog, kinabukasan tuyo' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Sent 22,000 soldiers home and kept only 300',
          verse: 'Judges 7:3-7',
          clue: 'he kept the ones who lapped up water like a dog' },
        { type: 'quote', lang: 'fil', answer: 'GEDEON',
          flag: 'unverified', difficulty: 1,
          quote: 'Pinauwi ang 22,000 sundalo at 300 lang ang itinira',
          verse: 'Mga Hukom 7:3-7',
          clue: 'pinili niya ang mga humimod ng tubig na parang aso' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Broke a clay jar and blew a trumpet in the dark',
          verse: 'Judges 7:19-20',
          clue: 'three hundred men did the very same thing all around the camp' },
        { type: 'quote', lang: 'fil', answer: 'GEDEON',
          flag: 'unverified', difficulty: 2,
          quote: 'Binasag ang bangang luwad at humihip ng trumpeta sa dilim',
          verse: 'Mga Hukom 7:19-20',
          clue: 'tatlong daang lalaki ang gumawa ng gayon din sa buong paligid ng kampo' },
      ],
    },
    {
      id: 'wd-11', answer: 'SAMSON', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Killed a lion with his bare hands',
          verse: 'Judges 14:6',
          clue: 'he told nobody, and later scooped honey out of the carcass' },
        { type: 'quote', lang: 'fil', answer: 'SAMSON',
          flag: 'unverified', difficulty: 2,
          quote: 'Pinatay ang isang leon gamit ang mga kamay lang',
          verse: 'Mga Hukom 14:6',
          clue: 'wala siyang pinagsabihan, at kumuha pa ng pulot sa bangkay nito' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Tied torches to the tails of three hundred foxes',
          verse: 'Judges 15:4-5',
          clue: 'the burning animals ran through his enemies\' standing grain' },
        { type: 'quote', lang: 'fil', answer: 'SAMSON',
          flag: 'unverified', difficulty: 2,
          quote: 'Itinali ang mga sulo sa buntot ng tatlong daang soro',
          verse: 'Mga Hukom 15:4-5',
          clue: 'tumakbo ang nagliliyab na mga hayop sa pananim ng mga kaaway niya' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Killed a thousand men with a donkey\'s jawbone',
          verse: 'Judges 15:15',
          clue: 'he threw the bone away and then begged for a drink' },
        { type: 'quote', lang: 'fil', answer: 'SAMSON',
          flag: 'unverified', difficulty: 1,
          quote: 'Pumatay ng isang libong lalaki gamit ang panga ng asno',
          verse: 'Mga Hukom 15:15',
          clue: 'itinapon niya ang buto at saka humingi ng maiinom' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Pushed apart the two pillars holding up a packed temple',
          verse: 'Judges 16:29-30',
          clue: 'his hair had grown back, and a boy had led him to the spot' },
        { type: 'quote', lang: 'fil', answer: 'SAMSON',
          flag: 'unverified', difficulty: 1,
          quote: 'Itinulak ang dalawang haliging nagtataglay sa punong-punong templo',
          verse: 'Mga Hukom 16:29-30',
          clue: 'tumubo nang muli ang buhok niya, at may batang umakay sa kanya doon' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Carried off a city\'s gates on his shoulders',
          verse: 'Judges 16:3',
          clue: 'he did it at midnight, and hauled them uphill' },
        { type: 'quote', lang: 'fil', answer: 'SAMSON',
          flag: 'unverified', difficulty: 3,
          quote: 'Binuhat sa balikat ang mga pintuang-bayan ng isang lungsod',
          verse: 'Mga Hukom 16:3',
          clue: 'hatinggabi niya ginawa, at iniakyat pa niya sa burol' },
      ],
    },
    {
      id: 'wd-12', answer: 'JAEL', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Drove a tent peg through a sleeping general\'s head',
          verse: 'Judges 4:21',
          clue: 'she gave him milk and a rug before he fell asleep' },
        { type: 'quote', lang: 'fil', answer: 'JAEL',
          flag: 'unverified', difficulty: 3,
          quote: 'Itinusok ang tulos ng tolda sa ulo ng natutulog na heneral',
          verse: 'Mga Hukom 4:21',
          clue: 'binigyan niya ito ng gatas at kumot bago ito nakatulog' },
      ],
    },
    {
      id: 'wd-13', answer: 'RUTH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Gleaned leftover barley behind a stranger\'s harvesters',
          verse: 'Ruth 2:3',
          clue: 'she had left her own country to follow her mother-in-law' },
        { type: 'quote', lang: 'fil', answer: 'RUTH',
          flag: 'unverified', difficulty: 1,
          quote: 'Namulot ng tirang sebada sa likod ng mga tagaani ng di-kilalang lalaki',
          verse: 'Ruth 2:3',
          clue: 'iniwan niya ang sariling bayan para sumama sa biyenan niya' },
      ],
    },
    {
      id: 'wd-14', answer: 'DAVID', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Sank one slung stone into a giant\'s forehead',
          verse: '1 Samuel 17:49',
          clue: 'he refused the king\'s armour and picked five smooth stones' },
        { type: 'quote', lang: 'fil', answer: 'DAVID',
          flag: 'unverified', difficulty: 1,
          quote: 'Isang batong ipinukol ang bumaon sa noo ng higante',
          verse: '1 Samuel 17:49',
          clue: 'tinanggihan niya ang baluti ng hari at pumili ng limang makinis na bato' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Cut a corner off a sleeping king\'s robe in a cave',
          verse: '1 Samuel 24:4',
          clue: 'his own men begged him to kill the man hunting him' },
        { type: 'quote', lang: 'fil', answer: 'DAVID',
          flag: 'unverified', difficulty: 2,
          quote: 'Ginupit ang laylayan ng balabal ng natutulog na hari sa yungib',
          verse: '1 Samuel 24:4',
          clue: 'pinipilit siya ng mga tauhan niyang patayin ang humahabol sa kanya' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Danced with all his might in front of the ark',
          verse: '2 Samuel 6:14',
          clue: 'his wife watched from a window and despised him for it' },
        { type: 'quote', lang: 'fil', answer: 'DAVID',
          flag: 'unverified', difficulty: 2,
          quote: 'Sumayaw nang buong lakas sa harap ng kaban',
          verse: '2 Samuel 6:14',
          clue: 'pinanood siya ng asawa niya sa bintana at kinasuklaman siya nito' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Drooled into his beard and acted insane before a king',
          verse: '1 Samuel 21:13',
          clue: 'he was trapped in an enemy city and had to get out alive' },
        { type: 'quote', lang: 'fil', answer: 'DAVID',
          flag: 'unverified', difficulty: 3,
          quote: 'Nagpalaway sa balbas at nagkunwaring baliw sa harap ng hari',
          verse: '1 Samuel 21:13',
          clue: 'naipit siya sa lungsod ng kaaway at kailangan niyang makatakas nang buhay' },
      ],
    },
    {
      id: 'wd-15', answer: 'SAUL', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Threw a spear at the harp player in his own house',
          verse: '1 Samuel 18:10-11',
          clue: 'the king it was meant to calm; he threw twice, and missed twice' },
        { type: 'quote', lang: 'fil', answer: 'SAUL',
          flag: 'unverified', difficulty: 2,
          quote: 'Ibinato ang sibat sa manunugtog ng alpa sa sarili niyang bahay',
          verse: '1 Samuel 18:10-11',
          clue: 'ang hari sana ang pinapakalma ng tugtog; dalawang beses siyang pumalya' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Went to a witch at night to call up a dead prophet',
          verse: '1 Samuel 28:7-8',
          clue: 'he had thrown all such people out of the land himself' },
        { type: 'quote', lang: 'fil', answer: 'SAUL',
          flag: 'unverified', difficulty: 3,
          quote: 'Pumunta sa isang mangkukulam sa gabi para tawagin ang patay nang propeta',
          verse: '1 Samuel 28:7-8',
          clue: 'siya mismo ang nagpalayas sa lahat ng ganoong tao sa lupain' },
      ],
    },
    {
      id: 'wd-16', answer: 'SOLOMON', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Ordered a live baby cut in two with a sword',
          verse: '1 Kings 3:25',
          clue: 'he was finding out which of two women was the real mother' },
        { type: 'quote', lang: 'fil', answer: 'SOLOMON',
          flag: 'unverified', difficulty: 1,
          quote: 'Iniutos na hatiin sa dalawa ng espada ang isang buhay na sanggol',
          verse: '1 Mga Hari 3:25',
          clue: 'inaalam niya kung sino sa dalawang babae ang tunay na ina' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Built a temple with stones so no hammer was heard',
          verse: '1 Kings 6:7',
          clue: 'it took seven years, and the cedar came from Lebanon' },
        { type: 'quote', lang: 'fil', answer: 'SOLOMON',
          flag: 'unverified', difficulty: 2,
          quote: 'Nagtayo ng templo na walang narinig na martilyo',
          verse: '1 Mga Hari 6:7',
          clue: 'pitong taon bago iyon natapos, at galing sa Libano ang sedro' },
      ],
    },
    {
      id: 'wd-17', answer: 'ELIJAH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Poured twelve barrels of water over his own altar',
          verse: '1 Kings 18:33-35',
          clue: 'fire fell and licked up even the water in the trench' },
        { type: 'quote', lang: 'fil', answer: 'ELIAS',
          flag: 'unverified', difficulty: 2,
          quote: 'Binuhusan ng labindalawang bangang tubig ang sarili niyang altar',
          verse: '1 Mga Hari 18:33-35',
          clue: 'bumaba ang apoy at tinupok pati ang tubig sa kanal' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Ran into the desert and fell asleep under a juniper tree',
          verse: '1 Kings 19:4-5',
          clue: 'an angel woke him twice with baked bread and water' },
        { type: 'quote', lang: 'fil', answer: 'ELIAS',
          flag: 'unverified', difficulty: 3,
          quote: 'Tumakbo sa ilang at nakatulog sa ilalim ng punong enebro',
          verse: '1 Mga Hari 19:4-5',
          clue: 'dalawang beses siyang ginising ng anghel, may tinapay at tubig' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Crouched on the ground with his face between his knees',
          verse: '1 Kings 18:42',
          clue: 'his servant looked out to sea seven times for one small cloud' },
        { type: 'quote', lang: 'fil', answer: 'ELIAS',
          flag: 'unverified', difficulty: 3,
          quote: 'Yumukod sa lupa, ang mukha sa pagitan ng mga tuhod niya',
          verse: '1 Mga Hari 18:42',
          clue: 'pitong beses tumanaw sa dagat ang alipin niya para sa isang maliit na ulap' },
      ],
    },
    {
      id: 'wd-18', answer: 'ELISHA', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Stretched out on a dead boy who then sneezed seven times',
          verse: '2 Kings 4:34-35',
          clue: 'the mother had built him a little room with a bed and a lamp' },
        { type: 'quote', lang: 'fil', answer: 'ELISEO',
          flag: 'unverified', difficulty: 2,
          quote: 'Dumapa sa patay na bata na pitong beses na bumahing pagkatapos',
          verse: '2 Mga Hari 4:34-35',
          clue: 'ipinagawan siya ng ina ng maliit na silid na may higaan at ilawan' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Threw a stick in a river to float up an iron axe head',
          verse: '2 Kings 6:6',
          clue: 'a borrowed tool had sunk while men were cutting wood' },
        { type: 'quote', lang: 'fil', answer: 'ELISEO',
          flag: 'unverified', difficulty: 3,
          quote: 'Naghagis ng patpat sa ilog para lumutang ang bakal na palakol',
          verse: '2 Mga Hari 6:6',
          clue: 'lumubog ang hiniram na kagamitan habang pumuputol sila ng kahoy' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Threw flour into a cooking pot that had poison in it',
          verse: '2 Kings 4:41',
          clue: 'the young students had shouted that death was in the pot' },
        { type: 'quote', lang: 'fil', answer: 'ELISEO',
          flag: 'unverified', difficulty: 3,
          quote: 'Naglagay ng harina sa kalderong may lason',
          verse: '2 Mga Hari 4:41',
          clue: 'sumigaw ang mga batang mag-aaral na may kamatayan sa kaldero' },
      ],
    },
    {
      id: 'wd-19', answer: 'NAAMAN', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Dipped himself seven times in a muddy foreign river',
          verse: '2 Kings 5:14',
          clue: 'he was an army commander who had wanted a grander cure' },
        { type: 'quote', lang: 'fil', answer: 'NAAMAN',
          flag: 'unverified', difficulty: 2,
          quote: 'Naligo nang pitong beses sa maputik na ilog sa ibang bayan',
          verse: '2 Mga Hari 5:14',
          clue: 'pinuno siya ng hukbo na gusto sana ng mas engrandeng lunas' },
      ],
    },
    {
      id: 'wd-20', answer: 'DANIEL', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Prayed at his wide-open window three times a day anyway',
          verse: 'Daniel 6:10',
          clue: 'a brand-new law said pray only to the king for thirty days' },
        { type: 'quote', lang: 'fil', answer: 'DANIEL',
          flag: 'unverified', difficulty: 1,
          quote: 'Nanalangin pa rin sa bukas na bintana, tatlong beses sa isang araw',
          verse: 'Daniel 6:10',
          clue: 'may bagong batas: sa hari lang manalangin sa loob ng tatlumpung araw' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Turned down the king\'s rich food for ten days of vegetables',
          verse: 'Daniel 1:12-16',
          clue: 'he and three friends ended up healthier than all the rest' },
        { type: 'quote', lang: 'fil', answer: 'DANIEL',
          flag: 'unverified', difficulty: 2,
          quote: 'Tinanggihan ang masarap na pagkain ng hari, gulay sa loob ng sampung araw',
          verse: 'Daniel 1:12-16',
          clue: 'siya at ang tatlong kaibigan niya ang naging mas malusog kaysa sa lahat' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Read the writing a floating hand left on a palace wall',
          verse: 'Daniel 5:25',
          clue: 'the king\'s knees knocked together in the middle of a feast' },
        { type: 'quote', lang: 'fil', answer: 'DANIEL',
          flag: 'unverified', difficulty: 2,
          quote: 'Binasa ang sulat na iniwan ng lumulutang na kamay sa pader ng palasyo',
          verse: 'Daniel 5:25',
          clue: 'nagkaumpugan ang tuhod ng hari sa gitna ng piging' },
      ],
    },
    {
      id: 'wd-21', answer: 'SHADRACH, MESHACH AND ABED-NEGO', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Stayed standing while a whole plain bowed to a statue',
          verse: 'Daniel 3:7-12',
          clue: 'a fourth figure was seen walking with them in the fire' },
        { type: 'quote', lang: 'fil', answer: 'SADRACH, MESACH AT ABED-NEGO',
          flag: 'unverified', difficulty: 1,
          quote: 'Nanatiling nakatayo habang yumuyukod ang buong kapatagan sa rebulto',
          verse: 'Daniel 3:7-12',
          clue: 'may ikaapat na nakitang kasamang naglalakad sa gitna ng apoy' },
      ],
    },
    {
      id: 'wd-22', answer: 'JONAH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Paid his fare and sailed the opposite way from his orders',
          verse: 'Jonah 1:3',
          clue: 'he slept below deck through a storm sent for him' },
        { type: 'quote', lang: 'fil', answer: 'JONAS',
          flag: 'unverified', difficulty: 1,
          quote: 'Nagbayad ng pamasahe at naglayag sa kabilang direksyon ng utos sa kanya',
          verse: 'Jonas 1:3',
          clue: 'natulog siya sa ilalim ng barko habang may bagyong para sa kanya' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Built a shelter to sit and watch a city be destroyed',
          verse: 'Jonah 4:5',
          clue: 'a worm killed the plant that had been shading him' },
        { type: 'quote', lang: 'fil', answer: 'JONAS',
          flag: 'unverified', difficulty: 3,
          quote: 'Gumawa ng silungan para maupo at panoorin ang pagkawasak ng lungsod',
          verse: 'Jonas 4:5',
          clue: 'may uod na pumatay sa halamang lumilim sa kanya' },
      ],
    },
    {
      id: 'wd-23', answer: 'ESTHER', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Walked into a throne room without being called for',
          verse: 'Esther 5:1-2',
          clue: 'she had fasted three days before stepping through that door' },
        { type: 'quote', lang: 'fil', answer: 'ESTER',
          flag: 'unverified', difficulty: 1,
          quote: 'Pumasok sa bulwagan ng trono kahit hindi ipinatawag',
          verse: 'Ester 5:1-2',
          clue: 'tatlong araw siyang nag-ayuno bago tumawid sa pintuang iyon' },
      ],
    },
    {
      id: 'wd-24', answer: 'NEHEMIAH', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Rebuilt a city wall in fifty-two days, sword at his side',
          verse: 'Nehemiah 6:15',
          clue: 'he had been cupbearer to the king of Persia' },
        { type: 'quote', lang: 'fil', answer: 'NEHEMIAS',
          flag: 'unverified', difficulty: 1,
          quote: 'Muling itinayo ang pader ng lungsod sa limampu\'t dalawang araw, may espada sa tabi',
          verse: 'Nehemias 6:15',
          clue: 'siya ang dating tagahawak ng saro ng hari ng Persia' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Rode out at night to inspect a city\'s broken-down walls',
          verse: 'Nehemiah 2:12-15',
          clue: 'he told nobody what his God had put in his heart to do' },
        { type: 'quote', lang: 'fil', answer: 'NEHEMIAS',
          flag: 'unverified', difficulty: 3,
          quote: 'Sumakay sa gabi para tingnan ang mga gibang pader ng lungsod',
          verse: 'Nehemias 2:12-15',
          clue: 'walang pinagsabihan kung ano ang inilagay ng Diyos sa puso niya' },
      ],
    },
    {
      id: 'wd-25', answer: 'PETER', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Cut off a soldier\'s ear',
          verse: 'John 18:10',
          clue: 'he did it in a garden, at night, without being asked' },
        { type: 'quote', lang: 'fil', answer: 'PEDRO',
          flag: 'unverified', difficulty: 1,
          quote: 'Pinutol ang tainga ng isang sundalo',
          verse: 'Juan 18:10',
          clue: 'sa halamanan niya ginawa, gabi, at walang nag-utos sa kaniya' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Stepped out of a boat onto open water',
          verse: 'Matthew 14:29',
          clue: 'it went well until he looked at the wind' },
        { type: 'quote', lang: 'fil', answer: 'PEDRO',
          flag: 'unverified', difficulty: 1,
          quote: 'Lumabas ng bangka at tumapak sa tubig',
          verse: 'Mateo 14:29',
          clue: 'ayos ang lahat hanggang tumingin siya sa hangin' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Jumped overboard and swam ashore, leaving the nets to the others',
          verse: 'John 21:7',
          clue: 'he never could wait for a boat to dock' },
        { type: 'quote', lang: 'fil', answer: 'PEDRO',
          flag: 'unverified', difficulty: 2,
          quote: 'Tumalon sa dagat at lumangoy sa pampang, iniwan sa iba ang lambat',
          verse: 'Juan 21:7',
          clue: 'hindi siya makapaghintay na dumaong ang bangka' },
      ],
    },
    {
      id: 'wd-26', answer: 'PAUL', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Climbed into a basket to be let down a city wall at night',
          verse: 'Acts 9:25',
          clue: 'the men watching the gates to kill him missed him completely' },
        { type: 'quote', lang: 'fil', answer: 'PABLO',
          flag: 'unverified', difficulty: 2,
          quote: 'Pumasok sa isang basket para ibaba sa pader ng lungsod nang gabi',
          verse: 'Mga Gawa 9:25',
          clue: 'binabantayan ng mga papatay sa kaniya ang mga pintuang-bayan, pero hindi nila siya nakita' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Shook a snake off his hand into a fire after a shipwreck',
          verse: 'Acts 28:3-5',
          clue: 'the islanders decided he must be a god' },
        { type: 'quote', lang: 'fil', answer: 'PABLO',
          flag: 'unverified', difficulty: 2,
          quote: 'Ipinagpag sa apoy ang ahas na kumapit sa kamay niya matapos lumubog ang barko',
          verse: 'Mga Gawa 28:3-5',
          clue: 'akala ng mga taga-isla ay isa siyang diyos' },
      ],
    },
    {
      id: 'wd-27', answer: 'JESUS', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Braided cords into a whip and cleared a temple courtyard',
          verse: 'John 2:15',
          clue: 'the coins were still rolling when the doves flew out' },
        { type: 'quote', lang: 'fil', answer: 'JESUS',
          flag: 'unverified', difficulty: 1,
          quote: 'Gumawa ng latigo mula sa lubid at nilinis ang looban ng templo',
          verse: 'Juan 2:15',
          clue: 'gumugulong pa ang mga barya nang lumipad ang mga kalapati' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Cooked fish and bread over a charcoal fire on a beach',
          verse: 'John 21:9',
          clue: 'seven fishermen had worked all night for nothing' },
        { type: 'quote', lang: 'fil', answer: 'JESUS',
          flag: 'unverified', difficulty: 2,
          quote: 'Nagluto ng isda at tinapay sa uling sa tabing-dagat',
          verse: 'Juan 21:9',
          clue: 'pitong mangingisda ang buong gabing nagpagod nang walang huli' },
      ],
    },
    {
      id: 'wd-28', answer: 'JUDAS ISCARIOT', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Kissed a man on the cheek to point him out to armed men',
          verse: 'Matthew 26:49',
          clue: 'he came out of the dark leading a crowd with torches' },
        { type: 'quote', lang: 'fil', answer: 'JUDAS ISCARIOTE',
          flag: 'unverified', difficulty: 1,
          quote: 'Hinalikan sa pisngi ang isang lalaki para ituro siya sa mga may sandata',
          verse: 'Mateo 26:49',
          clue: 'lumabas siya sa dilim, kasunod ang pulutong na may sulo' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Threw thirty silver coins back onto a temple floor',
          verse: 'Matthew 27:5',
          clue: 'the priests used the money to buy a field' },
        { type: 'quote', lang: 'fil', answer: 'JUDAS ISCARIOTE',
          flag: 'unverified', difficulty: 2,
          quote: 'Inihagis pabalik ang tatlumpung pilak sa sahig ng templo',
          verse: 'Mateo 27:5',
          clue: 'ipinambili ng bukid ng mga saserdote ang perang iyon' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Kept the group\'s money bag and helped himself from it',
          verse: 'John 12:6',
          clue: 'he complained loudest when the perfume was poured out' },
        { type: 'quote', lang: 'fil', answer: 'JUDAS ISCARIOTE',
          flag: 'unverified', difficulty: 3,
          quote: 'Siya ang may hawak ng supot ng pera, at ninanakawan niya ito',
          verse: 'Juan 12:6',
          clue: 'siya ang pinakamaingay na dumaing nang ibuhos ang pabango' },
      ],
    },
    {
      id: 'wd-29', answer: 'JOHN THE BAPTIST', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Ate locusts and wild honey and wore a coat of camel hair',
          verse: 'Matthew 3:4',
          clue: 'his belt was leather and his pulpit was a riverbank' },
        { type: 'quote', lang: 'fil', answer: 'JUAN BAUTISTA',
          flag: 'unverified', difficulty: 1,
          quote: 'Kumain ng balang at pulot-pukyutan, at nagdamit ng balahibo ng kamelyo',
          verse: 'Mateo 3:4',
          clue: 'katad ang sinturon niya, at pampang ng ilog ang pulpito niya' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Plunged whole crowds under the water of the Jordan',
          verse: 'Matthew 3:5-6',
          clue: 'he argued with his own cousin about going in' },
        { type: 'quote', lang: 'fil', answer: 'JUAN BAUTISTA',
          flag: 'unverified', difficulty: 2,
          quote: 'Inilubog sa tubig ng Jordan ang buong pulutong ng tao',
          verse: 'Mateo 3:5-6',
          clue: 'nakipagtalo siya sa sarili niyang pinsan tungkol sa paglusong' },
      ],
    },
    {
      id: 'wd-30', answer: 'PILATE', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Washed his hands in a basin in front of a shouting crowd',
          verse: 'Matthew 27:24',
          clue: 'he had just announced he could find no fault at all' },
        { type: 'quote', lang: 'fil', answer: 'PILATO',
          flag: 'unverified', difficulty: 1,
          quote: 'Naghugas ng kamay sa palanggana sa harap ng sumisigaw na pulutong',
          verse: 'Mateo 27:24',
          clue: 'kasasabi lang niya na wala siyang makitang anumang kasalanan' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Wrote a sign in three languages and refused to reword it',
          verse: 'John 19:19-22',
          clue: 'the priests wanted one word changed and lost' },
        { type: 'quote', lang: 'fil', answer: 'PILATO',
          flag: 'unverified', difficulty: 3,
          quote: 'Sumulat ng karatula sa tatlong wika at ayaw itong baguhin',
          verse: 'Juan 19:19-22',
          clue: 'isang salita lang ang gustong ipapalit ng mga saserdote, at hindi sila pinagbigyan' },
      ],
    },
    {
      id: 'wd-31', answer: 'ZACCHAEUS', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Climbed a sycamore tree to see over a crowd',
          verse: 'Luke 19:4',
          clue: 'he was too short to see and too rich to be liked' },
        { type: 'quote', lang: 'fil', answer: 'ZAQUEO',
          flag: 'unverified', difficulty: 1,
          quote: 'Umakyat sa puno ng sikomoro para makakita sa ibabaw ng pulutong',
          verse: 'Lucas 19:4',
          clue: 'masyadong pandak para makakita, at masyadong mayaman para mahalin' },
      ],
    },
    {
      id: 'wd-32', answer: 'MARTHA', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Rushed around serving a houseful of guests while her sister sat',
          verse: 'Luke 10:40',
          clue: 'she wanted her sister up off the floor and helping' },
        { type: 'quote', lang: 'fil', answer: 'MARTA',
          flag: 'unverified', difficulty: 2,
          quote: 'Abalang-abala sa paghahain sa maraming bisita habang nakaupo lang ang kapatid niya',
          verse: 'Lucas 10:40',
          clue: 'gusto niyang tumayo ang kapatid niya sa sahig at tumulong' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Ran out down the road to meet a friend who came too late',
          verse: 'John 11:20',
          clue: 'her sister stayed sitting in the house; she did not' },
        { type: 'quote', lang: 'fil', answer: 'MARTA',
          flag: 'unverified', difficulty: 3,
          quote: 'Tumakbo palabas sa daan para salubungin ang kaibigang huli na ang dating',
          verse: 'Juan 11:20',
          clue: 'nanatiling nakaupo sa bahay ang kapatid niya; siya, hindi' },
      ],
    },
    {
      id: 'wd-33', answer: 'MARY MAGDALENE', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Asked a gardener where a missing body had been taken',
          verse: 'John 20:15',
          clue: 'he answered her by saying her name' },
        { type: 'quote', lang: 'fil', answer: 'MARIA MAGDALENA',
          flag: 'unverified', difficulty: 2,
          quote: 'Tinanong ang hardinero kung saan dinala ang nawawalang bangkay',
          verse: 'Juan 20:15',
          clue: 'sinagot siya nito sa pagbanggit ng pangalan niya' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Ran through the dark to wake two disciples about an empty grave',
          verse: 'John 20:2',
          clue: 'she went to finish a burial and found the stone rolled back' },
        { type: 'quote', lang: 'fil', answer: 'MARIA MAGDALENA',
          flag: 'unverified', difficulty: 3,
          quote: 'Tumakbo sa dilim para gisingin ang dalawang alagad tungkol sa walang lamang libingan',
          verse: 'Juan 20:2',
          clue: 'pupunta sana siya para tapusin ang paglilibing, pero naigulong na ang bato' },
      ],
    },
    {
      id: 'wd-34', answer: 'THOMAS', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Came back a week late and inspected the scars for himself',
          verse: 'John 20:26-27',
          clue: 'he had missed the meeting where everyone else saw' },
        { type: 'quote', lang: 'fil', answer: 'TOMAS',
          flag: 'unverified', difficulty: 1,
          quote: 'Bumalik makalipas ang isang linggo at siya mismo ang sumuri sa mga peklat',
          verse: 'Juan 20:26-27',
          clue: 'hindi siya nakadalo sa pagtitipon kung saan nakakita ang lahat' },
      ],
    },
    {
      id: 'wd-35', answer: 'THE PRODIGAL SON', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Fed pigs in a foreign field and envied what they were eating',
          verse: 'Luke 15:15-16',
          clue: 'he rehearsed his apology all the way home' },
        { type: 'quote', lang: 'fil', answer: 'ANG ALIBUGHANG ANAK',
          flag: 'unverified', difficulty: 1,
          quote: 'Nagpakain ng baboy sa ibang lupain at nainggit sa kinakain ng mga ito',
          verse: 'Lucas 15:15-16',
          clue: 'inensayo niya ang paghingi ng tawad habang pauwi' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Sold up, moved far away, and spent every coin on parties',
          verse: 'Luke 15:13',
          clue: 'he had asked for his share of the farm early' },
        { type: 'quote', lang: 'fil', answer: 'ANG ALIBUGHANG ANAK',
          flag: 'unverified', difficulty: 2,
          quote: 'Ipinagbili ang lahat, lumayo, at inubos ang bawat sentimo sa pagsasaya',
          verse: 'Lucas 15:13',
          clue: 'maaga niyang hiningi ang bahagi niya sa bukid' },
      ],
    },
    {
      id: 'wd-36', answer: 'THE GOOD SAMARITAN', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Poured oil and wine on a stranger\'s wounds and paid his bill',
          verse: 'Luke 10:34-35',
          clue: 'two religious men had already walked past the same body' },
        { type: 'quote', lang: 'fil', answer: 'ANG MABUTING SAMARITANO',
          flag: 'unverified', difficulty: 1,
          quote: 'Binuhusan ng langis at alak ang sugat ng estranghero, at siya ang nagbayad',
          verse: 'Lucas 10:34-35',
          clue: 'dalawang lalaking relihiyoso ang nauna nang dumaan sa katawang iyon' },
      ],
    },
    {
      id: 'wd-37', answer: 'THE WOMAN AT THE WELL', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Left her water jar behind and ran to tell a whole town',
          verse: 'John 4:28',
          clue: 'she had come out at noon to avoid the other women' },
        { type: 'quote', lang: 'fil', answer: 'ANG BABAE SA BALON',
          flag: 'unverified', difficulty: 1,
          quote: 'Iniwan ang kaniyang banga at tumakbo para ibalita sa buong bayan',
          verse: 'Juan 4:28',
          clue: 'tanghaling-tapat siya pumunta para iwasan ang ibang kababaihan' },
      ],
    },
    {
      id: 'wd-38', answer: 'NICODEMUS', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Knocked on a teacher\'s door after dark to ask his questions',
          verse: 'John 3:1-2',
          clue: 'a Pharisee who did not want to be seen asking' },
        { type: 'quote', lang: 'fil', answer: 'NICODEMO',
          flag: 'unverified', difficulty: 2,
          quote: 'Kumatok sa pinto ng isang guro pagkagabi para magtanong',
          verse: 'Juan 3:1-2',
          clue: 'isang Fariseo na ayaw makitang nagtatanong' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Carried a hundred pounds of myrrh and aloes to a burial',
          verse: 'John 19:39',
          clue: 'the first time he came, he came at night' },
        { type: 'quote', lang: 'fil', answer: 'NICODEMO',
          flag: 'unverified', difficulty: 3,
          quote: 'Nagdala ng isang daang libra ng mira at aloe sa isang paglilibing',
          verse: 'Juan 19:39',
          clue: 'noong unang pagpunta niya, gabi siya dumating' },
      ],
    },
    {
      id: 'wd-39', answer: 'LAZARUS', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Walked out of a tomb wrapped head to foot in burial cloths',
          verse: 'John 11:44',
          clue: 'his two sisters had stopped expecting anything' },
        { type: 'quote', lang: 'fil', answer: 'LAZARO',
          flag: 'unverified', difficulty: 1,
          quote: 'Lumakad palabas ng libingan, nakabalot ng telang panlibing mula ulo hanggang paa',
          verse: 'Juan 11:44',
          clue: 'wala nang inaasahan ang dalawa niyang kapatid' },
      ],
    },
    {
      id: 'wd-40', answer: 'CAIAPHAS', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Tore his own robe during a midnight trial he had called',
          verse: 'Matthew 26:65',
          clue: 'he was the high priest that year' },
        { type: 'quote', lang: 'fil', answer: 'CAIFAS',
          flag: 'unverified', difficulty: 3,
          quote: 'Pinunit ang sarili niyang balabal sa hatinggabing paglilitis na siya ang nagpatawag',
          verse: 'Mateo 26:65',
          clue: 'siya ang dakilang saserdote nang taong iyon' },
      ],
    },
    {
      id: 'wd-41', answer: 'STEPHEN', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Knelt under a hail of stones and prayed for the men throwing',
          verse: 'Acts 7:60',
          clue: 'he was the first of many to die that way' },
        { type: 'quote', lang: 'fil', answer: 'ESTEBAN',
          flag: 'unverified', difficulty: 2,
          quote: 'Lumuhod sa ulan ng bato at ipinanalangin ang mga pumupukol',
          verse: 'Mga Gawa 7:60',
          clue: 'siya ang una sa marami na namatay nang ganoon' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Handed out food to widows before he ever preached a sermon',
          verse: 'Acts 6:5',
          clue: 'one of the first seven men chosen for the job' },
        { type: 'quote', lang: 'fil', answer: 'ESTEBAN',
          flag: 'unverified', difficulty: 3,
          quote: 'Namahagi ng pagkain sa mga biyuda bago pa siya nangaral',
          verse: 'Mga Gawa 6:5',
          clue: 'isa sa unang pitong lalaking pinili para sa gawaing iyon' },
      ],
    },
    {
      id: 'wd-42', answer: 'DORCAS', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Sewed coats and dresses for the widows of a seaside town',
          verse: 'Acts 9:36-39',
          clue: 'the widows held up her sewing and wept over it' },
        { type: 'quote', lang: 'fil', answer: 'DORCAS',
          flag: 'unverified', difficulty: 2,
          quote: 'Nanahi ng damit at balabal para sa mga biyuda ng bayang tabing-dagat',
          verse: 'Mga Gawa 9:36-39',
          clue: 'itinaas ng mga biyuda ang tinahi niya habang umiiyak' },
      ],
    },
    {
      id: 'wd-43', answer: 'BARNABAS', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Sold a field and laid every coin at the apostles\' feet',
          verse: 'Acts 4:36-37',
          clue: 'he vouched for the church\'s worst enemy when nobody else would' },
        { type: 'quote', lang: 'fil', answer: 'BERNABE',
          flag: 'unverified', difficulty: 3,
          quote: 'Ipinagbili ang bukid at inilagay ang buong pera sa paanan ng mga apostol',
          verse: 'Mga Gawa 4:36-37',
          clue: 'siya lang ang nanindigan para sa pinakamalaking kaaway ng iglesia' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Took a young deserter back on the road after a bitter argument',
          verse: 'Acts 15:37-39',
          clue: 'the argument split the mission team in two' },
        { type: 'quote', lang: 'fil', answer: 'BERNABE',
          flag: 'unverified', difficulty: 3,
          quote: 'Isinama ulit sa paglalakbay ang batang umatras, matapos ang matinding pagtatalo',
          verse: 'Mga Gawa 15:37-39',
          clue: 'nahati sa dalawa ang grupong misyonero dahil sa pagtatalong iyon' },
      ],
    },
    {
      id: 'wd-44', answer: 'PHILIP', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Ran alongside a moving chariot, then climbed in to read along',
          verse: 'Acts 8:30-31',
          clue: 'the passenger was reading Isaiah out loud and understood none' },
        { type: 'quote', lang: 'fil', answer: 'FELIPE',
          flag: 'unverified', difficulty: 2,
          quote: 'Tumakbo sa tabi ng umaandar na karwahe, saka sumakay para makibasa',
          verse: 'Mga Gawa 8:30-31',
          clue: 'malakas na binabasa ng sakay ang Isaias pero wala siyang naiintindihan' },
      ],
    },
    {
      id: 'wd-45', answer: 'HEROD', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Ordered every boy under two in one town killed',
          verse: 'Matthew 2:16',
          clue: 'the wise men never came back to report as promised' },
        { type: 'quote', lang: 'fil', answer: 'HERODES',
          flag: 'unverified', difficulty: 2,
          quote: 'Ipinapatay ang lahat ng batang lalaking wala pang dalawang taon sa isang bayan',
          verse: 'Mateo 2:16',
          clue: 'hindi na bumalik ang mga pantas para mag-ulat gaya ng pangako' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Sat on a throne in royal robes and accepted a crowd\'s worship',
          verse: 'Acts 12:21-22',
          clue: 'worms finished what the applause started' },
        { type: 'quote', lang: 'fil', answer: 'HERODES',
          flag: 'unverified', difficulty: 3,
          quote: 'Naupo sa trono na nakadamit-hari at tinanggap ang pagsamba ng pulutong',
          verse: 'Mga Gawa 12:21-22',
          clue: 'ang mga uod ang tumapos sa sinimulan ng palakpakan' },
      ],
    },
    {
      id: 'wd-46', answer: 'JOHN THE APOSTLE', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Wrote letters to seven churches while exiled on a rocky island',
          verse: 'Revelation 1:9-11',
          clue: 'he outlived every other one of the twelve' },
        { type: 'quote', lang: 'fil', answer: 'JUAN NA APOSTOL',
          flag: 'unverified', difficulty: 2,
          quote: 'Sumulat ng liham sa pitong iglesia habang ipinatapon sa mabatong isla',
          verse: 'Apocalipsis 1:9-11',
          clue: 'siya ang pinakahuling nabuhay sa labindalawa' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Outran another disciple to an empty tomb and stopped at the door',
          verse: 'John 20:4-5',
          clue: 'the slower man arrived second and went in first' },
        { type: 'quote', lang: 'fil', answer: 'JUAN NA APOSTOL',
          flag: 'unverified', difficulty: 3,
          quote: 'Nauna sa kapwa alagad papunta sa walang lamang libingan, pero tumigil sa pintuan',
          verse: 'Juan 20:4-5',
          clue: 'ang mas mabagal ay pangalawang dumating pero naunang pumasok' },
      ],
    },
  ],
};
