/*
 * Higher or Lower - the deck.
 *
 * GENERATED. Do not edit by hand: run
 *
 *     node tools/make-higher-or-lower.js
 *
 * after changing tools/numbers.json, which is the one hand-written thing behind
 * this game and the only place a number should ever be corrected.
 *
 * THE GAME. A number from the Bible, then one to bet on - or three to choose
 * from. Two beats: the question, then the answer with where it comes from.
 * This is the one game here with a gambling shape: the room commits before it
 * knows, which is a different feeling from the others, all of which reward
 * recall. That is why a two-way question is right here and was wrong for What
 * Came First? - nobody is expected to KNOW, so nobody is robbed by luck.
 *
 * THE ACCURACY RULE. The number must be STATED in the text, never summed or
 * inferred, and must read the SAME in any common translation. See
 * tools/numbers.json for what that excluded and why - Goliath's height and
 * "seventy times seven" are both out, and the ten plagues are out because
 * Exodus never says ten.
 *
 * ONE KNOWN ROUGH EDGE. A bet GIVES one number in order to ask about another,
 * so a round can state a number that a later puzzle asks for. It is a filler
 * game and the room having seen it counts as reinforcement rather than a leak,
 * but it is real, and no build-time generator can prevent it: the round is
 * drawn at random when the game starts.
 */
window.DECK = {
  id: 'higher-or-lower',
  title: 'Higher or Lower',
  idPrefix: 'hl',   // shown on the projector, so it must never hint the answer
  shuffle: true,
  // Two beats a puzzle, like What Came First?, so a round moves fast.
  sessionSize: 15,
  languages: ['en'],
  howToPlay: [
    'A number from the Bible, then one to bet on.',
    'Sometimes three to choose from instead.',
  ],
  // No credits and no versions: nothing here is quoted. The sentences are
  // ours, and a number belongs to nobody.
  puzzles: [
    {
      id: 'hl-01', answer: 'Methuselah lived 969 years · Genesis 5:27', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Abraham lived 175 years. Did METHUSELAH live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'LONGER',
          ref: 'Methuselah lived 969 years — the oldest age in the Bible · Genesis 5:27' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did METHUSELAH live?',
          options: ['930', '950', '969'],
          answer: '969',
          ref: 'the oldest age in the Bible · Genesis 5:27' },
      ],
    },
    {
      id: 'hl-02', answer: 'Noah lived 950 years · Genesis 9:29', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'Enoch lived 365 years. Did NOAH live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'LONGER',
          ref: 'Noah lived 950 years — nineteen short of the record · Genesis 9:29' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did NOAH live?',
          options: ['930', '950', '969'],
          answer: '950',
          ref: 'nineteen short of the record · Genesis 9:29' },
      ],
    },
    {
      id: 'hl-03', answer: 'Adam lived 930 years · Genesis 5:5', difficulty: 3,
      variants: [
        { type: 'binary', difficulty: 3,
          prompt: 'Methuselah lived 969 years. Did ADAM live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'SHORTER',
          ref: 'Adam lived 930 years — the first man, and nearly the oldest · Genesis 5:5' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did ADAM live?',
          options: ['930', '950', '969'],
          answer: '930',
          ref: 'the first man, and nearly the oldest · Genesis 5:5' },
      ],
    },
    {
      id: 'hl-04', answer: 'Enoch lived 365 years · Genesis 5:23', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'Moses lived 120 years. Did ENOCH live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'LONGER',
          ref: 'Enoch lived 365 years — he walked with God and did not die · Genesis 5:23' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many years did ENOCH live?',
          options: ['175', '180', '365'],
          answer: '365',
          ref: 'he walked with God and did not die · Genesis 5:23' },
      ],
    },
    {
      id: 'hl-05', answer: 'Isaac lived 180 years · Genesis 35:28', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'Enoch lived 365 years. Did ISAAC live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'SHORTER',
          ref: 'Isaac lived 180 years — he outlived his father Abraham · Genesis 35:28' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did ISAAC live?',
          options: ['127', '175', '180'],
          answer: '180',
          ref: 'he outlived his father Abraham · Genesis 35:28' },
      ],
    },
    {
      id: 'hl-06', answer: 'Abraham lived 175 years · Genesis 25:7', difficulty: 3,
      variants: [
        { type: 'binary', difficulty: 3,
          prompt: 'Sarah lived 127 years. Did ABRAHAM live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'LONGER',
          ref: 'Abraham lived 175 years — the father of the faithful · Genesis 25:7' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did ABRAHAM live?',
          options: ['127', '175', '180'],
          answer: '175',
          ref: 'the father of the faithful · Genesis 25:7' },
      ],
    },
    {
      id: 'hl-07', answer: 'Sarah lived 127 years · Genesis 23:1', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Noah lived 950 years. Did SARAH live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'SHORTER',
          ref: 'Sarah lived 127 years — Abraham’s wife, who laughed at the promise · Genesis 23:1' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did SARAH live?',
          options: ['110', '120', '127'],
          answer: '127',
          ref: 'Abraham’s wife, who laughed at the promise · Genesis 23:1' },
      ],
    },
    {
      id: 'hl-08', answer: 'Moses lived 120 years · Deuteronomy 34:7', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'Enoch lived 365 years. Did MOSES live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'SHORTER',
          ref: 'Moses lived 120 years — his eye was not dim at the end · Deuteronomy 34:7' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did MOSES live?',
          options: ['110', '120', '127'],
          answer: '120',
          ref: 'his eye was not dim at the end · Deuteronomy 34:7' },
      ],
    },
    {
      id: 'hl-09', answer: 'Joseph lived 110 years · Genesis 50:26', difficulty: 3,
      variants: [
        { type: 'binary', difficulty: 3,
          prompt: 'Sarah lived 127 years. Did JOSEPH live longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'SHORTER',
          ref: 'Joseph lived 110 years — he died in Egypt and was embalmed · Genesis 50:26' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did JOSEPH live?',
          options: ['110', '120', '127'],
          answer: '110',
          ref: 'he died in Egypt and was embalmed · Genesis 50:26' },
      ],
    },
    {
      id: 'hl-10', answer: 'The floodwaters prevailed for 150 days · Genesis 7:24', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Lazarus was in the tomb 4 days. Did the FLOODWATERS last more or fewer days?',
          options: ['MORE', 'FEWER'],
          answer: 'MORE',
          ref: 'The floodwaters prevailed for 150 days — before the water began to go down · Genesis 7:24' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many days did the FLOODWATERS prevail?',
          options: ['6', '40', '150'],
          answer: '150',
          ref: 'before the water began to go down · Genesis 7:24' },
      ],
    },
    {
      id: 'hl-11', answer: 'Rain fell on the earth for 40 days · Genesis 7:12', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'The floodwaters prevailed for 150 days. Did the RAIN fall for more or fewer days?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'Rain fell on the earth for 40 days — forty days and forty nights · Genesis 7:12' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many days did the RAIN fall?',
          options: ['6', '40', '150'],
          answer: '40',
          ref: 'forty days and forty nights · Genesis 7:12' },
      ],
    },
    {
      id: 'hl-12', answer: 'God made heaven and earth in 6 days · Exodus 20:11', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'Lazarus was in the tomb 4 days. Did CREATION take more or fewer days?',
          options: ['MORE', 'FEWER'],
          answer: 'MORE',
          ref: 'God made heaven and earth in 6 days — and He rested on the seventh · Exodus 20:11' },
        { type: 'binary', difficulty: 2,
          prompt: 'In how many days did God make the world?',
          options: ['3', '4', '6'],
          answer: '6',
          ref: 'and He rested on the seventh · Exodus 20:11' },
      ],
    },
    {
      id: 'hl-13', answer: 'Lazarus was in the tomb 4 days · John 11:17', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'The floodwaters prevailed for 150 days. Was LAZARUS in the tomb more or fewer days?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'Lazarus was in the tomb 4 days — already dead when Jesus arrived · John 11:17' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many days was LAZARUS in the tomb?',
          options: ['3', '4', '6'],
          answer: '4',
          ref: 'already dead when Jesus arrived · John 11:17' },
      ],
    },
    {
      id: 'hl-14', answer: 'Jonah was in the great fish 3 days · Jonah 1:17', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'God made heaven and earth in 6 days. Was JONAH in the fish more or fewer days?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'Jonah was in the great fish 3 days — three days and three nights · Jonah 1:17' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many days was JONAH in the fish?',
          options: ['3', '4', '6'],
          answer: '3',
          ref: 'three days and three nights · Jonah 1:17' },
      ],
    },
    {
      id: 'hl-15', answer: 'Abraham\'s seed was afflicted 400 years · Genesis 15:13', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Israel wandered the wilderness 40 years. Was the AFFLICTION in Egypt longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'LONGER',
          ref: 'Abraham\'s seed was afflicted 400 years — God told Abraham before it happened · Genesis 15:13' },
        { type: 'binary', difficulty: 1,
          prompt: 'How long was Abraham\'s seed afflicted?',
          options: ['40', '70', '400'],
          answer: '400',
          ref: 'God told Abraham before it happened · Genesis 15:13' },
      ],
    },
    {
      id: 'hl-16', answer: 'Judah served Babylon 70 years · Jeremiah 25:11', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'The famine in Egypt lasted 7 years. Was the BABYLON captivity longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'LONGER',
          ref: 'Judah served Babylon 70 years — Jeremiah named the length in advance · Jeremiah 25:11' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many years was Judah in Babylon?',
          options: ['38', '40', '70'],
          answer: '70',
          ref: 'Jeremiah named the length in advance · Jeremiah 25:11' },
      ],
    },
    {
      id: 'hl-17', answer: 'Israel wandered the wilderness 40 years · Numbers 14:33', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'A woman had an issue of blood 12 years. Was the WILDERNESS wandering longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'LONGER',
          ref: 'Israel wandered the wilderness 40 years — one year for each day the spies searched · Numbers 14:33' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many years did Israel wander?',
          options: ['38', '40', '70'],
          answer: '40',
          ref: 'one year for each day the spies searched · Numbers 14:33' },
      ],
    },
    {
      id: 'hl-18', answer: 'The man at the pool was ill 38 years · John 5:5', difficulty: 3,
      variants: [
        { type: 'binary', difficulty: 3,
          prompt: 'Israel wandered the wilderness 40 years. Was the POOL man\'s illness longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'SHORTER',
          ref: 'The man at the pool was ill 38 years — Jesus told him to take up his bed · John 5:5' },
        { type: 'binary', difficulty: 3,
          prompt: 'How long was the man at the pool ill?',
          options: ['38', '40', '70'],
          answer: '38',
          ref: 'Jesus told him to take up his bed · John 5:5' },
      ],
    },
    {
      id: 'hl-19', answer: 'A woman had an issue of blood 12 years · Mark 5:25', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Judah served Babylon 70 years. Did the SICK WOMAN suffer longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'SHORTER',
          ref: 'A woman had an issue of blood 12 years — healed by touching Jesus\' garment · Mark 5:25' },
        { type: 'binary', difficulty: 2,
          prompt: 'How long had the bleeding woman suffered?',
          options: ['7', '12', '38'],
          answer: '12',
          ref: 'healed by touching Jesus\' garment · Mark 5:25' },
      ],
    },
    {
      id: 'hl-20', answer: 'The famine in Egypt lasted 7 years · Genesis 41:30', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'A woman had an issue of blood 12 years. Was EGYPT\'S FAMINE longer or shorter?',
          options: ['LONGER', 'SHORTER'],
          answer: 'SHORTER',
          ref: 'The famine in Egypt lasted 7 years — it followed the years of plenty · Genesis 41:30' },
        { type: 'binary', difficulty: 2,
          prompt: 'How long did the famine in Egypt last?',
          options: ['7', '12', '38'],
          answer: '7',
          ref: 'it followed the years of plenty · Genesis 41:30' },
      ],
    },
    {
      id: 'hl-21', answer: '144,000 were sealed out of Israel\'s tribes · Revelation 7:4', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Jesus chose 12 disciples. Were more or fewer sealed in Revelation?',
          options: ['MORE', 'FEWER'],
          answer: 'MORE',
          ref: '144,000 were sealed out of Israel\'s tribes — twelve thousand from each tribe · Revelation 7:4' },
        { type: 'binary', difficulty: 1,
          prompt: 'How many were sealed in Revelation?',
          options: ['4,000', '5,000', '144,000'],
          answer: '144,000',
          ref: 'twelve thousand from each tribe · Revelation 7:4' },
      ],
    },
    {
      id: 'hl-22', answer: 'Jesus fed 5000 men beside women and children · Matthew 14:21', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Jesus chose 12 disciples. At the FIRST feeding, more or fewer men?',
          options: ['MORE', 'FEWER'],
          answer: 'MORE',
          ref: 'Jesus fed 5000 men beside women and children — from a boy\'s loaves and fish · Matthew 14:21' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many men did Jesus feed the first time?',
          options: ['3,000', '4,000', '5,000'],
          answer: '5,000',
          ref: 'from a boy\'s loaves and fish · Matthew 14:21' },
      ],
    },
    {
      id: 'hl-23', answer: 'Jesus later fed 4000 men the same way · Matthew 15:38', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: '144,000 were sealed out of Israel\'s tribes. At the SECOND feeding, more or fewer men?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'Jesus later fed 4000 men the same way — a second miracle most people forget · Matthew 15:38' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many men did Jesus feed the second time?',
          options: ['3,000', '4,000', '5,000'],
          answer: '4,000',
          ref: 'a second miracle most people forget · Matthew 15:38' },
      ],
    },
    {
      id: 'hl-24', answer: '3000 were baptized at Pentecost · Acts 2:41', difficulty: 3,
      variants: [
        { type: 'binary', difficulty: 3,
          prompt: 'Jesus later fed 4000 men the same way. Were more or fewer baptized at Pentecost?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: '3000 were baptized at Pentecost — after one sermon by Peter · Acts 2:41' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many were baptized at Pentecost?',
          options: ['3,000', '4,000', '5,000'],
          answer: '3,000',
          ref: 'after one sermon by Peter · Acts 2:41' },
      ],
    },
    {
      id: 'hl-25', answer: 'Gideon kept 300 men to fight Midian · Judges 7:7', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Jesus later fed 4000 men the same way. Did GIDEON keep more or fewer men?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'Gideon kept 300 men to fight Midian — chosen by the way they drank · Judges 7:7' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many men did Gideon keep?',
          options: ['120', '300', '3,000'],
          answer: '300',
          ref: 'chosen by the way they drank · Judges 7:7' },
      ],
    },
    {
      id: 'hl-26', answer: 'About 120 believers met in the upper room · Acts 1:15', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'Gideon kept 300 men to fight Midian. Were more or fewer in the UPPER ROOM?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'About 120 believers met in the upper room — waiting together for Pentecost · Acts 1:15' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many believers met in the upper room?',
          options: ['12', '120', '300'],
          answer: '120',
          ref: 'waiting together for Pentecost · Acts 1:15' },
      ],
    },
    {
      id: 'hl-27', answer: 'Jesus chose 12 disciples · Luke 6:13', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Jesus later fed 4000 men the same way. Did Jesus choose more or fewer disciples?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'Jesus chose 12 disciples — He named them apostles · Luke 6:13' },
        { type: 'binary', difficulty: 1,
          prompt: 'How many disciples did Jesus choose?',
          options: ['12', '120', '300'],
          answer: '12',
          ref: 'He named them apostles · Luke 6:13' },
      ],
    },
    {
      id: 'hl-28', answer: 'Judas was paid 30 pieces of silver · Matthew 26:15', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'They circled Jericho 7 times on the last day. Was JUDAS paid more or fewer pieces of silver?',
          options: ['MORE', 'FEWER'],
          answer: 'MORE',
          ref: 'Judas was paid 30 pieces of silver — the price of a slave · Matthew 26:15' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many pieces of silver was Judas paid?',
          options: ['10', '12', '30'],
          answer: '30',
          ref: 'the price of a slave · Matthew 26:15' },
      ],
    },
    {
      id: 'hl-29', answer: '12 baskets of leftovers were gathered · Matthew 14:20', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'Judas was paid 30 pieces of silver. Were more or fewer baskets of leftovers taken up?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: '12 baskets of leftovers were gathered — more left over than they started with · Matthew 14:20' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many baskets of leftovers were gathered?',
          options: ['7', '10', '12'],
          answer: '12',
          ref: 'more left over than they started with · Matthew 14:20' },
      ],
    },
    {
      id: 'hl-30', answer: 'God gave 10 commandments · Exodus 34:28', difficulty: 3,
      variants: [
        { type: 'binary', difficulty: 3,
          prompt: '12 baskets of leftovers were gathered. Did God give more or fewer commandments?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'God gave 10 commandments — written with the finger of God · Exodus 34:28' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many commandments did God give?',
          options: ['7', '10', '12'],
          answer: '10',
          ref: 'written with the finger of God · Exodus 34:28' },
      ],
    },
    {
      id: 'hl-31', answer: 'They circled Jericho 7 times on the last day · Joshua 6:4', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: 'Judas was paid 30 pieces of silver. More or fewer laps of Jericho on the last day?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'They circled Jericho 7 times on the last day — then the walls fell down flat · Joshua 6:4' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many laps of Jericho on the last day?',
          options: ['5', '7', '10'],
          answer: '7',
          ref: 'then the walls fell down flat · Joshua 6:4' },
      ],
    },
    {
      id: 'hl-32', answer: 'Jesus fed the crowd from 5 loaves · Matthew 14:17', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: '12 baskets of leftovers were gathered. Did they start with more or fewer loaves?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'Jesus fed the crowd from 5 loaves — and two small fish · Matthew 14:17' },
        { type: 'binary', difficulty: 3,
          prompt: 'How many loaves did they start with?',
          options: ['3', '5', '7'],
          answer: '5',
          ref: 'and two small fish · Matthew 14:17' },
      ],
    },
    {
      id: 'hl-33', answer: 'Peter denied Jesus 3 times · Matthew 26:34', difficulty: 2,
      variants: [
        { type: 'binary', difficulty: 2,
          prompt: 'Moses carried 2 tablets of stone. Did PETER deny Jesus more or fewer times?',
          options: ['MORE', 'FEWER'],
          answer: 'MORE',
          ref: 'Peter denied Jesus 3 times — before the rooster crowed · Matthew 26:34' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many times did Peter deny Jesus?',
          options: ['2', '3', '5'],
          answer: '3',
          ref: 'before the rooster crowed · Matthew 26:34' },
      ],
    },
    {
      id: 'hl-34', answer: 'Moses carried 2 tablets of stone · Exodus 34:1', difficulty: 1,
      variants: [
        { type: 'binary', difficulty: 1,
          prompt: '12 baskets of leftovers were gathered. Did Moses carry more or fewer tablets of stone?',
          options: ['MORE', 'FEWER'],
          answer: 'FEWER',
          ref: 'Moses carried 2 tablets of stone — he broke the first pair in anger · Exodus 34:1' },
        { type: 'binary', difficulty: 2,
          prompt: 'How many tablets of stone did Moses carry?',
          options: ['2', '3', '5'],
          answer: '2',
          ref: 'he broke the first pair in anger · Exodus 34:1' },
      ],
    },
  ],
};
