/*
 * Who Said It? - the deck.
 *
 * A line someone in the Bible said goes on the projector; the room shouts who
 * said it. Four clicks: the quote, then the verse, then a clue, then the name.
 *
 *   answer     the person, revealed last
 *   quote      the line. English quotes are NKJV; Tagalog quotes are MBB and
 *              are pasted in by hand - see "Tagalog" below.
 *   verse      where it is said. Shown BEFORE the clue on purpose: the
 *              reference is itself a hint for whoever has read the passage.
 *   clue       one line about the speaker that does not name them
 *   verseAtReveal
 *              hold the verse back to the reveal. REQUIRED when the book is
 *              named after the speaker - "Jonah 2:2" under JONAH hands the
 *              answer over. validate.js refuses a deck that forgets.
 *   lang       'en' or 'fil'. On the VARIANT, not the puzzle: PEDRO and PETER
 *              are the same person, so they are one puzzle.
 *   answer     on a variant, the name in that language - PEDRO for PETER.
 *   flag       'unverified' until a human has checked the wording against the
 *              Bible. validate.js counts them; the game master page tags them.
 *
 * The puzzle is the PERSON and each quote is a VARIANT. That is what makes
 * rounds work: a person cannot come up twice in one round, but a later round
 * can bring them back with a line the room has not heard.
 *
 * TAGALOG. The Magandang Balita Biblia text belongs to the Philippine Bible
 * Society, so it is NOT drafted into this repository. What is drafted is
 * everything around it - the name, the reference and the clue, which are our
 * own words. A quote with no text is DORMANT: never drawn, exactly as a
 * variant whose picture file is missing is never drawn. Paste the line in
 * with the deck manager and it wakes up.
 */
window.DECK = {
  id: 'who-said-it',
  title: 'Who Said It?',
  idPrefix: 'qs',   // shown on the projector, so it must never hint the answer
  shuffle: true,
  sessionSize: 20,
  // Both languages are declared, but Tagalog has nothing playable until its
  // lines are pasted in - so the start screen offers English alone until then,
  // rather than a choice that leads to an empty round.
  languages: ['en', 'fil'],
  howToPlay: [
    'A line someone in the Bible said. The room says who said it.',
    'Stuck? The next click gives the verse, then a clue.',
  ],
  // Named on the start screen, so whoever runs the game sees which
  // translation the room is about to hear before they begin.
  versions: {
    en: 'New King James Version',
    fil: 'Ang Dating Biblia (1905)',
  },
  // Shown small at the foot of the screen, for the language being played.
  credits: {
    en: 'Scripture taken from the New King James Version®. '
      + 'Copyright © 1982 by Thomas Nelson. Used by permission. '
      + 'All rights reserved.',
    // Ang Dating Biblia (1905): public domain, and FETCHED from a public
    // source rather than written from memory - which is the only reason there
    // is Tagalog scripture in this file at all. If these lines are ever
    // replaced with Magandang Balita Biblia text, this notice has to become
    // the Philippine Bible Society's:
    //   Scripture texts are from the Magandang Balita Biblia (c) 2026
    //   Philippine Bible Society, used with permission.
    fil: 'Ang Dating Biblia (1905) — public domain.',
  },
  puzzles: [
    {
      id: 'qs-01', answer: 'CAIN', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'I do not know. Am I my brother\'s keeper?',
          verse: 'Genesis 4:9',
          clue: 'A farmer dodging a question about his younger brother.' },
        { type: 'quote', lang: 'fil', answer: 'CAIN', flag: 'unverified', difficulty: 1,
          quote: 'Aywan ko: ako ba\'y tagapagbantay sa aking kapatid?',
          verse: 'Genesis 4:9',
          clue: 'nagsasaka siya; ang kapatid niya ay pastol ng tupa' },
      ],
    },
    {
      id: 'qs-02', answer: 'GOD', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Let there be light.',
          verse: 'Genesis 1:3',
          clue: 'the first words anyone speaks in the Bible' },
        { type: 'quote', lang: 'fil', answer: 'DIYOS', flag: 'unverified', difficulty: 1,
          quote: 'Magkaroon ng liwanag',
          verse: 'Genesis 1:3',
          clue: 'ang kauna-unahang salitang binigkas sa Bibliya' },
      ],
    },
    {
      id: 'qs-03', answer: 'ISAIAH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'Here am I! Send me.',
          verse: 'Isaiah 6:8',
          clue: 'he saw the Lord on a throne, and a coal touched his lips' },
        { type: 'quote', lang: 'fil', answer: 'ISAIAS', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'Narito ako; suguin mo ako.',
          verse: 'Isaias 6:8',
          clue: 'nakita niya ang Panginoon sa trono, at may baga sa kanyang labi' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Woe is me, for I am undone! Because I am a man of unclean lips, and I dwell in the midst of a people of unclean lips.',
          verse: 'Isaiah 6:5',
          clue: 'A seraphim flew to him with a live coal from the altar and touched his mouth.' },
      ],
    },
    {
      id: 'qs-04', answer: 'RUTH', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Wherever you go, I will go; and wherever you lodge, I will lodge; your people shall be my people, and your God, my God.',
          verse: 'Ruth 1:16',
          clue: 'A Moabite widow refusing to leave her mother-in-law on the road home.' },
        { type: 'quote', lang: 'fil', answer: 'RUT', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Kung saan ka pumaroon, ay paroroon ako: at kung saan ka tumigil, ay titigil ako: ang iyong bayan ay magiging aking bayan, at ang iyong Dios ay aking Dios',
          verse: 'Rut 1:16',
          clue: 'sinabi niya ito sa kanyang biyenan, palabas ng Moab' },
      ],
    },
    {
      id: 'qs-05', answer: 'PETER', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'You are the Christ, the Son of the living God.',
          verse: 'Matthew 16:16',
          clue: 'a fisherman; Jesus called him a rock' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'I do not know the Man!',
          verse: 'Matthew 26:72',
          clue: 'he said it three times, by a fire, before dawn' },
        { type: 'quote', lang: 'fil', answer: 'PEDRO', flag: 'unverified', difficulty: 2,
          quote: 'Ikaw ang Cristo, Ang anak ng Dios na buhay.',
          verse: 'Mateo 16:16',
          clue: 'isang mangingisda; tinawag siyang bato ni Jesus' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Depart from me, for I am a sinful man, O Lord!',
          verse: 'Luke 5:8',
          clue: 'He had fished all night and caught nothing, until the nets nearly broke.' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Silver and gold I do not have, but what I do have I give you: In the name of Jesus Christ of Nazareth, rise up and walk.',
          verse: 'Acts 3:6',
          clue: 'A fisherman who once sank in the waves, now speaking at a temple gate' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Repent, and let every one of you be baptized in the name of Jesus Christ for the remission of sins.',
          verse: 'Acts 2:38',
          clue: 'He preached the first sermon of the church, after denying his Lord three times' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'We ought to obey God rather than men.',
          verse: 'Acts 5:29',
          clue: 'Standing before the council that had condemned his Master' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Not so, Lord! For I have never eaten anything common or unclean.',
          verse: 'Acts 10:14',
          clue: 'He argued with a voice from heaven while hungry on a rooftop' },
      ],
    },
    {
      id: 'qs-06', answer: 'PILATE', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'What is truth?',
          verse: 'John 18:38',
          clue: 'he asked it of the prisoner in front of him, then washed his hands' },
        { type: 'quote', lang: 'fil', answer: 'PILATO', flag: 'unverified', difficulty: 3,
          quote: 'Ano ang katotohanan?',
          verse: 'Juan 18:38',
          clue: 'tinanong niya ito sa bilanggo sa harap niya, saka naghugas ng kamay' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'What I have written, I have written.',
          verse: 'John 19:22',
          clue: 'He refused to change the sign nailed above a condemned man\'s head.' },
      ],
    },
    {
      id: 'qs-07', answer: 'ADAM', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'The woman whom You gave to be with me, she gave me of the tree, and I ate.',
          verse: 'Genesis 3:12',
          clue: 'Caught out in the garden, he passes the blame straight to his wife.' },
        { type: 'quote', lang: 'fil', answer: 'ADAN', flag: 'unverified', difficulty: 1,
          quote: 'Ang babaing ibinigay mong aking kasamahin, ay siyang nagbigay sa akin ng bunga ng punong kahoy at aking kinain.',
          verse: 'Genesis 3:12',
          clue: 'nahuli sa hardin, at ang asawa niya agad ang isinisi' },
      ],
    },
    {
      id: 'qs-08', answer: 'EVE', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'The serpent deceived me, and I ate.',
          verse: 'Genesis 3:13',
          clue: 'Her turn to answer, and she passes the blame further down.' },
        { type: 'quote', lang: 'fil', answer: 'EVA', flag: 'unverified', difficulty: 1,
          quote: 'Dinaya ako ng ahas, at ako\'y kumain.',
          verse: 'Genesis 3:13',
          clue: 'siya naman ang tinanong, at ang ahas naman ang isinisi niya' },
      ],
    },
    {
      id: 'qs-09', answer: 'ABRAHAM', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'My son, God will provide for Himself the lamb for a burnt offering.',
          verse: 'Genesis 22:8',
          clue: 'Walking up a mountain with his boy, a knife, and no animal.' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Please say you are my sister, that it may be well with me for your sake.',
          verse: 'Genesis 12:13',
          clue: 'Heading into Egypt with a beautiful wife and a nervous plan.' },
        { type: 'quote', lang: 'fil', answer: 'ABRAHAM', flag: 'unverified', difficulty: 1,
          quote: 'Dios ang maghahanda ng korderong pinakahandog na susunugin, anak ko',
          verse: 'Genesis 22:8',
          clue: 'umaakyat sa bundok kasama ang anak, may dalang patalim pero walang tupa' },
      ],
    },
    {
      id: 'qs-10', answer: 'JOSEPH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'But as for you, you meant evil against me; but God meant it for good.',
          verse: 'Genesis 50:20',
          clue: 'He is speaking to the brothers who once dropped him in a pit.' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'How then can I do this great wickedness, and sin against God?',
          verse: 'Genesis 39:9',
          clue: 'A slave in a rich Egyptian house, refusing his master\'s wife.' },
        { type: 'quote', lang: 'fil', answer: 'JOSE', flag: 'unverified', difficulty: 1,
          quote: 'At tungkol sa inyo ay inyong ipinalagay na kasamaan laban sa akin; nguni\'t ipinalagay ng Dios na kabutihan',
          verse: 'Genesis 50:20',
          clue: 'kausap niya ang mga kapatid na naghulog sa kanya sa balon noon' },
      ],
    },
    {
      id: 'qs-11', answer: 'MOSES', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Who am I that I should go to Pharaoh, and that I should bring the children of Israel out of Egypt?',
          verse: 'Exodus 3:11',
          clue: 'A shepherd arguing with a bush that will not burn up.' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Do not be afraid. Stand still, and see the salvation of the LORD, which He will accomplish for you today.',
          verse: 'Exodus 14:13',
          clue: 'Sea in front, chariots behind, staff in his hand.' },
        { type: 'quote', lang: 'fil', answer: 'MOISES', flag: 'unverified', difficulty: 1,
          quote: 'Sino ako, upang pumaroon kay Faraon, at upang ilabas sa Egipto ang mga anak ni Israel?',
          verse: 'Exodo 3:11',
          clue: 'isang pastol na nakikipagtalo sa palumpong na hindi naman nasusunog' },
      ],
    },
    {
      id: 'qs-12', answer: 'SARAH', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'God has made me laugh, and all who hear will laugh with me.',
          verse: 'Genesis 21:6',
          clue: 'Ninety years old and holding her first baby.' },
        { type: 'quote', lang: 'fil', answer: 'SARA', flag: 'unverified', difficulty: 2,
          quote: 'Pinatawa ako ng Dios, sinomang makarinig ay makikitawa.',
          verse: 'Genesis 21:6',
          clue: 'siyamnapung taong gulang na, kandong ang kauna-unahang anak niya' },
      ],
    },
    {
      id: 'qs-13', answer: 'ISAAC', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Look, the fire and the wood, but where is the lamb for a burnt offering?',
          verse: 'Genesis 22:7',
          clue: 'The boy carrying the wood up the hill, asking a very good question.' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'The voice is Jacob\'s voice, but the hands are the hands of Esau.',
          verse: 'Genesis 27:22',
          clue: 'Old and blind, and something about this dinner is not right.' },
        { type: 'quote', lang: 'fil', answer: 'ISAAC', flag: 'unverified', difficulty: 2,
          quote: 'Narito, ang apoy at ang kahoy, nguni\'t saan naroon ang korderong pinakahandog na susunugin?',
          verse: 'Genesis 22:7',
          clue: 'ang batang pasan ang kahoy paakyat sa burol, may napakatalas na tanong' },
      ],
    },
    {
      id: 'qs-14', answer: 'ESAU', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Look, I am about to die; so what is this birthright to me?',
          verse: 'Genesis 25:32',
          clue: 'He came in starving from the hunt and smelled his brother\'s stew.' },
        { type: 'quote', lang: 'fil', answer: 'ESAU', flag: 'unverified', difficulty: 2,
          quote: 'Narito, ako\'y namamatay: at saan ko mapapakinabangan ang pagkapanganay?',
          verse: 'Genesis 25:32',
          clue: 'galing sa pangangaso, gutom na gutom, naamoy ang niluluto ng kapatid' },
      ],
    },
    {
      id: 'qs-15', answer: 'JACOB', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'I will not let You go unless You bless me!',
          verse: 'Genesis 32:26',
          clue: 'He has been wrestling all night by a river and comes away limping.' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Surely the LORD is in this place, and I did not know it.',
          verse: 'Genesis 28:16',
          clue: 'He woke up from a dream, with a stone for a pillow.' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'It is enough. Joseph my son is still alive. I will go and see him before I die.',
          verse: 'Genesis 45:28',
          clue: 'An old father, told that the son he mourned for years is alive.' },
        { type: 'quote', lang: 'fil', answer: 'JACOB', flag: 'unverified', difficulty: 2,
          quote: 'Hindi kita bibitawan hanggang hindi mo ako mabasbasan.',
          verse: 'Genesis 32:26',
          clue: 'magdamag siyang nakipagbuno sa tabi ng ilog, at umalis na paika-ika' },
      ],
    },
    {
      id: 'qs-16', answer: 'PHARAOH', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Who is the LORD, that I should obey His voice to let Israel go? I do not know the LORD, nor will I let Israel go.',
          verse: 'Exodus 5:2',
          clue: 'On a throne, hearing a demand from two Hebrew brothers.' },
        { type: 'quote', lang: 'fil', answer: 'FARAON', flag: 'unverified', difficulty: 2,
          quote: 'Sino ang Panginoon na aking pakikinggan ang kaniyang tinig, upang pahintulutan kong yumaon ang Israel?',
          verse: 'Exodo 5:2',
          clue: 'nakaupo sa trono, dalawang Hebreong magkapatid ang may hinihingi sa kanya' },
      ],
    },
    {
      id: 'qs-17', answer: 'AARON', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'So they gave it to me, and I cast it into the fire, and this calf came out.',
          verse: 'Exodus 32:24',
          clue: 'The worst excuse in the Old Testament, given to his furious brother.' },
        { type: 'quote', lang: 'fil', answer: 'AARON', flag: 'unverified', difficulty: 2,
          quote: 'Kanilang ibinigay sa akin: at aking inihagis sa apoy at lumabas ang guyang ito.',
          verse: 'Exodo 32:24',
          clue: 'pinakapalpak na dahilan sa Lumang Tipan, sinabi sa galit na galit na kapatid' },
      ],
    },
    {
      id: 'qs-18', answer: 'JUDAH', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'What profit is there if we kill our brother and conceal his blood?',
          verse: 'Genesis 37:26',
          clue: 'One of the brothers, doing the maths at the edge of a pit.' },
        { type: 'quote', lang: 'fil', answer: 'JUDA', flag: 'unverified', difficulty: 3,
          quote: 'Anong ating mapapakinabang kung ating patayin ang ating kapatid, at ilihim ang kaniyang dugo?',
          verse: 'Genesis 37:26',
          clue: 'isa sa magkakapatid, nagkukwenta ng kikitain sa gilid ng balon' },
      ],
    },
    {
      id: 'qs-19', answer: 'CALEB', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Let us go up at once and take possession, for we are well able to overcome it.',
          verse: 'Numbers 13:30',
          clue: 'One of only two spies who came back from the land unafraid.' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Now therefore, give me this mountain of which the LORD spoke in that day.',
          verse: 'Joshua 14:12',
          clue: 'Eighty-five years old, and one of only two spies who brought back a good report.' },
        { type: 'quote', lang: 'fil', answer: 'CALEB', flag: 'unverified', difficulty: 3,
          quote: 'Ating akyating paminsan, at ating ariin; sapagka\'t kaya nating lupigin.',
          verse: 'Mga Bilang 13:30',
          clue: 'isa lang sa dalawang espiya na bumalik na walang katakot-takot' },
      ],
    },
    {
      id: 'qs-20', answer: 'BALAAM', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'How shall I curse whom God has not cursed? And how shall I denounce whom the LORD has not denounced?',
          verse: 'Numbers 23:8',
          clue: 'Hired by a worried king to curse Israel, standing on a hilltop.' },
        { type: 'quote', lang: 'fil', answer: 'BALAAM', flag: 'unverified', difficulty: 3,
          quote: 'Paanong aking susumpain ang hindi sinumpa ng Dios? At paanong aking lalaitin ang hindi nilait ng Panginoon?',
          verse: 'Mga Bilang 23:8',
          clue: 'inupahan ng balisang hari para sumpain ang Israel, nakatayo sa tuktok ng burol' },
      ],
    },
    {
      id: 'qs-21', answer: 'JOSHUA', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'But as for me and my house, we will serve the LORD.',
          verse: 'Joshua 24:15',
          clue: 'Moses\' successor, giving his farewell challenge to the tribes at Shechem.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Sun, stand still over Gibeon; and Moon, in the Valley of Aijalon.',
          verse: 'Joshua 10:12',
          clue: 'A commander praying out loud in the middle of a battle against five kings.' },
        { type: 'quote', lang: 'fil', answer: 'JOSUE', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'Nguni\'t sa ganang akin at ng aking sangbahayan ay maglilingkod kami sa Panginoon.',
          verse: 'Josue 24:15',
          clue: 'kahalili ni Moises, huling hamon niya sa mga tribo doon sa Sikem' },
      ],
    },
    {
      id: 'qs-22', answer: 'RAHAB', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'I know that the LORD has given you the land, that the terror of you has fallen on us.',
          verse: 'Joshua 2:9',
          clue: 'She hid two spies under stalks of flax on her roof in Jericho.' },
        { type: 'quote', lang: 'fil', answer: 'RAHAB', flag: 'unverified', difficulty: 3,
          quote: 'Talastas ko na ibinigay sa inyo ng Panginoon ang lupain, at dinatnan kami ng pangingilabot sa inyo',
          verse: 'Josue 2:9',
          clue: 'itinago niya ang dalawang espiya sa ilalim ng lino sa bubong niya sa Jerico' },
      ],
    },
    {
      id: 'qs-23', answer: 'GIDEON', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'O my lord, if the LORD is with us, why then has all this happened to us?',
          verse: 'Judges 6:13',
          clue: 'He was threshing wheat in a winepress when an angel called him a mighty man of valor.' },
        { type: 'quote', lang: 'fil', answer: 'GEDEON', flag: 'unverified', difficulty: 3,
          quote: 'Oh Panginoon ko, kung ang Panginoon ay sumasaamin, bakit nga ang lahat ng ito ay sumapit sa amin?',
          verse: 'Mga Hukom 6:13',
          clue: 'naggigiik ng trigo sa pisaan ng ubas nang tawagin siyang magiting ng anghel' },
      ],
    },
    {
      id: 'qs-24', answer: 'SAMSON', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Let me die with the Philistines!',
          verse: 'Judges 16:30',
          clue: 'Blind and chained between two pillars in a temple full of his enemies.' },
        { type: 'quote', lang: 'fil', answer: 'SANSON', flag: 'unverified', difficulty: 2,
          quote: 'Mamatay nawa akong kasama ng mga Filisteo',
          verse: 'Mga Hukom 16:30',
          clue: 'bulag at nakakadena sa pagitan ng dalawang haligi, puno ng kaaway ang templo' },
      ],
    },
    {
      id: 'qs-25', answer: 'HANNAH', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'For this child I prayed, and the LORD has granted me my petition which I asked of Him.',
          verse: '1 Samuel 1:27',
          clue: 'She prayed so desperately at the tabernacle that the priest thought she was drunk.' },
        { type: 'quote', lang: 'fil', answer: 'ANA', flag: 'unverified', difficulty: 2,
          quote: 'Dahil sa batang ito ako nanalangin; at ipinagkaloob sa akin ng Panginoon ang aking hiling na aking hiningi sa kaniya',
          verse: '1 Samuel 1:27',
          clue: 'sobrang taimtim manalangin sa tabernakulo kaya akala ng pari lasing siya' },
      ],
    },
    {
      id: 'qs-26', answer: 'SAMUEL', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'Speak, for Your servant hears.',
          verse: '1 Samuel 3:10',
          clue: 'A boy sleeping in the tabernacle who kept thinking the old priest was calling him.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Behold, to obey is better than sacrifice, and to heed than the fat of rams.',
          verse: '1 Samuel 15:22',
          clue: 'The prophet confronting the first king over the sheep and cattle he kept alive.' },
        { type: 'quote', lang: 'fil', answer: 'SAMUEL', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'Magsalita ka; sapagka\'t dinirinig ng iyong lingkod.',
          verse: '1 Samuel 3:10',
          clue: 'batang natutulog sa tabernakulo, akala niya ang matandang pari ang tumatawag' },
      ],
    },
    {
      id: 'qs-27', answer: 'ELI', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'It is the LORD. Let Him do what seems good to Him.',
          verse: '1 Samuel 3:18',
          clue: 'The old priest at Shiloh whose two sons disgraced the tabernacle.' },
        { type: 'quote', lang: 'fil', answer: 'ELI', flag: 'unverified', difficulty: 3,
          quote: 'Panginoon nga: gawin niya ang inaakala niyang mabuti.',
          verse: '1 Samuel 3:18',
          clue: 'matandang pari sa Silo na ang dalawang anak ang nagpahiya sa tabernakulo' },
      ],
    },
    {
      id: 'qs-28', answer: 'GOLIATH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Am I a dog, that you come to me with sticks?',
          verse: '1 Samuel 17:43',
          clue: 'Nine feet tall, in bronze armor, insulted by the sight of a shepherd boy.' },
        { type: 'quote', lang: 'fil', answer: 'GOLIAT', flag: 'unverified', difficulty: 1,
          quote: 'Ako ba ay aso, na ikaw ay paririto sa akin na may mga tungkod?',
          verse: '1 Samuel 17:43',
          clue: 'siyam na talampakan ang taas, tanso ang baluti, naiinis sa isang batang pastol' },
      ],
    },
    {
      id: 'qs-29', answer: 'DAVID', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'You come to me with a sword, with a spear, and with a javelin. But I come to you in the name of the LORD of hosts.',
          verse: '1 Samuel 17:45',
          clue: 'A teenager with a sling and five smooth stones from the brook.' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'What have I done now? Is there not a cause?',
          verse: '1 Samuel 17:29',
          clue: 'The youngest of eight brothers, sent to the battle line with bread and cheese.' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'O my son Absalom, my son, my son Absalom, if only I had died in your place!',
          verse: '2 Samuel 18:33',
          clue: 'A king weeping in the chamber over the gate after a rebellion was crushed.' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'The LORD is my shepherd; I shall not want.',
          verse: 'Psalm 23:1',
          clue: 'He kept sheep as a boy, played the harp for a troubled king, and later wore the crown himself.' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Create in me a clean heart, O God, and renew a steadfast spirit within me.',
          verse: 'Psalm 51:10',
          clue: 'A king writing after a prophet told him a story about a poor man\'s one little lamb.' },
        { type: 'quote', lang: 'fil', answer: 'DAVID', flag: 'unverified', difficulty: 1,
          quote: 'Ikaw ay naparirito sa akin na may tabak, at may malaking sibat at may kalasag; nguni\'t ako\'y naparirito laban sa iyo sa pangalan ng Panginoon ng mga hukbo',
          verse: '1 Samuel 17:45',
          clue: 'binatilyong may tirador at limang makinis na bato mula sa sapa' },
      ],
    },
    {
      id: 'qs-30', answer: 'NATHAN', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'You are the man!',
          verse: '2 Samuel 12:7',
          clue: 'The prophet who trapped a king with a story about a poor man\'s one little lamb.' },
        { type: 'quote', lang: 'fil', answer: 'NATAN', flag: 'unverified', difficulty: 2,
          quote: 'Ikaw ang lalaking yaon.',
          verse: '2 Samuel 12:7',
          clue: 'propetang binitag ang hari sa kwento ng iisang kordero ng mahirap' },
      ],
    },
    {
      id: 'qs-31', answer: 'SOLOMON', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Divide the living child in two, and give half to one, and half to the other.',
          verse: '1 Kings 3:25',
          clue: 'A young king settling an argument between two women claiming one baby.' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'But will God indeed dwell on the earth? Behold, heaven and the heaven of heavens cannot contain You.',
          verse: '1 Kings 8:27',
          clue: 'He was dedicating the temple his father had always wanted to build.' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Vanity of vanities, all is vanity.',
          verse: 'Ecclesiastes 1:2',
          clue: 'The king who built the temple, tried every pleasure money could buy, and called it all empty.' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Trust in the LORD with all your heart, and lean not on your own understanding.',
          verse: 'Proverbs 3:5',
          clue: 'God offered him anything he wanted and he asked for wisdom instead of riches or long life.' },
        { type: 'quote', lang: 'fil', answer: 'SOLOMON', flag: 'unverified', difficulty: 1,
          quote: 'Hatiin ng dalawa ang buhay na bata, at ibigay ang kalahati sa isa at ang kalahati ay sa isa.',
          verse: '1 Mga Hari 3:25',
          clue: 'batang hari na humahatol sa dalawang babaeng nag-aagawan sa isang sanggol' },
      ],
    },
    {
      id: 'qs-32', answer: 'ELIJAH', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'How long will you falter between two opinions? If the LORD is God, follow Him; but if Baal, follow him.',
          verse: '1 Kings 18:21',
          clue: 'Standing on Mount Carmel in front of the whole nation and 450 rival prophets.' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Cry aloud, for he is a god; either he is meditating, or he is busy, or he is on a journey.',
          verse: '1 Kings 18:27',
          clue: 'He is mocking prophets who have been cutting themselves all day with no answer.' },
        { type: 'quote', lang: 'fil', answer: 'ELIAS', flag: 'unverified', difficulty: 2,
          quote: 'Hanggang kaylan kayo mangagaalinlangan sa dalawang isipan? kung ang Panginoon ay Dios, sumunod kayo sa kaniya: nguni\'t kung si Baal, sumunod nga kayo sa kaniya.',
          verse: '1 Mga Hari 18:21',
          clue: 'nakatayo sa Bundok Carmelo, harap ang buong bansa at 450 propeta ng Baal' },
      ],
    },
    {
      id: 'qs-33', answer: 'NAAMAN', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Are not the Abanah and the Pharpar, the rivers of Damascus, better than all the waters of Israel?',
          verse: '2 Kings 5:12',
          clue: 'A Syrian army commander with leprosy, offended by embarrassingly simple instructions.' },
        { type: 'quote', lang: 'fil', answer: 'NAAMAN', flag: 'unverified', difficulty: 3,
          quote: 'Hindi ba ang Abana at ang Pharphar, na mga ilog ng Damasco, ay mainam kay sa lahat ng tubig sa Israel?',
          verse: '2 Mga Hari 5:12',
          clue: 'kumandante ng hukbo ng Siria na may ketong, nainsulto sa sobrang simpleng utos' },
      ],
    },
    {
      id: 'qs-34', answer: 'NEHEMIAH', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'I am doing a great work, so that I cannot come down.',
          verse: 'Nehemiah 6:3',
          clue: 'Rebuilding Jerusalem\'s wall, refusing to meet his enemies on the plain of Ono.' },
        { type: 'quote', lang: 'fil', verseAtReveal: true, answer: 'NEHEMIAS', flag: 'unverified', difficulty: 3,
          quote: 'Ako\'y gumagawa ng dakilang gawain, na anopa\'t hindi ako makababa',
          verse: 'Nehemias 6:3',
          clue: 'itinatayo ang pader ng Jerusalem, ayaw makipagkita sa kaaway sa kapatagan ng Ono' },
      ],
    },
    {
      id: 'qs-35', answer: 'ESTHER', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'And so I will go to the king, which is against the law; and if I perish, I perish!',
          verse: 'Esther 4:16',
          clue: 'A queen deciding to walk into the throne room without being summoned.' },
        { type: 'quote', lang: 'fil', verseAtReveal: true, answer: 'ESTER', flag: 'unverified', difficulty: 1,
          quote: 'At sa gayo\'y papasukin ko ang hari, na hindi ayon sa kautusan: at kung ako\'y mamatay ay mamatay.',
          verse: 'Ester 4:16',
          clue: 'reyna na nagpasyang pumasok sa trono kahit hindi naman siya ipinatawag' },
      ],
    },
    {
      id: 'qs-36', answer: 'MORDECAI', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Yet who knows whether you have come to the kingdom for such a time as this?',
          verse: 'Esther 4:14',
          clue: 'He sat in sackcloth at the palace gate after refusing to bow to Haman.' },
        { type: 'quote', lang: 'fil', answer: 'MARDOQUEO', flag: 'unverified', difficulty: 2,
          quote: 'At sinong nakakaalam na kung kaya ka pinasapit sa kaharian ay dahil sa bagay na ito?',
          verse: 'Ester 4:14',
          clue: 'nakaupo sa pintuan ng palasyo, naka-sako, ayaw talagang yumukod kay Haman' },
      ],
    },
    {
      id: 'qs-37', answer: 'JOB', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'The LORD gave, and the LORD has taken away; blessed be the name of the LORD.',
          verse: 'Job 1:21',
          clue: 'He lost his children, his herds and his servants in a single day, and still worshiped.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'For I know that my Redeemer lives, and He shall stand at last on the earth.',
          verse: 'Job 19:25',
          clue: 'Covered in boils, scraping himself with a piece of broken pottery, and still sure God would clear his name.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Though He slay me, yet will I trust Him.',
          verse: 'Job 13:15',
          clue: 'Three friends came a long way to comfort him and only made things worse.' },
        { type: 'quote', lang: 'fil', answer: 'JOB', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'Ang Panginoon ang nagbigay, at ang Panginoon ang nagalis; purihin ang pangalan ng Panginoon.',
          verse: 'Job 1:21',
          clue: 'isang araw lang, nawala ang anak, hayop at katulong niya; sumamba pa rin siya' },
      ],
    },
    {
      id: 'qs-38', answer: 'JOB\'S WIFE', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'Do you still hold fast to your integrity? Curse God and die!',
          verse: 'Job 2:9',
          clue: 'She lost the same ten children he did, and this is the only line she gets.' },
        { type: 'quote', lang: 'fil', answer: 'ASAWA NI JOB', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'Namamalagi ka pa ba sa iyong pagtatapat? itakuwil mo ang Dios, at mamatay ka.',
          verse: 'Job 2:9',
          clue: 'nawalan din siya ng sampung anak, pero isang linya lang ang naisagot niya' },
      ],
    },
    {
      id: 'qs-39', answer: 'JEREMIAH', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Ah, Lord GOD! Behold, I cannot speak, for I am a youth.',
          verse: 'Jeremiah 1:6',
          clue: 'God told him He knew him before he was formed in the womb, and he answered that he was far too young.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'His word was in my heart like a burning fire shut up in my bones; I was weary of holding it back, and I could not.',
          verse: 'Jeremiah 20:9',
          clue: 'The weeping prophet, thrown into a muddy cistern, who tried to quit preaching and found he couldn\'t.' },
        { type: 'quote', lang: 'fil', answer: 'JEREMIAS', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Ah, Panginoong Dios! narito, hindi ako marunong magsalita: sapagka\'t ako\'y bata.',
          verse: 'Jeremias 1:6',
          clue: 'sabi ng Diyos kilala na siya bago pa ipanganak; sagot niya, bata pa raw siya' },
      ],
    },
    {
      id: 'qs-40', answer: 'EZEKIEL', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'O Lord GOD, You know.',
          verse: 'Ezekiel 37:3',
          clue: 'God set him down in a valley full of dry bones and asked him whether they could live.' },
        { type: 'quote', lang: 'fil', answer: 'EZEKIEL', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'Oh Panginoong Dios; ikaw ang nakakaalam.',
          verse: 'Ezekiel 37:3',
          clue: 'inilagay siya ng Diyos sa libis ng tuyong buto, tinanong kung mabubuhay pa' },
      ],
    },
    {
      id: 'qs-41', answer: 'DANIEL', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'O king, live forever! My God sent His angel and shut the lions\' mouths, so that they have not hurt me.',
          verse: 'Daniel 6:22',
          clue: 'He kept praying at his open window three times a day even after the new law made it a crime.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'MENE: God has numbered your kingdom, and finished it.',
          verse: 'Daniel 5:26',
          clue: 'The only man in the palace who could read the handwriting that appeared on the wall during a feast.' },
        { type: 'quote', lang: 'fil', answer: 'DANIEL', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'Ang Dios ko\'y nagsugo ng kaniyang anghel, at itinikom ang mga bibig ng mga leon, at hindi nila ako sinaktan',
          verse: 'Daniel 6:22',
          clue: 'tuloy pa rin ang tatlong beses na dasal sa bukas na bintana kahit bawal na' },
      ],
    },
    {
      id: 'qs-42', answer: 'SHADRACH, MESHACH, AND ABED-NEGO', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Our God whom we serve is able to deliver us from the burning fiery furnace, and He will deliver us from your hand, O king.',
          verse: 'Daniel 3:17',
          clue: 'Three friends who refused to bow to a golden image when the music played.' },
        { type: 'quote', lang: 'fil', answer: 'SADRAC, MESAC, AT ABED-NEGO', flag: 'unverified', difficulty: 2,
          quote: 'Narito, ang aming Dios na aming pinaglilingkuran ay makapagliligtas sa amin sa mabangis na hurnong nagniningas; at ililigtas niya kami sa iyong kamay, Oh hari.',
          verse: 'Daniel 3:17',
          clue: 'tatlong magkakaibigan na ayaw yumukod sa gintong rebulto nang tumugtog ang musika' },
      ],
    },
    {
      id: 'qs-43', answer: 'NEBUCHADNEZZAR', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Look! I see four men loose, walking in the midst of the fire, and they are not hurt, and the form of the fourth is like the Son of God.',
          verse: 'Daniel 3:25',
          clue: 'The king who ordered the furnace heated seven times hotter, then looked inside and got a shock.' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Is not this great Babylon, that I have built for a royal dwelling by my mighty power and for the glory of my majesty?',
          verse: 'Daniel 4:30',
          clue: 'He boasted from his palace roof and spent the next seven seasons eating grass like an ox.' },
        { type: 'quote', lang: 'fil', answer: 'NABUCODONOSOR', flag: 'unverified', difficulty: 3,
          quote: 'Narito, aking nakikita ay apat na lalake na hindi gapos na nagsisilakad sa gitna ng apoy, at sila\'y walang paso; at ang anyo ng ikaapat ay kawangis ng isang anak ng mga dios.',
          verse: 'Daniel 3:25',
          clue: 'hari na nag-utos na pitong ulit na initin ang hurno, tapos nagulat sa nakita' },
      ],
    },
    {
      id: 'qs-44', answer: 'JONAH', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 1,
          quote: 'Pick me up and throw me into the sea; then the sea will become calm for you.',
          verse: 'Jonah 1:12',
          clue: 'He paid his fare to sail the opposite way from where God sent him, then slept through the storm.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'I am a Hebrew; and I fear the LORD, the God of heaven, who made the sea and the dry land.',
          verse: 'Jonah 1:9',
          clue: 'The terrified sailors shook him awake and demanded to know who he was and where he came from.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'It is better for me to die than to live.',
          verse: 'Jonah 4:3',
          clue: 'He sulked on a hillside because a wicked city repented, and God grew a plant to shade him.' },
        { type: 'quote', lang: 'fil', verseAtReveal: true, answer: 'JONAS', flag: 'unverified', difficulty: 1,
          quote: 'Ako\'y inyong buhatin, at ihagis ninyo ako sa dagat; sa gayo\'y ang dagat ay tatahimik sa inyo',
          verse: 'Jonas 1:12',
          clue: 'nagbayad ng pamasahe pakabila ng utos ng Diyos, nakatulog sa gitna ng bagyo' },
      ],
    },
    {
      id: 'qs-45', answer: 'MICAH', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'What does the LORD require of you but to do justly, to love mercy, and to walk humbly with your God?',
          verse: 'Micah 6:8',
          clue: 'A prophet from a small country town who named Bethlehem as the birthplace of the Ruler to come.' },
        { type: 'quote', lang: 'fil', verseAtReveal: true, answer: 'MIKAS', flag: 'unverified', difficulty: 2,
          quote: 'At ano ang hinihingi ng Panginoon sa iyo, kundi gumawa na may kaganapan, at ibigin ang kaawaan, at lumakad na may kababaan na kasama ng iyong Dios.',
          verse: 'Mikas 6:8',
          clue: 'propeta mula sa maliit na bayan, tinuro ang Betlehem bilang sisilangan ng Tagapamahala' },
      ],
    },
    {
      id: 'qs-46', answer: 'HABAKKUK', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'Though the fig tree may not blossom, nor fruit be on the vines, yet I will rejoice in the LORD.',
          verse: 'Habakkuk 3:17',
          clue: 'A prophet who spent a whole short book arguing with God, then set his answer to music.' },
        { type: 'quote', lang: 'fil', verseAtReveal: true, answer: 'HABAKUK', flag: 'unverified', difficulty: 3,
          quote: 'Sapagka\'t bagama\'t ang puno ng igos ay hindi namumulaklak, Ni magkakaroon man ng bunga sa mga puno ng ubas',
          verse: 'Habakuk 3:17',
          clue: 'buong aklat siyang nakipagtalo sa Diyos, tapos ginawang awit ang sagot' },
      ],
    },
    {
      id: 'qs-47', answer: 'AMOS', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'I was no prophet, nor was I a son of a prophet, but I was a sheepbreeder and a tender of sycamore fruit.',
          verse: 'Amos 7:14',
          clue: 'A herdsman from Tekoa sent north to a kingdom that told him to go home and preach somewhere else.' },
        { type: 'quote', lang: 'fil', answer: 'AMOS', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'Ako\'y hindi propeta, o anak man ng propeta; kundi ako\'y pastor, at manggagawa sa mga puno ng sikomoro',
          verse: 'Amos 7:14',
          clue: 'pastol mula sa Tekoa, pinauwi ng kaharian sa hilaga: doon ka na lang daw mangaral' },
      ],
    },
    {
      id: 'qs-48', answer: 'THOMAS', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'My Lord and my God!',
          verse: 'John 20:28',
          clue: 'The disciple who missed the first appearance and finally got his own.' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Unless I see in His hands the print of the nails, and put my hand into His side, I will not believe.',
          verse: 'John 20:25',
          clue: 'One of the Twelve who wanted evidence before he would commit.' },
        { type: 'quote', lang: 'fil', answer: 'TOMAS', flag: 'unverified', difficulty: 1,
          quote: 'Panginoon ko at Dios ko.',
          verse: 'Juan 20:28',
          clue: 'ang alagad na hindi umabot sa unang pagpapakita, kaya binigyan ng sarili niya' },
      ],
    },
    {
      id: 'qs-49', answer: 'JUDAS ISCARIOT', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'What are you willing to give me if I deliver Him to you?',
          verse: 'Matthew 26:15',
          clue: 'One of the Twelve, quietly doing business with the chief priests.' },
        { type: 'quote', lang: 'fil', answer: 'HUDAS ISCARIOTE', flag: 'unverified', difficulty: 1,
          quote: 'Ano ang ibig ninyong ibigay sa akin, at siya\'y ibibigay ko sa inyo?',
          verse: 'Mateo 26:15',
          clue: 'isa sa Labindalawa, tahimik na nakikipagtransaksyon sa mga punong pari' },
      ],
    },
    {
      id: 'qs-50', answer: 'JOHN THE BAPTIST', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Behold! The Lamb of God who takes away the sin of the world!',
          verse: 'John 1:29',
          clue: 'A wilderness preacher in camel\'s hair, pointing at a man walking past.' },
        { type: 'quote', flag: 'unverified', verseAtReveal: true, difficulty: 3,
          quote: 'He must increase, but I must decrease.',
          verse: 'John 3:30',
          clue: 'His own crowd was shrinking, and he said that was exactly right.' },
        { type: 'quote', lang: 'fil', answer: 'JUAN BAUTISTA', flag: 'unverified', verseAtReveal: true, difficulty: 2,
          quote: 'Narito, ang Cordero ng Dios, na nagaalis ng kasalanan ng sanglibutan!',
          verse: 'Juan 1:29',
          clue: 'mangangaral sa ilang, damit na balahibo ng kamelyo, itinuturo ang dumaraan' },
      ],
    },
    {
      id: 'qs-51', answer: 'MARY', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Behold the maidservant of the Lord! Let it be to me according to your word.',
          verse: 'Luke 1:38',
          clue: 'A young woman in Nazareth answering an angel.' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'My soul magnifies the Lord, and my spirit has rejoiced in God my Savior.',
          verse: 'Luke 1:46',
          clue: 'Expecting a child, she burst into song while visiting a relative in the hill country.' },
        { type: 'quote', lang: 'fil', answer: 'MARIA', flag: 'unverified', difficulty: 2,
          quote: 'Narito, ang alipin ng Panginoon; mangyari sa akin ang ayon sa iyong salita.',
          verse: 'Lucas 1:38',
          clue: 'dalagang taga-Nazaret na sumasagot sa isang anghel' },
      ],
    },
    {
      id: 'qs-52', answer: 'MARTHA', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Lord, do You not care that my sister has left me to serve alone? Therefore tell her to help me.',
          verse: 'Luke 10:40',
          clue: 'The one doing all the cooking while the other one sat and listened.' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Lord, by this time there is a stench, for he has been dead four days.',
          verse: 'John 11:39',
          clue: 'The practical sister at a tomb in Bethany, worried about the smell.' },
        { type: 'quote', lang: 'fil', answer: 'MARTA', flag: 'unverified', difficulty: 2,
          quote: 'Panginoon, wala bagang anoman sa iyo, na pabayaan ako ng aking kapatid na babae na maglingkod na magisa? iutos mo nga sa kaniya na ako\'y tulungan niya.',
          verse: 'Lucas 10:40',
          clue: 'siya ang abalang-abala sa pagluluto habang nakaupo\'t nakikinig ang isa' },
      ],
    },
    {
      id: 'qs-53', answer: 'THE CENTURION', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Truly this Man was the Son of God!',
          verse: 'Mark 15:39',
          clue: 'The Roman officer on execution duty, who changed his mind at the very end.' },
        { type: 'quote', lang: 'fil', answer: 'ANG SENTURYON', flag: 'unverified', difficulty: 2,
          quote: 'Katotohanang ang taong ito ay Anak ng Dios.',
          verse: 'Marcos 15:39',
          clue: 'opisyal na Romanong nakatalaga sa pagbitay, nagbago ang isip sa huling sandali' },
      ],
    },
    {
      id: 'qs-54', answer: 'THE THIEF ON THE CROSS', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Lord, remember me when You come into Your kingdom.',
          verse: 'Luke 23:42',
          clue: 'A condemned man hanging beside Jesus, hours from death, asking for one thing.' },
        { type: 'quote', lang: 'fil', answer: 'ANG MAGNANAKAW SA KRUS', flag: 'unverified', difficulty: 2,
          quote: 'Jesus, alalahanin mo ako, pagdating mo sa iyong kaharian.',
          verse: 'Lucas 23:42',
          clue: 'hatol na kamatayan, ilang oras na lang, may isang bagay siyang hiniling kay Jesus' },
      ],
    },
    {
      id: 'qs-55', answer: 'ZACCHAEUS', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Look, Lord, I give half of my goods to the poor; and if I have taken anything from anyone by false accusation, I restore fourfold.',
          verse: 'Luke 19:8',
          clue: 'A short, rich tax man who climbed a tree for a better view.' },
        { type: 'quote', lang: 'fil', answer: 'ZAQUEO', flag: 'unverified', difficulty: 2,
          quote: 'Narito, Panginoon, ang kalahati ng aking mga pag-aari ay ibinibigay ko sa mga dukha; at kung sakali\'t nakasingil akong may daya sa kanino mang tao, ay isinasauli ko ng makaapat.',
          verse: 'Lucas 19:8',
          clue: 'pandak at mayamang maniningil ng buwis na umakyat sa puno para makasilip' },
      ],
    },
    {
      id: 'qs-56', answer: 'NICODEMUS', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'How can a man be born when he is old? Can he enter a second time into his mother\'s womb and be born?',
          verse: 'John 3:4',
          clue: 'A ruler of the Jews who came for a conversation after dark.' },
        { type: 'quote', lang: 'fil', answer: 'NICODEMO', flag: 'unverified', difficulty: 3,
          quote: 'Paanong maipanganganak ang tao kung siya\'y matanda na? makapapasok baga siyang bilang ikalawa sa tiyan ng kaniyang ina, at ipanganak?',
          verse: 'Juan 3:4',
          clue: 'isang pinuno ng mga Judio na dumating para makipag-usap nang gabing-gabi' },
      ],
    },
    {
      id: 'qs-57', answer: 'THE WOMAN AT THE WELL', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Sir, give me this water, that I may not thirst, nor come here to draw.',
          verse: 'John 4:15',
          clue: 'A Samaritan who came out alone at noon; the stranger there knew her whole history.' },
        { type: 'quote', lang: 'fil', answer: 'ANG BABAE SA BALON', flag: 'unverified', difficulty: 3,
          quote: 'Ginoo, ibigay mo sa akin ang tubig na ito, upang ako\'y huwag mauhaw, ni pumarito man sa ganito kalayo upang umigib pa.',
          verse: 'Juan 4:15',
          clue: 'Samaritana na nag-isang lumabas sa tanghali; alam ng estranghero ang buong buhay niya' },
      ],
    },
    {
      id: 'qs-58', answer: 'GABRIEL', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Do not be afraid, Mary, for you have found favor with God.',
          verse: 'Luke 1:30',
          clue: 'A messenger sent from God to a young girl in Nazareth.' },
        { type: 'quote', lang: 'fil', answer: 'GABRIEL', flag: 'unverified', difficulty: 3,
          quote: 'Huwag kang matakot, Maria: sapagka\'t nakasumpong ka ng biyaya sa Dios.',
          verse: 'Lucas 1:30',
          clue: 'sugo ng Diyos na ipinadala sa isang dalaga roon sa Nazaret' },
      ],
    },
    {
      id: 'qs-59', answer: 'SIMEON', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Lord, now You are letting Your servant depart in peace, according to Your word.',
          verse: 'Luke 2:29',
          clue: 'An old man in the temple who had been promised he would not die before this day.' },
        { type: 'quote', lang: 'fil', answer: 'SIMEON', flag: 'unverified', difficulty: 3,
          quote: 'Ngayo\'y papanawin mo, Panginoon, ang iyong alipin, Ayon sa iyong salita, sa kapayapaan',
          verse: 'Lucas 2:29',
          clue: 'matanda sa templo na pinangakuang hindi mamamatay bago dumating ang araw na ito' },
      ],
    },
    {
      id: 'qs-60', answer: 'THE PRODIGAL SON', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Father, I have sinned against heaven and before you, and am no longer worthy to be called your son.',
          verse: 'Luke 15:21',
          clue: 'The younger of two brothers, rehearsing a speech on the long road home.' },
        { type: 'quote', lang: 'fil', answer: 'ANG ALIBUGHANG ANAK', flag: 'unverified', difficulty: 2,
          quote: 'Ama, nagkasala ako laban sa langit, at sa iyong paningin: hindi na ako karapatdapat na tawaging anak mo.',
          verse: 'Lucas 15:21',
          clue: 'ang nakababata sa magkapatid, nag-eensayo ng sasabihin habang pauwi' },
      ],
    },
    {
      id: 'qs-61', answer: 'BARTIMAEUS', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Jesus, Son of David, have mercy on me!',
          verse: 'Mark 10:47',
          clue: 'A blind beggar on the Jericho road who refused to be shushed.' },
        { type: 'quote', lang: 'fil', answer: 'BARTIMEO', flag: 'unverified', difficulty: 3,
          quote: 'Jesus, ikaw na anak ni David, mahabag ka sa akin.',
          verse: 'Marcos 10:47',
          clue: 'bulag na pulubi sa daan ng Jerico na ayaw magpatahimik' },
      ],
    },
    {
      id: 'qs-62', answer: 'JESUS', difficulty: 1,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Neither do I condemn you; go and sin no more.',
          verse: 'John 8:11',
          clue: 'The only person in that crowd who actually had the right to throw a stone.' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Saul, Saul, why are you persecuting Me?',
          verse: 'Acts 9:4',
          clue: 'A voice from a blinding light on the road to Damascus' },
        { type: 'quote', flag: 'unverified', difficulty: 1,
          quote: 'Behold, I stand at the door and knock. If anyone hears My voice and opens the door, I will come in to him.',
          verse: 'Revelation 3:20',
          clue: 'Speaking to a lukewarm church in a letter dictated to John' },
        { type: 'quote', lang: 'fil', answer: 'JESUS', flag: 'unverified', difficulty: 2,
          quote: 'Ako man ay hindi rin hahatol sa iyo: humayo ka ng iyong lakad; mula ngayo\'y huwag ka nang magkasala.',
          verse: 'Juan 8:11',
          clue: 'siya lang sa buong pulutong ang may karapatang bumato' },
      ],
    },
    {
      id: 'qs-63', answer: 'PAUL', difficulty: 1,
      variants: [
        { type: 'quote', answer: 'SAUL', flag: 'unverified', difficulty: 1,
          quote: 'Who are You, Lord?',
          verse: 'Acts 9:5',
          clue: 'Blinded on a road, on his way to arrest believers' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Believe on the Lord Jesus Christ, and you will be saved, you and your household.',
          verse: 'Acts 16:31',
          clue: 'Answering a terrified man at midnight, still inside a prison' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Men of Athens, I perceive that in all things you are very religious.',
          verse: 'Acts 17:22',
          clue: 'A visitor preaching to philosophers beside an altar to an unknown god' },
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'I am a Jew from Tarsus, in Cilicia, a citizen of no mean city.',
          verse: 'Acts 21:39',
          clue: 'A prisoner explaining himself to a commander on the temple stairs' },
        { type: 'quote', lang: 'fil', answer: 'PABLO', flag: 'unverified', difficulty: 1,
          quote: 'Sino ka baga, Panginoon?',
          verse: 'Mga Gawa 9:5',
          clue: 'nabulag sa daan habang papunta siyang manghuli ng mga mananampalataya' },
      ],
    },
    {
      id: 'qs-64', answer: 'STEPHEN', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Lord, do not charge them with this sin.',
          verse: 'Acts 7:60',
          clue: 'The first believer to die for the faith, praying as the stones fell' },
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Look! I see the heavens opened and the Son of Man standing at the right hand of God!',
          verse: 'Acts 7:56',
          clue: 'One of the seven chosen to serve tables, on trial before the council' },
        { type: 'quote', lang: 'fil', answer: 'ESTEBAN', flag: 'unverified', difficulty: 2,
          quote: 'Panginoon, huwag mong iparatang sa kanila ang kasalanang ito.',
          verse: 'Mga Gawa 7:60',
          clue: 'unang namatay para sa pananampalataya, nananalangin habang binabato' },
      ],
    },
    {
      id: 'qs-65', answer: 'GAMALIEL', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'If it is of God, you cannot overthrow it—lest you even be found to fight against God.',
          verse: 'Acts 5:39',
          clue: 'A respected teacher of the law giving the council cool-headed advice' },
        { type: 'quote', lang: 'fil', answer: 'GAMALIEL', flag: 'unverified', difficulty: 3,
          quote: 'Datapuwa\'t kung sa Dios, ay hindi ninyo maiwawasak; baka pa kayo\'y mangasumpungan na nangakikihamok laban sa Dios.',
          verse: 'Mga Gawa 5:39',
          clue: 'iginagalang na guro ng kautusan, kalmadong payo ang ibinigay sa konseho' },
      ],
    },
    {
      id: 'qs-66', answer: 'THE PHILIPPIAN JAILER', difficulty: 2,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 2,
          quote: 'Sirs, what must I do to be saved?',
          verse: 'Acts 16:30',
          clue: 'An earthquake had just opened every door he was paid to keep shut' },
        { type: 'quote', lang: 'fil', answer: 'ANG BANTAY NG BILANGGUAN', flag: 'unverified', difficulty: 2,
          quote: 'Mga ginoo, ano ang kinakailangan kong gawin upang maligtas?',
          verse: 'Mga Gawa 16:30',
          clue: 'kabubukas lang ng lindol sa lahat ng pintuang trabaho niyang panatilihing sarado' },
      ],
    },
    {
      id: 'qs-67', answer: 'KING AGRIPPA', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'You almost persuade me to become a Christian.',
          verse: 'Acts 26:28',
          clue: 'A royal listener who came to hear a prisoner\'s defence and nearly changed his mind' },
        { type: 'quote', lang: 'fil', answer: 'HARING AGRIPA', flag: 'unverified', difficulty: 3,
          quote: 'Sa kakaunting paghikayat ay ibig mo akong maging Cristiano.',
          verse: 'Mga Gawa 26:28',
          clue: 'hari na dumalo para pakinggan ang depensa ng bilanggo, muntik nang mapapayag' },
      ],
    },
    {
      id: 'qs-68', answer: 'FESTUS', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Paul, you are beside yourself! Much learning is driving you mad!',
          verse: 'Acts 26:24',
          clue: 'The Roman governor who interrupted a prisoner\'s testimony with a shout' },
        { type: 'quote', lang: 'fil', answer: 'FESTO', flag: 'unverified', difficulty: 3,
          quote: 'Pablo, ikaw ay ulol; ang kalakhan ng dunong mo ay siyang sa iyo\'y nagpapaulol.',
          verse: 'Mga Gawa 26:24',
          clue: 'gobernador na Romano na sumigaw at pinutol ang testimonya ng bilanggo' },
      ],
    },
    {
      id: 'qs-69', answer: 'THE ETHIOPIAN EUNUCH', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'How can I, unless someone guides me?',
          verse: 'Acts 8:31',
          clue: 'A foreign official reading Isaiah aloud in his chariot on a desert road' },
        { type: 'quote', lang: 'fil', answer: 'ANG EUNUKO NA TAGA-ETIOPIA', flag: 'unverified', difficulty: 3,
          quote: 'Paanong magagawa ko, maliban nang may pumatnubay sa aking sinoman?',
          verse: 'Mga Gawa 8:31',
          clue: 'dayuhang opisyal na malakas na binabasa si Isaias sa karwahe sa disyertong daan' },
      ],
    },
    {
      id: 'qs-70', answer: 'ANANIAS OF DAMASCUS', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Lord, I have heard from many about this man, how much harm he has done to Your saints.',
          verse: 'Acts 9:13',
          clue: 'God told him to go heal the very man he was afraid of' },
        { type: 'quote', lang: 'fil', answer: 'ANANIAS NG DAMASCO', flag: 'unverified', difficulty: 3,
          quote: 'Panginoon, nabalitaan ko sa marami ang tungkol sa taong ito, kung gaano karaming kasamaan ang ginawa niya sa iyong mga banal sa Jerusalem',
          verse: 'Mga Gawa 9:13',
          clue: 'inutusan siya ng Diyos na puntahan at pagalingin ang mismong kinatatakutan niya' },
      ],
    },
    {
      id: 'qs-71', answer: 'DEMETRIUS', difficulty: 3,
      variants: [
        { type: 'quote', flag: 'unverified', difficulty: 3,
          quote: 'Men, you know that we have our prosperity by this trade.',
          verse: 'Acts 19:25',
          clue: 'His business making little silver shrines was collapsing as a new preaching spread' },
        { type: 'quote', lang: 'fil', answer: 'DEMETRIO', flag: 'unverified', difficulty: 3,
          quote: 'Mga Ginoo, talastas ninyo na nagsisiyaman tayo sa hanap-buhay na ito.',
          verse: 'Mga Gawa 19:25',
          clue: 'bumabagsak ang negosyo niyang maliliit na pilak na dambana dahil sa bagong turo' },
      ],
    },
  ],
};
