/*
 * Name the Place - the deck.
 *
 * GENERATED. Do not edit by hand: run
 *
 *     node tools/make-name-the-place.js
 *
 * after changing tools/places.json, which is the one hand-written thing behind
 * this game and the only place a coordinate should ever be corrected.
 *
 * THE GAME. A dot pulses on a map of the Bible world; the room shouts what
 * place it is. Four beats: the pin, the verse, a clue, the name.
 *
 * WHICH MAP. Each place is asked on the TIGHTEST map that contains it, which
 * the generator reads off the coordinates. Jerusalem is only ever asked
 * close-up, where it is a distinct dot; Babylon is only ever asked on the wide
 * map. There is deliberately no hand-written extent field: it would be a
 * second source of truth for something the coordinates already decide, and
 * the failure it invites is a map drawn with no pin visible on it.
 *
 * THE ACCURACY RULE. The location must not be seriously disputed. Mount Sinai,
 * Cana, Emmaus, Bethsaida and Ai are all left out on exactly that basis - see
 * tools/places.json for the list and the reasons.
 */
window.DECK = {
  id: 'name-the-place',
  title: 'Name the Place',
  idPrefix: 'np',   // shown on the projector, so it must never hint the answer
  shuffle: true,
  sessionSize: 15,
  languages: ['en', 'fil'],
  howToPlay: [
    'A dot appears on the map. The room says what place it is.',
    'Stuck? The next click gives the verse, then a clue.',
  ],
  // No credits and no versions: nothing here is quoted. The clues are ours
  // in both languages, and a coastline belongs to nobody.
  puzzles: [
    {
      id: 'np-01', answer: 'JERUSALEM', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [35.23, 31.78],
          verse: '2 Samuel 5:7',
          clue: 'David took its stronghold and called it his city' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'JERUSALEM',
          extent: 'holyland', at: [35.23, 31.78],
          verse: '2 Samuel 5:7',
          clue: 'sinakop ito ni David at tinawag na kaniyang lungsod' },
      ],
    },
    {
      id: 'np-02', answer: 'BETHLEHEM', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [35.2, 31.7],
          verse: 'Micah 5:2',
          clue: 'little among the thousands of Judah' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'BETLEHEM',
          extent: 'holyland', at: [35.2, 31.7],
          verse: 'Micah 5:2',
          clue: 'maliit sa mga angkan ng Juda' },
      ],
    },
    {
      id: 'np-03', answer: 'JERICHO', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [35.44, 31.87],
          verse: 'Joshua 6:20',
          clue: 'the walls fell down flat' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'JERICO',
          extent: 'holyland', at: [35.44, 31.87],
          verse: 'Joshua 6:20',
          clue: 'gumuho ang pader nito' },
      ],
    },
    {
      id: 'np-04', answer: 'NAZARETH', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [35.3, 32.7],
          verse: 'Luke 2:39',
          clue: 'can anything good come out of it?' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'NAZARET',
          extent: 'holyland', at: [35.3, 32.7],
          verse: 'Luke 2:39',
          clue: 'may mabuti bang manggagaling dito?' },
      ],
    },
    {
      id: 'np-05', answer: 'THE SEA OF GALILEE', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [35.58, 32.8],
          verse: 'Matthew 4:18',
          clue: 'four fishermen were called from this shore' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'DAGAT NG GALILEA',
          extent: 'holyland', at: [35.58, 32.8],
          verse: 'Matthew 4:18',
          clue: 'apat na mangingisda ang tinawag sa baybaying ito' },
      ],
    },
    {
      id: 'np-06', answer: 'THE DEAD SEA', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [35.45, 31.45],
          verse: 'Genesis 19:24',
          clue: 'two cities burned at its southern end' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'DAGAT NA PATAY',
          extent: 'holyland', at: [35.45, 31.45],
          verse: 'Genesis 19:24',
          clue: 'dalawang lungsod ang nasunog sa timog nito' },
      ],
    },
    {
      id: 'np-07', answer: 'JOPPA', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [34.75, 32.05],
          verse: 'Jonah 1:3',
          clue: 'he paid his fare and sailed the other way' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'JOPE',
          extent: 'holyland', at: [34.75, 32.05],
          verse: 'Jonah 1:3',
          clue: 'nagbayad siya ng pamasahe at naglayag paurong' },
      ],
    },
    {
      id: 'np-08', answer: 'MOUNT CARMEL', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'holyland', at: [35.05, 32.73],
          verse: '1 Kings 18:38',
          clue: 'fire fell on a soaked altar here' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'BUNDOK CARMELO',
          extent: 'holyland', at: [35.05, 32.73],
          verse: '1 Kings 18:38',
          clue: 'bumaba ang apoy sa basang altar dito' },
      ],
    },
    {
      id: 'np-09', answer: 'GOSHEN', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'bibleworld', at: [31.8, 30.8],
          verse: 'Genesis 47:27',
          clue: 'Jacob\'s family settled in the best of the land' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'GOSEN',
          extent: 'bibleworld', at: [31.8, 30.8],
          verse: 'Genesis 47:27',
          clue: 'dito tumira ang sambahayan ni Jacob' },
      ],
    },
    {
      id: 'np-10', answer: 'BABYLON', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'bibleworld', at: [44.42, 32.54],
          verse: 'Daniel 1:1',
          clue: 'Judah was carried here for seventy years' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'BABILONIA',
          extent: 'bibleworld', at: [44.42, 32.54],
          verse: 'Daniel 1:1',
          clue: 'dito dinala ang Juda sa loob ng pitumpung taon' },
      ],
    },
    {
      id: 'np-11', answer: 'NINEVEH', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'bibleworld', at: [43.15, 36.36],
          verse: 'Jonah 3:4',
          clue: 'forty days, and it shall be overthrown' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'NINIVE',
          extent: 'bibleworld', at: [43.15, 36.36],
          verse: 'Jonah 3:4',
          clue: 'apatnapung araw, at gugain ito' },
      ],
    },
    {
      id: 'np-12', answer: 'UR', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [46.1, 30.96],
          verse: 'Genesis 11:31',
          clue: 'Abraham\'s family left here for Canaan' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'UR',
          extent: 'bibleworld', at: [46.1, 30.96],
          verse: 'Genesis 11:31',
          clue: 'mula rito umalis ang angkan ni Abraham' },
      ],
    },
    {
      id: 'np-13', answer: 'HEBRON', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'holyland', at: [35.1, 31.53],
          verse: 'Genesis 23:19',
          clue: 'Abraham buried Sarah in a cave near here' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'HEBRON',
          extent: 'holyland', at: [35.1, 31.53],
          verse: 'Genesis 23:19',
          clue: 'inilibing ni Abraham si Sara sa isang yungib malapit dito' },
      ],
    },
    {
      id: 'np-14', answer: 'SHECHEM', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.28, 32.21],
          verse: 'Joshua 24:32',
          clue: 'the bones of Joseph were finally laid to rest here' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'SIQUEM',
          extent: 'holyland', at: [35.28, 32.21],
          verse: 'Joshua 24:32',
          clue: 'dito wakas na inilibing ang mga buto ni Jose' },
      ],
    },
    {
      id: 'np-15', answer: 'BETHEL', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.24, 31.93],
          verse: 'Genesis 28:19',
          clue: 'Jacob dreamed of a stairway to heaven here' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'BETHEL',
          extent: 'holyland', at: [35.24, 31.93],
          verse: 'Genesis 28:19',
          clue: 'dito nanaginip si Jacob ng hagdan patungo sa langit' },
      ],
    },
    {
      id: 'np-16', answer: 'SHILOH', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.29, 32.05],
          verse: '1 Samuel 3:10',
          clue: 'the tabernacle stood here, and a boy heard his name called in the night' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'SILO',
          extent: 'holyland', at: [35.29, 32.05],
          verse: '1 Samuel 3:10',
          clue: 'dito nakatayo ang tabernakulo, at narinig ng isang bata na tinawag ang kaniyang pangalan sa gabi' },
      ],
    },
    {
      id: 'np-17', answer: 'BEERSHEBA', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'holyland', at: [34.84, 31.25],
          verse: 'Genesis 21:31',
          clue: 'Abraham and a king swore an oath here over a well' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'BEERSEBA',
          extent: 'holyland', at: [34.84, 31.25],
          verse: 'Genesis 21:31',
          clue: 'dito nanumpa si Abraham at ang isang hari dahil sa isang balon' },
      ],
    },
    {
      id: 'np-18', answer: 'GAZA', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [34.47, 31.5],
          verse: 'Judges 16:21',
          clue: 'the blinded strong man was made to grind grain here' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'GAZA',
          extent: 'holyland', at: [34.47, 31.5],
          verse: 'Judges 16:21',
          clue: 'dito pinaggiling ng butil ang bulag na malakas na tao' },
      ],
    },
    {
      id: 'np-19', answer: 'ASHDOD', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [34.65, 31.8],
          verse: '1 Samuel 5:3',
          clue: 'an idol fell on its face before the captured ark' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'ASDOD',
          extent: 'holyland', at: [34.65, 31.8],
          verse: '1 Samuel 5:3',
          clue: 'bumagsak ang diyus-diyosan nang nakadapa sa harap ng nabihag na kaban' },
      ],
    },
    {
      id: 'np-20', answer: 'LACHISH', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [34.85, 31.565],
          verse: '2 Kings 18:14',
          clue: 'an Assyrian king besieged it while Hezekiah paid him tribute' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'LAQUIS',
          extent: 'holyland', at: [34.85, 31.565],
          verse: '2 Kings 18:14',
          clue: 'kinubkob ito ng isang haring taga-Asiria habang nagbabayad ng buwis si Ezequias' },
      ],
    },
    {
      id: 'np-21', answer: 'MEGIDDO', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.18, 32.585],
          verse: 'Revelation 16:16',
          clue: 'the last great gathering of armies is named for its hill' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'MEGIDO',
          extent: 'holyland', at: [35.18, 32.585],
          verse: 'Revelation 16:16',
          clue: 'ang huling malaking pagtitipon ng mga hukbo ay ipinangalan sa burol nito' },
      ],
    },
    {
      id: 'np-22', answer: 'SAMARIA', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.19, 32.28],
          verse: '1 Kings 16:24',
          clue: 'Omri bought a hill and built his capital on it' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'SAMARIA',
          extent: 'holyland', at: [35.19, 32.28],
          verse: '1 Kings 16:24',
          clue: 'binili ni Omri ang isang burol at doon itinayo ang kaniyang kabisera' },
      ],
    },
    {
      id: 'np-23', answer: 'DAN', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'holyland', at: [35.65, 33.25],
          verse: '1 Kings 12:29',
          clue: 'Jeroboam set up a golden calf at the northern edge of the land' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'DAN',
          extent: 'holyland', at: [35.65, 33.25],
          verse: '1 Kings 12:29',
          clue: 'nagtayo si Jeroboam ng gintong guya sa hilagang dulo ng lupain' },
      ],
    },
    {
      id: 'np-24', answer: 'TYRE', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'holyland', at: [35.2, 33.27],
          verse: '1 Kings 5:1',
          clue: 'its king Hiram sent cedar and craftsmen for the temple' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'TIRO',
          extent: 'holyland', at: [35.2, 33.27],
          verse: '1 Kings 5:1',
          clue: 'ipinadala ng hari nitong si Hiram ang sedro at mga manggagawa para sa templo' },
      ],
    },
    {
      id: 'np-25', answer: 'SIDON', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.37, 33.56],
          verse: '1 Kings 16:31',
          clue: 'Jezebel\'s father was king here' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'SIDON',
          extent: 'holyland', at: [35.37, 33.56],
          verse: '1 Kings 16:31',
          clue: 'hari rito ang ama ni Jezebel' },
      ],
    },
    {
      id: 'np-26', answer: 'MOUNT HERMON', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [35.86, 33.42],
          verse: 'Psalm 133:3',
          clue: 'the dew from this snowy height falls on the hills of Zion' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'BUNDOK HERMON',
          extent: 'holyland', at: [35.86, 33.42],
          verse: 'Psalm 133:3',
          clue: 'ang hamog mula sa maniyebeng taluktok na ito ay bumabagsak sa mga burol ng Sion' },
      ],
    },
    {
      id: 'np-27', answer: 'CAESAREA', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'holyland', at: [34.89, 32.5],
          verse: 'Acts 10:1',
          clue: 'a centurion named Cornelius sent from here for Peter' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'CESAREA',
          extent: 'holyland', at: [34.89, 32.5],
          verse: 'Acts 10:1',
          clue: 'mula rito ipinatawag ng senturyong si Cornelio si Pedro' },
      ],
    },
    {
      id: 'np-28', answer: 'DAMASCUS', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [36.29, 33.51],
          verse: 'Acts 9:3',
          clue: 'a light from heaven stopped Saul on the road to it' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'DAMASCO',
          extent: 'holyland', at: [36.29, 33.51],
          verse: 'Acts 9:3',
          clue: 'isang liwanag mula sa langit ang tumigil kay Saulo sa daan patungo rito' },
      ],
    },
    {
      id: 'np-29', answer: 'MOUNT TABOR', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.39, 32.69],
          verse: 'Judges 4:14',
          clue: 'Barak charged down from here with ten thousand men' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'BUNDOK TABOR',
          extent: 'holyland', at: [35.39, 32.69],
          verse: 'Judges 4:14',
          clue: 'mula rito bumaba si Barak kasama ang sampung libong lalaki' },
      ],
    },
    {
      id: 'np-30', answer: 'MOUNT GILBOA', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.41, 32.47],
          verse: '1 Samuel 31:1',
          clue: 'Saul and Jonathan fell in battle on its slopes' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'BUNDOK GILBOA',
          extent: 'holyland', at: [35.41, 32.47],
          verse: '1 Samuel 31:1',
          clue: 'sina Saul at Jonatan ay nabuwal sa labanan sa mga dalisdis nito' },
      ],
    },
    {
      id: 'np-31', answer: 'MOUNT NEBO', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'holyland', at: [35.725, 31.77],
          verse: 'Deuteronomy 34:1',
          clue: 'Moses looked over the promised land from here and never entered it' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'BUNDOK NEBO',
          extent: 'holyland', at: [35.725, 31.77],
          verse: 'Deuteronomy 34:1',
          clue: 'mula rito tinanaw ni Moises ang lupaing ipinangako, ngunit hindi siya nakapasok' },
      ],
    },
    {
      id: 'np-32', answer: 'DOTHAN', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.24, 32.41],
          verse: 'Genesis 37:17',
          clue: 'Joseph found his brothers here, and they sold him' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'DOTAN',
          extent: 'holyland', at: [35.24, 32.41],
          verse: 'Genesis 37:17',
          clue: 'dito natagpuan ni Jose ang kaniyang mga kapatid, at ipinagbili nila siya' },
      ],
    },
    {
      id: 'np-33', answer: 'CAPERNAUM', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'holyland', at: [35.575, 32.88],
          verse: 'Mark 2:1',
          clue: 'four friends lowered a paralysed man through the roof' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'CAPERNAUM',
          extent: 'holyland', at: [35.575, 32.88],
          verse: 'Mark 2:1',
          clue: 'ibinaba ng apat na magkakaibigan ang isang paralitiko mula sa bubong' },
      ],
    },
    {
      id: 'np-34', answer: 'RABBAH', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.93, 31.95],
          verse: '2 Samuel 11:17',
          clue: 'Uriah died at its wall in the fiercest fighting' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'RABA',
          extent: 'holyland', at: [35.93, 31.95],
          verse: '2 Samuel 11:17',
          clue: 'namatay si Urias sa pader nito sa pinakamabangis na labanan' },
      ],
    },
    {
      id: 'np-35', answer: 'BETH-SHAN', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'holyland', at: [35.5, 32.5],
          verse: '1 Samuel 31:10',
          clue: 'the Philistines hung the body of a king on its wall' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'BET-SAN',
          extent: 'holyland', at: [35.5, 32.5],
          verse: '1 Samuel 31:10',
          clue: 'isinabit ng mga Filisteo ang bangkay ng isang hari sa pader nito' },
      ],
    },
    {
      id: 'np-36', answer: 'ROME', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'bibleworld', at: [12.5, 41.9],
          verse: 'Acts 28:16',
          clue: 'Paul reached the capital of the empire in chains, and kept on preaching' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'ROMA',
          extent: 'bibleworld', at: [12.5, 41.9],
          verse: 'Acts 28:16',
          clue: 'narating ni Pablo ang kabisera ng imperyo na nakatanikala, at patuloy siyang nangaral' },
      ],
    },
    {
      id: 'np-37', answer: 'ATHENS', difficulty: 1,
      variants: [
        { type: 'map', difficulty: 1,
          extent: 'bibleworld', at: [23.73, 37.98],
          verse: 'Acts 17:23',
          clue: 'Paul found an altar here to an unknown god' },
        { type: 'map', difficulty: 1, lang: 'fil',
          answer: 'ATENAS',
          extent: 'bibleworld', at: [23.73, 37.98],
          verse: 'Acts 17:23',
          clue: 'nakita ni Pablo rito ang isang altar para sa isang diyos na hindi kilala' },
      ],
    },
    {
      id: 'np-38', answer: 'CORINTH', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'bibleworld', at: [22.93, 37.94],
          verse: 'Acts 18:3',
          clue: 'Paul made tents here with Aquila and Priscilla' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'CORINTO',
          extent: 'bibleworld', at: [22.93, 37.94],
          verse: 'Acts 18:3',
          clue: 'dito gumawa ng tolda si Pablo kasama sina Aquila at Priscila' },
      ],
    },
    {
      id: 'np-39', answer: 'EPHESUS', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'bibleworld', at: [27.34, 37.94],
          verse: 'Acts 19:28',
          clue: 'the silversmiths rioted here for their goddess Diana' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'EFESO',
          extent: 'bibleworld', at: [27.34, 37.94],
          verse: 'Acts 19:28',
          clue: 'nagkagulo rito ang mga panday-pilak dahil sa kanilang diyosang si Diana' },
      ],
    },
    {
      id: 'np-40', answer: 'PHILIPPI', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [24.29, 41.01],
          verse: 'Acts 16:26',
          clue: 'a midnight earthquake threw open the prison doors' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'FILIPOS',
          extent: 'bibleworld', at: [24.29, 41.01],
          verse: 'Acts 16:26',
          clue: 'binuksan ng lindol sa hatinggabi ang mga pintuan ng bilangguan' },
      ],
    },
    {
      id: 'np-41', answer: 'THESSALONICA', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [22.94, 40.64],
          verse: 'Acts 17:5',
          clue: 'jealous men set the city in an uproar over Paul and Silas' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'TESALONICA',
          extent: 'bibleworld', at: [22.94, 40.64],
          verse: 'Acts 17:5',
          clue: 'ginulo ng mga naiinggit na lalaki ang lungsod dahil kina Pablo at Silas' },
      ],
    },
    {
      id: 'np-42', answer: 'BEREA', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [22.2, 40.52],
          verse: 'Acts 17:11',
          clue: 'its people searched the scriptures daily to check what Paul said' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'BEREA',
          extent: 'bibleworld', at: [22.2, 40.52],
          verse: 'Acts 17:11',
          clue: 'araw-araw na sinaliksik ng mga taga rito ang Kasulatan upang tiyakin ang sinabi ni Pablo' },
      ],
    },
    {
      id: 'np-43', answer: 'TROAS', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [26.09, 39.75],
          verse: 'Acts 16:9',
          clue: 'Paul saw a vision of a man begging, come over and help us' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'TROAS',
          extent: 'bibleworld', at: [26.09, 39.75],
          verse: 'Acts 16:9',
          clue: 'nakita ni Pablo sa pangitain ang isang lalaking nagmamakaawa, tulungan mo kami' },
      ],
    },
    {
      id: 'np-44', answer: 'ANTIOCH IN SYRIA', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'bibleworld', at: [36.16, 36.2],
          verse: 'Acts 11:26',
          clue: 'the disciples were first called Christians here' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'ANTIOQUIA NG SIRIA',
          extent: 'bibleworld', at: [36.16, 36.2],
          verse: 'Acts 11:26',
          clue: 'dito unang tinawag na mga Cristiano ang mga alagad' },
      ],
    },
    {
      id: 'np-45', answer: 'ANTIOCH IN PISIDIA', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [31.19, 38.31],
          verse: 'Acts 13:44',
          clue: 'almost the whole city came to hear on the next sabbath, and Paul turned to the Gentiles' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'ANTIOQUIA NG PISIDIA',
          extent: 'bibleworld', at: [31.19, 38.31],
          verse: 'Acts 13:44',
          clue: 'halos buong lungsod ay dumating upang making sa sumunod na sabbath, at bumaling si Pablo sa mga Gentil' },
      ],
    },
    {
      id: 'np-46', answer: 'TARSUS', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [34.9, 36.92],
          verse: 'Acts 22:3',
          clue: 'the birthplace of Saul, a citizen of no mean city' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'TARSO',
          extent: 'bibleworld', at: [34.9, 36.92],
          verse: 'Acts 22:3',
          clue: 'ang lungsod na sinilangan ni Saulo, isang mamamayan ng lungsod na hindi hamak' },
      ],
    },
    {
      id: 'np-47', answer: 'LYSTRA', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [32.45, 37.58],
          verse: 'Acts 14:19',
          clue: 'stoned and dragged out of the city, Paul got up and went straight back in' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'LISTRA',
          extent: 'bibleworld', at: [32.45, 37.58],
          verse: 'Acts 14:19',
          clue: 'binato at kinaladkad palabas ng lungsod, tumayo si Pablo at bumalik sa loob' },
      ],
    },
    {
      id: 'np-48', answer: 'PATMOS', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [26.55, 37.31],
          verse: 'Revelation 1:9',
          clue: 'John was exiled to this island and saw the visions' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'PATMOS',
          extent: 'bibleworld', at: [26.55, 37.31],
          verse: 'Revelation 1:9',
          clue: 'ipinatapon si Juan sa pulong ito at nakita niya ang mga pangitain' },
      ],
    },
    {
      id: 'np-49', answer: 'MALTA', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'bibleworld', at: [14.5, 35.9],
          verse: 'Acts 28:5',
          clue: 'after the shipwreck, Paul shook a viper off into the fire' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'MALTA',
          extent: 'bibleworld', at: [14.5, 35.9],
          verse: 'Acts 28:5',
          clue: 'pagkatapos ng pagkawasak ng barko, iwinaksi ni Pablo sa apoy ang ulupong' },
      ],
    },
    {
      id: 'np-50', answer: 'PAPHOS', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [32.41, 34.75],
          verse: 'Acts 13:11',
          clue: 'a sorcerer was struck blind here and the governor believed' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'PAFOS',
          extent: 'bibleworld', at: [32.41, 34.75],
          verse: 'Acts 13:11',
          clue: 'dito nabulag ang isang manggagaway at sumampalataya ang gobernador' },
      ],
    },
    {
      id: 'np-51', answer: 'MEMPHIS', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'bibleworld', at: [31.25, 29.85],
          verse: 'Hosea 9:6',
          clue: 'an old capital beside the Nile, called Noph by the prophets' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'MENFIS',
          extent: 'bibleworld', at: [31.25, 29.85],
          verse: 'Hosea 9:6',
          clue: 'sinaunang kabisera sa tabi ng Nilo na tinawag na Nof ng mga propeta' },
      ],
    },
    {
      id: 'np-52', answer: 'HARAN', difficulty: 3,
      variants: [
        { type: 'map', difficulty: 3,
          extent: 'bibleworld', at: [39.03, 36.86],
          verse: 'Genesis 12:4',
          clue: 'Abram waited here until his father died, then obeyed the call to go' },
        { type: 'map', difficulty: 3, lang: 'fil',
          answer: 'HARAN',
          extent: 'bibleworld', at: [39.03, 36.86],
          verse: 'Genesis 12:4',
          clue: 'naghintay dito si Abram hanggang mamatay ang kaniyang ama, saka sumunod sa tawag na humayo' },
      ],
    },
    {
      id: 'np-53', answer: 'MOUNT ARARAT', difficulty: 2,
      variants: [
        { type: 'map', difficulty: 2,
          extent: 'bibleworld', at: [44.3, 39.7],
          verse: 'Genesis 8:4',
          clue: 'the ark came to rest somewhere in the mountains here' },
        { type: 'map', difficulty: 2, lang: 'fil',
          answer: 'BUNDOK NG ARARAT',
          extent: 'bibleworld', at: [44.3, 39.7],
          verse: 'Genesis 8:4',
          clue: 'sa mga bundok dito nagpahinga ang arka' },
      ],
    },
  ],
};
