/*
 * Hot Potato - the deck.
 *
 * HAND-WRITTEN, unlike What Came First? and Higher or Lower, which are
 * generated because their content is facts that cannot be proofread by eye.
 * These cards are writing. There is no source to derive them from.
 *
 * TWO KINDS OF CARD, and the difference is where the text lives:
 *
 *   a TASK       something to DO. The text goes in `answer`, because a task IS
 *                its own identity - and validate.js already rejects two
 *                puzzles sharing an answer, so that buys duplicate-card
 *                detection for free. No `prompt`.
 *   a KNOWLEDGE  a question in `prompt`, the answer in `answer`, the reference
 *                in `ref`. It gets a fourth screen the task cards do not have.
 *
 * THE RULE FOR A TASK CARD: it must be performable by whoever is holding the
 * mic, with nothing but a Bible and the people next to them. No props, no
 * phones, no printing. A card that cannot be done is only discovered when it
 * comes up, in front of everyone, which is the worst place to find out.
 *
 * English only for now. `languages` carries the slot, so Tagalog is a deck
 * edit later with no code change - the same as every other game here.
 */
window.DECK = {
  id: 'hot-potato',
  title: 'Hot Potato',
  idPrefix: 'hp',   // shown on the projector, so it must never hint the answer
  shuffle: true,
  sessionSize: 12,
  languages: ['en'],
  // The range the stop is drawn from, in seconds - NOT a fixed duration. Every
  // round draws a fresh number inside it, so nobody can count. Widen it if the
  // room starts sensing the floor.
  musicSeconds: [6, 20],
  howToPlay: [
    'Pass something round while the music plays.',
    'When it stops, whoever is holding it does what the screen says.',
  ],
  puzzles: [
    // Tasks: something to do. Text in `answer`, no prompt.
    { id: 'hp-01', answer: 'Recite any two verses from memory',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-02', answer: 'Say John 3:16 out loud, and let the room join in',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-03', answer: 'Say the Lord’s Prayer together, with the room joining in',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-04', answer: 'Read Psalm 117 aloud with the person next to you, one verse each',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-05', answer: 'Say the verse that means the most to you, then say in one sentence why',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-06', answer: 'Find Proverbs 3:5-6 in your Bible and read it aloud',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-07', answer: 'Find the shortest verse in the Bible, John 11:35, and read it aloud',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-08', answer: 'Sing one verse of a hymn with the person on your left',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-09', answer: 'Sing the chorus of a worship song with the person on your right',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-10', answer: 'Ask the room to call out a song, then sing its chorus together',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-11', answer: 'With a neighbour, hum a few notes of a song and let the room guess it for up to 30 seconds, or until they get it',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-12', answer: 'Name five of the twelve disciples',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-13', answer: 'Name five books of the New Testament',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-14', answer: 'Name five people from the Old Testament',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-15', answer: 'Name four of the ten plagues of Egypt, and ask the room to help if you get stuck',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-16', answer: 'Name three women of the Bible',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-17', answer: 'Name four miracles that Jesus did',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-18', answer: 'Name three stories that Jesus told',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-19', answer: 'Name four animals that appear in the Bible',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-20', answer: 'Name three of the nine fruits of the Spirit',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-21', answer: 'Say in one sentence what grace means',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-22', answer: 'Say in one sentence why we pray',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-23', answer: 'Say in one sentence what the good news is',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-24', answer: 'Finish this sentence out loud: “I know God is faithful because…”',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-25', answer: 'Say in one sentence what you would tell a friend who asked what church is for',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-26', answer: 'Say a short prayer out loud for a friend or family member, without naming them',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-27', answer: 'Thank God out loud for three things from this week',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-28', answer: 'Say a one-sentence prayer of thanks for this place and the people in it',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-29', answer: 'Pray one sentence for someone who is having a hard week, without naming them',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-30', answer: 'Pray one sentence for the leaders of this group',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-31', answer: 'With the people next to you, freeze in a pose that shows a Bible scene, and let the room guess for up to 30 seconds',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-32', answer: 'With a neighbour, act out a Bible story without words, and let the room guess for up to 30 seconds',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-33', answer: 'With your hands only, show one thing a shepherd does for his sheep, and let the room guess it for up to 30 seconds, or until they get it',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-34', answer: 'Ask the room for their favourite Bible story, and listen to three answers',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-35', answer: 'Ask the room which Bible character they would most like to meet, and hear two answers',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-36', answer: 'Ask the room for one thing they are thankful for, and hear three answers',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-37', answer: 'Ask the room for a verse that helped them in a hard time, and hear two answers',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-38', answer: 'Say out loud one thing you are glad about in this youth group',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-39', answer: 'With the person next to you, find a verse about love and read it to each other',
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-40', answer: 'Finish this sentence out loud: \u201CSomething I have learned about God lately is\u2026\u201D',
      variants: [{ type: 'card', kind: 'task' }] },
    // Knowledge: the answer is STATED in the verse, never inferred, and reads
    // the same in the KJV and WEB, and where translations differ both are given
    // (Melita/Malta). Verified against fetched KJV and WEB text, cross-checked in
    // ASV and YLT. The NIV was NOT consulted (copyrighted, not in the source used).
    { id: 'hp-41', answer: 'Belshazzar', ref: 'Daniel 5:1-5',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which king saw a hand writing on the wall?' }] },
    { id: 'hp-42', answer: 'Melita (Malta)', ref: 'Acts 27:41-28:3',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'On which island was Paul shipwrecked?' }] },
    { id: 'hp-43', answer: 'Goliath', ref: '1 Samuel 17:4-10',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which Philistine champion from Gath challenged the armies of Israel?' }] },
    { id: 'hp-44', answer: 'Daniel', ref: 'Daniel 6:16',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Who was thrown into the lions’ den?' }] },
    { id: 'hp-45', answer: 'Five', ref: 'John 6:9',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'How many barley loaves did the boy have?' }] },
    { id: 'hp-46', answer: 'Peter', ref: 'Matthew 26:33-34',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which disciple did Jesus say would deny him three times before the rooster crowed?' }] },
    { id: 'hp-47', answer: 'Zacchaeus (Zaccheus)', ref: 'Luke 19:2-4',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which tax collector climbed a tree to see Jesus?' }] },
    { id: 'hp-48', answer: 'Jonah', ref: 'Jonah 1:17',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which prophet was swallowed by a fish?' }] },
    { id: 'hp-49', answer: 'Jericho', ref: 'Hebrews 11:30',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which city’s walls fell after the Israelites marched around them for seven days?' }] },
    { id: 'hp-50', answer: 'Bethlehem', ref: 'Matthew 2:1',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'In which town was Jesus born?' }] },
    { id: 'hp-51', answer: 'Wine', ref: 'John 2:1-11',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'At the wedding in Cana, what did Jesus turn the water into?' }] },
    { id: 'hp-52', answer: 'Aaron', ref: 'Exodus 4:14-16; 4:30',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which brother of Moses spoke to the people for him?' }] },
    { id: 'hp-53', answer: 'Sarah', ref: 'Genesis 17:15',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'God changed Abraham’s wife’s name from Sarai to what?' }] },
    { id: 'hp-54', answer: 'Elijah', ref: '2 Kings 2:11',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which prophet went up to heaven in a whirlwind?' }] },
    { id: 'hp-55', answer: 'Mount Sinai (Horeb)', ref: 'Exodus 31:18',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'On which mountain did the Lord give Moses two tablets of stone?' }] },
    { id: 'hp-56', answer: 'Abednego (Abed-nego)', ref: 'Daniel 3:20-23',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Shadrach, Meshach and who else were thrown into the blazing furnace?' }] },
    { id: 'hp-57', answer: 'A dove', ref: 'Matthew 3:16',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'At Jesus’ baptism, the Spirit of God came down like what?' }] },
    { id: 'hp-58', answer: 'Thomas', ref: 'John 20:24-25',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which disciple said he would not believe unless he saw the nail marks in Jesus’ hands?' }] },
    { id: 'hp-59', answer: 'Stephen', ref: 'Acts 7:59',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Who prayed “Lord Jesus, receive my spirit” while being stoned?' }] },
    { id: 'hp-60', answer: 'Shepherd', ref: 'Psalm 23:1',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Complete the verse: “The Lord is my ___”' }] },
    { id: 'hp-61', answer: 'World', ref: 'John 3:16',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Complete the verse: “For God so loved the ___”' }] },
    { id: 'hp-62', answer: 'Forty days and forty nights', ref: 'Genesis 7:12',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'How long did the rain fall on the earth in the flood?' }] },
    { id: 'hp-63', answer: 'Gethsemane', ref: 'Matthew 26:36-50',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'What was the name of the place where Jesus went to pray before he was arrested?' }] },
    { id: 'hp-64', answer: 'Hannah', ref: '1 Samuel 1:20',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which woman gave birth to a son and named him Samuel?' }] },
    { id: 'hp-65', answer: 'The Jordan', ref: 'Mark 1:9',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'In which river was Jesus baptized by John?' }] },
    { id: 'hp-66', answer: 'Tentmaking', ref: 'Acts 18:1-3',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'What trade did Paul share with Aquila and Priscilla?' }] },
    { id: 'hp-67', answer: 'Joseph', ref: 'Genesis 35:10; 37:1-3',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which of Jacob’s sons did he love more than the others, making him a special robe?' }] },
    { id: 'hp-68', answer: 'Peace', ref: 'Galatians 5:22',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Complete the list: “The fruit of the Spirit is love, joy, ___”' }] },
    { id: 'hp-69', answer: 'David', ref: '1 Samuel 16:11-13',
      variants: [{ type: 'card', kind: 'knowledge',
                   prompt: 'Which youngest son of Jesse did Samuel anoint with oil?' }] },
  ],
};
