/*
 * Hot Potato - the deck.
 *
 * HAND-WRITTEN, unlike What Came First? and Higher or Lower, which are
 * generated because their content is facts that cannot be proofread by eye.
 * These cards are writing. There is no source to derive them from.
 *
 * TWO KINDS OF CARD, and no third. A TASK is something the holder DOES, and its
 * text goes in `answer` because a task IS its own identity - validate.js
 * already rejects two puzzles sharing an answer, so that buys duplicate-card
 * detection for free. No `prompt`, no `ref`.
 *
 * A LIST card is a constrained-recall challenge - "Name a king of Israel or
 * Judah whose name starts with J" - in `prompt`, followed by a screen showing
 * the valid answers, in `answer`, so the room can settle "does that count?".
 * It is NOT trivia and must not turn into it: the challenge is recalling one
 * under pressure, standing up, and it stays fresh because a different person
 * holds the potato each time. The list is a referee, not a lesson.
 *
 * KNOWLEDGE cards stay out. A question is spent the moment the room hears the
 * answer, which is what made the deck run dry; the scripture questions that
 * used to be here are kept, verified, in tools/bible-questions.json. The
 * engine's knowledge-card path still exists in core/views.js for a deck that
 * wants it; tests/hot-potato.test.js is what stops one arriving by accident.
 *
 * THE LISTS ARE FACTS, so every one was checked against fetched KJV and WEB
 * text (api.getbible.net/v2), not written from memory; a name that could not
 * be found in the text was left out. A list that is missing a valid answer is
 * a small unfairness, so lists drawn from an open set (women, places, animals,
 * people who met Jesus, prophets) end "and others", and only the closed sets
 * (kings, books, the twelve, judges) claim to be complete. Where the KJV and
 * the WEB spell a name differently, or scholars differ, the answer carries both
 * (Jehoram (Joram), Zacchaeus (Zaccheus), Mars' Hill (Areopagus)).
 *
 * THE RULE FOR A TASK CARD: it must be performable by whoever is holding the
 * mic, with nothing but a Bible and the people next to them. No props, no
 * phones, no printing. A card that cannot be done is only discovered when it
 * comes up, in front of everyone, which is the worst place to find out.
 *
 * English only for now. `languages` carries the slot, so Tagalog is a deck
 * edit later with no code change - the same as every other game here.
 */
window.DECK = {
  id: 'hot-potato',
  title: 'Hot Potato',
  idPrefix: 'hp',   // shown on the projector, so it must never hint the answer
  shuffle: true,
  // This deck is NOT consumed by being played. Every card is a performance or
  // a recall challenge, so the same card is a different thing in a different
  // person's hands. Remembering what has been asked would only empty it: after
  // 162 cards the game would say it was finished and stop, which is the one
  // thing a game that never runs out must not do.
  remembers: false,
  sessionSize: 12,
  languages: ['en'],
  // The range the stop is drawn from, in seconds - NOT a fixed duration. Every
  // round draws a fresh number inside it, so nobody can count. Widen it if the
  // room starts sensing the floor.
  musicSeconds: [6, 20],
  howToPlay: [
    'Pass something round while the music plays.',
    'When it stops, whoever is holding it does what the screen says.',
  ],
  puzzles: [
    // A task is something the holder does: text in `answer`, no prompt and no
    // ref. A list card (hp-2xx, below) is a challenge in `prompt` with the valid
    // answers in `answer`. Either way the challenge is doing it from memory,
    // standing up, in front of everyone, which is fresh each time a different
    // person holds the potato.
    // difficulty: 1 anyone can do it on the spot, 2 takes some thought or
    // memory, 3 real recall. The order ramps 1 -> 2 -> 3 within a round, so the
    // Ten Commandments never opens it. The scripture questions that used to be
    // here are kept, verified, in tools/bible-questions.json.
    { id: 'hp-001', answer: 'Recite any two verses from memory', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-002', answer: 'Say John 3:16 out loud, and let the room join in', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-003', difficulty: 1, ref: 'Matthew 6:9-13',
      answer: 'After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name. Thy kingdom come. Thy will be done in earth, as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we forgive our debtors. And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Say the Lord’s Prayer together, with the room joining in' }] },
    { id: 'hp-004', answer: 'Read Psalm 117 aloud with the person next to you, one verse each', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-005', answer: 'Say the verse that means the most to you, then say in one sentence why', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-006', answer: 'Find Proverbs 3:5-6 in your Bible and read it aloud', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-007', answer: 'Find the shortest verse in the Bible, John 11:35, and read it aloud', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-008', answer: 'Sing one verse of a hymn with the person on your left', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-009', answer: 'Sing the chorus of a worship song with the person on your right', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-010', answer: 'Name a song you want everyone to sing, then start it off', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-011', answer: 'With a neighbour, hum a few notes of a song and let the room guess it for up to 30 seconds, or until they get it', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-012', difficulty: 2, ref: 'Matthew 10:2-4',
      answer: 'Simon Peter, Andrew, James, John, Philip, Bartholomew, Thomas, Matthew, James son of Alphaeus, Thaddaeus, Simon the Canaanite, Judas Iscariot',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name five of the twelve disciples' }] },
    { id: 'hp-013', difficulty: 1,
      answer: 'Matthew, Mark, Luke, John, Acts, Romans, 1 and 2 Corinthians, Galatians, Ephesians, Philippians, Colossians, 1 and 2 Thessalonians, 1 and 2 Timothy, Titus, Philemon, Hebrews, James, 1 and 2 Peter, 1-3 John, Jude, Revelation',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name five books of the New Testament' }] },
    { id: 'hp-014', difficulty: 1, ref: 'Others count too',
      answer: 'Adam, Noah, Abraham, Sarah, Moses, Joshua, Ruth, David, Elijah, Daniel, Esther',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name five people from the Old Testament' }] },
    { id: 'hp-015', difficulty: 2, ref: 'Exodus 7-12',
      answer: 'Blood, frogs, lice, flies, livestock, boils, hail, locusts, darkness, the firstborn',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name four of the ten plagues of Egypt, and ask the room to help if you get stuck' }] },
    { id: 'hp-016', difficulty: 2, ref: 'Others count too',
      answer: 'Eve, Sarah, Rebekah, Rachel, Miriam, Deborah, Ruth, Hannah, Abigail, Esther, Mary',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name three women of the Bible' }] },
    { id: 'hp-017', difficulty: 2, ref: 'Others count too',
      answer: 'Water into wine, calming the storm, feeding the five thousand, walking on water, healing the blind, raising Lazarus',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name four miracles that Jesus did' }] },
    { id: 'hp-018', difficulty: 1, ref: 'Others count too',
      answer: 'The good Samaritan, the prodigal son, the sower, the lost sheep, the talents, the ten virgins, the rich fool',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name three stories that Jesus told' }] },
    { id: 'hp-019', difficulty: 1, ref: 'Others count too',
      answer: 'Lion, lamb, serpent, dove, donkey, raven, whale or great fish, camel, eagle, locust',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name four animals that appear in the Bible' }] },
    { id: 'hp-020', difficulty: 2, ref: 'Galatians 5:22-23',
      answer: 'Love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name three of the nine fruits of the Spirit' }] },
    { id: 'hp-021', answer: 'Say in one sentence what grace means', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-022', answer: 'Say in one sentence why we pray', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-023', answer: 'Say in one sentence what the good news is', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-024', answer: 'Finish this sentence out loud: “I know God is faithful because…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-025', answer: 'Say in one sentence what you would tell a friend who asked what church is for', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-026', answer: 'Say a short prayer out loud for a friend or family member, without naming them', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-027', answer: 'Thank God out loud for three things from this week', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-028', answer: 'Say a one-sentence prayer of thanks for this place and the people in it', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-029', answer: 'Pray one sentence for someone who is having a hard week, without naming them', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-030', answer: 'Pray one sentence for the leaders of this group', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-031', answer: 'With the people next to you, freeze in a pose that shows a Bible scene, and let the room guess for up to 30 seconds', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-032', answer: 'With a neighbour, act out a Bible story without words, and let the room guess for up to 30 seconds', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-033', answer: 'With your hands only, show one thing a shepherd does for his sheep, and let the room guess it for up to 30 seconds, or until they get it', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-034', answer: 'Tell everyone your favourite Bible story in one sentence', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-035', answer: 'Say which Bible character you would most like to meet, and why', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-036', answer: 'Say one thing you are thankful for today', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-037', answer: 'Give two verses that have helped you in a hard time', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-038', answer: 'Say out loud one thing you are glad about in this youth group', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-039', answer: 'With the person next to you, find a verse about love and read it to each other', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-040', answer: 'Finish this sentence out loud: “Something I have learned about God lately is…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-041', answer: 'Say a verse you learned as a child, as best you remember it', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-042', answer: 'Open your Bible to a Psalm you like and read two verses from it aloud', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-043', answer: 'Say a verse you would give a friend who is scared', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-044', answer: 'Say a verse that reminds you God is with you', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-045', answer: 'Say one thing that made you smile this week', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-046', answer: 'Say one thing you are looking forward to', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-047', answer: 'Say one thing you enjoy doing when nobody is making you', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-048', answer: 'Say what you would be doing right now if you were not here', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-049', answer: 'Say one thing you would ask God if you could sit with him for five minutes', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-050', answer: 'Say one way you have seen God help someone lately', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-051', answer: 'Say the funniest thing you have seen happen in church, without naming anyone', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-052', answer: 'Say which Bible story would make the best film, and why', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-053', answer: 'Say one thing you hope heaven will be like', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-054', answer: 'Say one sentence you would tell someone who had never heard of Jesus', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-055', answer: 'Finish this sentence out loud: “I feel closest to God when…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-056', answer: 'Finish this sentence out loud: “A church should be a place where…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-057', answer: 'Finish this sentence out loud: “The best advice I ever heard was…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-058', answer: 'Finish this sentence out loud: “One thing Jesus did that surprises me is…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-059', answer: 'Finish this sentence out loud: “If I could say one thing to my younger self, it would be…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-060', answer: 'Say a one-sentence prayer for the week ahead', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-061', answer: 'Pray one sentence of thanks for the food you ate today', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-062', answer: 'Pray one sentence for the place where you spend most of your week', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-063', answer: 'Sing one line of a song that makes you feel peaceful', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-064', answer: 'Say one line from a worship song that you like, and why you like it', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-065', answer: 'With a neighbour, read Psalm 136:1-4 aloud one verse each, and let the room join in on the line that repeats', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-066', answer: 'With a neighbour, agree on one verse and read it together out loud', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-067', answer: 'Name three things in creation that you are thankful God made', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-068', answer: 'Say three words that describe what God is like', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-069', answer: 'Name three things you could do this week to show kindness', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-070', answer: 'Stand up, stretch, and thank God for one thing your body can do', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-071', answer: 'Give the room one sentence of encouragement for the week ahead', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-072', difficulty: 3, ref: 'Psalm 23',
      answer: 'The Lord is my shepherd; I shall not want. He maketh me to lie down in green pastures: he leadeth me beside the still waters. He restoreth my soul: he leadeth me in the paths of righteousness for his name’s sake. Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me. Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over. Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the Lord for ever.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite Psalm 23 from memory, and the room may help if you stall' }] },
    { id: 'hp-073', difficulty: 3, ref: 'Matthew 5:3-10',
      answer: 'Blessed are the poor in spirit: for theirs is the kingdom of heaven. Blessed are they that mourn: for they shall be comforted. Blessed are the meek: for they shall inherit the earth. Blessed are they which do hunger and thirst after righteousness: for they shall be filled. Blessed are the merciful: for they shall obtain mercy. Blessed are the pure in heart: for they shall see God. Blessed are the peacemakers: for they shall be called the children of God. Blessed are they which are persecuted for righteousness’ sake: for theirs is the kingdom of heaven.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite the Beatitudes, Matthew 5:3-10, from memory, as far as you get' }] },
    { id: 'hp-074', difficulty: 3, ref: 'Galatians 5:22-23',
      answer: 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name the nine fruits of the Spirit from Galatians 5:22-23, in any translation' }] },
    { id: 'hp-075', difficulty: 3, ref: 'Exodus 20:3-17',
      answer: 'Thou shalt have no other gods before me; Thou shalt not make unto thee any graven image; Thou shalt not take the name of the LORD thy God in vain; Remember the sabbath day, to keep it holy; Honour thy father and thy mother; Thou shalt not kill; Thou shalt not commit adultery; Thou shalt not steal; Thou shalt not bear false witness; Thou shalt not covet',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Say as many of the Ten Commandments as you can in 30 seconds' }] },
    { id: 'hp-076', difficulty: 3,
      answer: 'Matthew, Mark, Luke, John, Acts, Romans, 1 and 2 Corinthians, Galatians, Ephesians, Philippians, Colossians, 1 and 2 Thessalonians, 1 and 2 Timothy, Titus, Philemon, Hebrews, James, 1 and 2 Peter, 1-3 John, Jude, Revelation',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Say the books of the New Testament in order, as far as you get in 30 seconds' }] },
    { id: 'hp-077', answer: 'Say five books of the Old Testament in the order they appear in the Bible', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-078', difficulty: 3, ref: 'Matthew 10:2-4',
      answer: 'Simon Peter, Andrew, James, John, Philip, Bartholomew, Thomas, Matthew, James son of Alphaeus, Thaddaeus, Simon the Canaanite, Judas Iscariot',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name the twelve disciples, and the room may help if you stall' }] },
    { id: 'hp-079', answer: 'Ask the room for a letter other than Q, X or Z, then say a verse that begins with that letter', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-080', answer: 'Say two verses from the same chapter of the Bible, and name the chapter', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-081', answer: 'Say a verse from memory, then tell the room which book and chapter it is in', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-082', difficulty: 3, ref: '1 Corinthians 13:4-7',
      answer: 'Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite 1 Corinthians 13:4-7 from memory, as far as you get' }] },
    { id: 'hp-083', difficulty: 3, ref: 'Isaiah 40:31',
      answer: 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite Isaiah 40:31 from memory' }] },
    { id: 'hp-084', difficulty: 3, ref: 'Matthew 28:19-20',
      answer: 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost: Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite the Great Commission, Matthew 28:19-20, from memory, as far as you get' }] },
    { id: 'hp-085', difficulty: 3, ref: 'Numbers 6:24-26',
      answer: 'The Lord bless thee, and keep thee: The Lord make his face shine upon thee, and be gracious unto thee: The Lord lift up his countenance upon thee, and give thee peace.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite the blessing in Numbers 6:24-26 from memory' }] },
    { id: 'hp-086', difficulty: 3, ref: 'Ephesians 6:14-17',
      answer: 'Stand therefore, having your loins girt about with truth, and having on the breastplate of righteousness; And your feet shod with the preparation of the gospel of peace; Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked. And take the helmet of salvation, and the sword of the Spirit, which is the word of God:',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name six pieces of the armour of God from Ephesians 6' }] },
    { id: 'hp-087', difficulty: 3, ref: 'Genesis 1',
      answer: 'Light; the firmament; dry land and plants; sun, moon and stars; fish and birds; animals and people',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name what God made on each of the first six days of creation, in order' }] },
    { id: 'hp-088', difficulty: 3, ref: 'John 6, 8, 10, 11, 14, 15',
      answer: 'The bread of life; the light of the world; the door; the good shepherd; the resurrection and the life; the way, the truth and the life; the true vine',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name four of the “I am” sayings of Jesus in John’s Gospel' }] },
    { id: 'hp-089', difficulty: 3,
      answer: 'Hosea, Joel, Amos, Obadiah, Jonah, Micah, Nahum, Habakkuk, Zephaniah, Haggai, Zechariah, Malachi',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name five of the twelve minor prophets' }] },
    { id: 'hp-090', difficulty: 3, ref: 'Psalm 1:1-3',
      answer: 'Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful. But his delight is in the law of the Lord; and in his law doth he meditate day and night. And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite Psalm 1:1-3 from memory, as far as you get' }] },
    { id: 'hp-091', difficulty: 3, ref: 'John 1:1-3',
      answer: 'In the beginning was the Word, and the Word was with God, and the Word was God. The same was in the beginning with God. All things were made by him; and without him was not any thing made that was made.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite John 1:1-3 from memory' }] },
    { id: 'hp-092', difficulty: 2, ref: 'Matthew 6:9-13',
      answer: 'After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name. Thy kingdom come. Thy will be done in earth, as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we forgive our debtors. And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Say the Lord’s Prayer from memory on your own, and the room joins in only if you stall' }] },
    { id: 'hp-093', difficulty: 2, ref: 'Romans 8:28',
      answer: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite Romans 8:28 from memory' }] },
    { id: 'hp-094', difficulty: 2, ref: 'Jeremiah 29:11',
      answer: 'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite Jeremiah 29:11 from memory' }] },
    { id: 'hp-095', difficulty: 2, ref: 'Joshua 1:9',
      answer: 'Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite Joshua 1:9 from memory' }] },
    { id: 'hp-096', difficulty: 2, ref: 'Proverbs 3:5-6',
      answer: 'Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Recite Proverbs 3:5-6 from memory' }] },
    { id: 'hp-097', difficulty: 2,
      answer: 'Genesis, Exodus, Leviticus, Numbers, Deuteronomy',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Say the first five books of the Bible in order' }] },
    { id: 'hp-098', difficulty: 2,
      answer: 'Matthew, Mark, Luke, John',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name the four Gospels in order, and one thing each is known for' }] },
    { id: 'hp-099', difficulty: 2, ref: 'Others count too',
      answer: 'Saul, David, Solomon, Jeroboam, Ahab, Jehu, Hezekiah, Josiah, Uzziah, Jehoshaphat',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name five kings of Israel or Judah' }] },
    { id: 'hp-100', difficulty: 1, ref: 'Genesis 35:23-26',
      answer: 'Reuben, Simeon, Levi, Judah, Dan, Naphtali, Gad, Asher, Issachar, Zebulun, Joseph, Benjamin',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two or three of the sons of Jacob' }] },
    { id: 'hp-101', difficulty: 2, ref: 'Genesis 35:23-26',
      answer: 'Reuben, Simeon, Levi, Judah, Dan, Naphtali, Gad, Asher, Issachar, Zebulun, Joseph, Benjamin',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name five of the twelve sons of Jacob' }] },
    { id: 'hp-102', difficulty: 3, ref: 'Genesis 35:23-26',
      answer: 'Reuben, Simeon, Levi, Judah, Dan, Naphtali, Gad, Asher, Issachar, Zebulun, Joseph, Benjamin',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name as many of the sons of Jacob as you can in 30 seconds' }] },
    { id: 'hp-103', difficulty: 1, ref: 'Judges; 1 Samuel',
      answer: 'Othniel, Ehud, Shamgar, Deborah, Gideon, Tola, Jair, Jephthah, Ibzan, Elon, Abdon, Samson, Eli, Samuel',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two judges of Israel' }] },
    { id: 'hp-104', difficulty: 2, ref: 'Judges; 1 Samuel',
      answer: 'Othniel, Ehud, Shamgar, Deborah, Gideon, Tola, Jair, Jephthah, Ibzan, Elon, Abdon, Samson, Eli, Samuel',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name four judges of Israel' }] },
    { id: 'hp-105', difficulty: 3, ref: 'Judges; 1 Samuel',
      answer: 'Othniel, Ehud, Shamgar, Deborah, Gideon, Tola, Jair, Jephthah, Ibzan, Elon, Abdon, Samson, Eli, Samuel',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name as many judges of Israel as you can in 30 seconds' }] },
    { id: 'hp-106', difficulty: 1, ref: 'Exodus 7-12',
      answer: 'Blood, frogs, lice, flies, livestock, boils, hail, locusts, darkness, the firstborn',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two of the ten plagues of Egypt' }] },
    { id: 'hp-107', difficulty: 3, ref: 'Exodus 7-12',
      answer: 'Blood, frogs, lice, flies, livestock, boils, hail, locusts, darkness, the firstborn',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name as many of the ten plagues of Egypt as you can in 30 seconds' }] },
    { id: 'hp-108', difficulty: 1, ref: 'Matthew 10:2-4',
      answer: 'Simon Peter, Andrew, James, John, Philip, Bartholomew, Thomas, Matthew, James son of Alphaeus, Thaddaeus, Simon the Canaanite, Judas Iscariot',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two of the twelve disciples' }] },
    { id: 'hp-109', difficulty: 1, ref: 'Galatians 5:22-23',
      answer: 'Love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two of the nine fruits of the Spirit' }] },
    { id: 'hp-110', difficulty: 1, ref: 'Ephesians 6:14-17',
      answer: 'The belt of truth, the breastplate of righteousness, feet shod with the gospel of peace, the shield of faith, the helmet of salvation, the sword of the Spirit',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two pieces of the armour of God' }] },
    { id: 'hp-111', difficulty: 2, ref: 'Ephesians 6:14-17',
      answer: 'The belt of truth, the breastplate of righteousness, feet shod with the gospel of peace, the shield of faith, the helmet of salvation, the sword of the Spirit',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name four pieces of the armour of God' }] },
    { id: 'hp-112', difficulty: 1, ref: 'Others count too',
      answer: 'Saul, David, Solomon, Jeroboam, Ahab, Jehu, Hezekiah, Josiah, Uzziah, Jehoshaphat',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two kings of Israel or Judah' }] },
    { id: 'hp-113', difficulty: 3, ref: 'Others count too',
      answer: 'Saul, David, Solomon, Jeroboam, Ahab, Jehu, Hezekiah, Josiah, Uzziah, Jehoshaphat',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name as many kings of Israel or Judah as you can in 30 seconds' }] },
    { id: 'hp-114', difficulty: 1,
      answer: 'Romans, 1 and 2 Corinthians, Galatians, Ephesians, Philippians, Colossians, 1 and 2 Thessalonians, 1 and 2 Timothy, Titus, Philemon',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two books written by Paul' }] },
    { id: 'hp-115', difficulty: 2,
      answer: 'Romans, 1 and 2 Corinthians, Galatians, Ephesians, Philippians, Colossians, 1 and 2 Thessalonians, 1 and 2 Timothy, Titus, Philemon',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name four books written by Paul' }] },
    { id: 'hp-116', difficulty: 3,
      answer: 'Romans, 1 and 2 Corinthians, Galatians, Ephesians, Philippians, Colossians, 1 and 2 Thessalonians, 1 and 2 Timothy, Titus, Philemon',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name as many books written by Paul as you can in 30 seconds' }] },
    { id: 'hp-117', difficulty: 1, ref: 'Others count too',
      answer: 'Mary the mother of Jesus, Mary Magdalene, Martha, Mary of Bethany, Elisabeth, Anna, Joanna, Salome, Herodias',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two women named in the Gospels' }] },
    { id: 'hp-118', difficulty: 2, ref: 'Others count too',
      answer: 'Mary the mother of Jesus, Mary Magdalene, Martha, Mary of Bethany, Elisabeth, Anna, Joanna, Salome, Herodias',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name four women named in the Gospels' }] },
    { id: 'hp-119', difficulty: 1, ref: 'Others count too',
      answer: 'Water into wine, calming the storm, feeding the five thousand, walking on water, healing the blind, raising Lazarus',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name two miracles that Jesus did' }] },
    { id: 'hp-120', difficulty: 3, ref: 'Others count too',
      answer: 'Water into wine, calming the storm, feeding the five thousand, walking on water, healing the blind, raising Lazarus',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name as many miracles of Jesus as you can in 30 seconds' }] },

    // LIST CARDS: a challenge, then the valid answers. difficulty follows how
    // many valid answers exist - six or more is 1, three to five is 2, one or
    // two is 3 - and a letter is only used if it has answers (checked, not
    // assumed). The answer is kept to 75 characters because the projector sets
    // it at 12vmin: longer lists ran off the screen, so a longer set shows its
    // best-known names and ends "and others".
    { id: 'hp-201', difficulty: 1,
      ref: 'Others count too',
      answer: 'Jeroboam, Jehu, Jehoram (Joram), Jehoahaz (Joahaz), Jehoash (Joash), Jehoshaphat, Jotham, Josiah, Jehoiakim, Jehoiachin (Jeconiah)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with J' }] },
    { id: 'hp-202', difficulty: 1,
      ref: 'Others count too',
      answer: 'Ahab, Ahaziah, Asa, Ahaz, Amaziah, Amon, Abijah (Abijam), Azariah (Uzziah)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with A' }] },
    { id: 'hp-203', difficulty: 2,
      answer: 'Saul, Solomon, Shallum',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with S' }] },
    { id: 'hp-204', difficulty: 2,
      answer: 'Zimri, Zechariah (Zachariah), Zedekiah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with Z' }] },
    { id: 'hp-205', difficulty: 3,
      answer: 'Hezekiah, Hoshea',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with H' }] },
    { id: 'hp-206', difficulty: 3,
      answer: 'Pekah, Pekahiah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with P' }] },
    { id: 'hp-207', difficulty: 3,
      answer: 'Menahem, Manasseh',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with M' }] },
    { id: 'hp-208', difficulty: 3,
      answer: 'Nadab',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with N' }] },
    { id: 'hp-209', difficulty: 1,
      answer: 'Exodus, Ezra, Esther, Ecclesiastes, Ezekiel, Ephesians',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with E' }] },
    { id: 'hp-210', difficulty: 2,
      answer: 'Habakkuk, Haggai, Hosea, Hebrews',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with H' }] },
    { id: 'hp-211', difficulty: 2,
      answer: 'Micah, Malachi, Mark, Matthew',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with M' }] },
    { id: 'hp-212', difficulty: 2,
      answer: 'Numbers, Nehemiah, Nahum',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with N' }] },
    { id: 'hp-213', difficulty: 3,
      answer: 'Zephaniah, Zechariah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with Z' }] },
    { id: 'hp-214', difficulty: 3,
      answer: 'Obadiah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with O' }] },
    { id: 'hp-215', difficulty: 2,
      answer: 'James, John, Judas (Iscariot, or the son of James)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name one of the twelve disciples whose name starts with J' }] },
    { id: 'hp-216', difficulty: 3,
      answer: 'Peter, Philip',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name one of the twelve disciples whose name starts with P' }] },
    { id: 'hp-217', difficulty: 3,
      answer: 'Thomas, Thaddaeus (Thaddeus)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name one of the twelve disciples whose name starts with T' }] },
    { id: 'hp-218', difficulty: 2,
      ref: 'Others count too',
      answer: 'Haggai, Habakkuk, Hosea, Huldah, Hananiah (a false prophet)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a prophet or prophetess whose name starts with H' }] },
    { id: 'hp-219', difficulty: 1,
      ref: 'Others count too',
      answer: 'Elijah, Elisha, Ezekiel, Enoch, Eliezer son of Dodavah, Eldad',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a prophet whose name starts with E' }] },
    { id: 'hp-220', difficulty: 2,
      ref: 'Others count too',
      answer: 'Jeremiah, Joel, Jonah, Jehu son of Hanani, John the Baptist',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a prophet whose name starts with J' }] },
    { id: 'hp-221', difficulty: 3,
      ref: 'Others count too',
      answer: 'Zechariah, Zephaniah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a prophet whose name starts with Z' }] },
    { id: 'hp-222', difficulty: 2,
      answer: 'Ehud, Elon, Eli',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a judge of Israel whose name starts with E' }] },
    { id: 'hp-223', difficulty: 2,
      answer: 'Jair, Jephthah, Jerubbaal (Gideon), Joel (a son of Samuel)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a judge of Israel whose name starts with J' }] },
    { id: 'hp-224', difficulty: 2,
      answer: 'Samson, Samuel, Shamgar',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a judge of Israel whose name starts with S' }] },
    { id: 'hp-225', difficulty: 1,
      ref: 'Others count too',
      answer: 'Ruth, Rahab, Rebekah (Rebecca), Rachel, Rhoda, Rizpah, Reumah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a woman in the Bible whose name starts with R' }] },
    { id: 'hp-226', difficulty: 1,
      ref: 'Others count too',
      answer: 'Hannah, Hagar, Huldah, Hadassah (Esther), Herodias, Hephzibah, Hamutal, Hoglah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a woman in the Bible whose name starts with H' }] },
    { id: 'hp-227', difficulty: 2,
      ref: 'Others count too',
      answer: 'Priscilla, Phoebe (Phebe), Peninnah, Puah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a woman in the Bible whose name starts with P' }] },
    { id: 'hp-228', difficulty: 2,
      ref: 'Others count too',
      answer: 'Naomi, Naamah, Nehushta, Noadiah, Naarah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a woman in the Bible whose name starts with N' }] },
    { id: 'hp-229', difficulty: 3,
      ref: 'Others count too',
      answer: 'Nicodemus, Nathanael',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name someone who met Jesus whose name starts with N' }] },
    { id: 'hp-230', difficulty: 3,
      ref: 'Others count too',
      answer: 'Zacchaeus (Zaccheus)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name someone who met Jesus whose name starts with Z' }] },
    { id: 'hp-231', difficulty: 3,
      ref: 'Others count too',
      answer: 'Bartimaeus (Bartimeus), Bartholomew',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name someone who met Jesus whose name starts with B' }] },
    { id: 'hp-232', difficulty: 2,
      ref: 'Others count too',
      answer: 'Jairus, John, James, Judas, Joanna',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name someone who met Jesus whose name starts with J' }] },
    { id: 'hp-233', difficulty: 1,
      ref: 'Others count too',
      answer: 'Antioch, Athens, Antipatris, Amphipolis, Apollonia, Assos, Attalia, Achaia, Arabia, Asia, Areopagus (Mars’ Hill)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with A' }] },
    { id: 'hp-234', difficulty: 1,
      ref: 'Others count too',
      answer: 'Malta (Melita), Miletus, Mitylene, Myra, Macedonia, Mysia, Mars’ Hill (Areopagus)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with M' }] },
    { id: 'hp-235', difficulty: 1,
      ref: 'Others count too',
      answer: 'Troas, Tarsus, Thessalonica, Tyre, Three Taverns, Trogyllium',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with T' }] },
    { id: 'hp-236', difficulty: 2,
      ref: 'Others count too',
      answer: 'Rome, Rhegium, Rhodes',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with R' }] },
    { id: 'hp-237', difficulty: 3,
      ref: 'Others count too',
      answer: 'Damascus, Derbe',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with D' }] },
    { id: 'hp-238', difficulty: 2,
      ref: 'Others count too',
      answer: 'Dog, Dove, Donkey (ass), Deer, Dromedary',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with D' }] },
    { id: 'hp-239', difficulty: 2,
      ref: 'Others count too',
      answer: 'Ox, Owl, Ostrich',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with O' }] },
    { id: 'hp-240', difficulty: 2,
      ref: 'Others count too',
      answer: 'Wolf, Whale, Weasel, Worm',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with W' }] },
    { id: 'hp-241', difficulty: 2,
      ref: 'Others count too',
      answer: 'Fox, Frog, Flea, Fish',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with F' }] },
    { id: 'hp-242', difficulty: 3,
      ref: 'Others count too',
      answer: 'Quail',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with Q' }] },
  ],
};
