/*
 * Hot Potato - the deck.
 *
 * HAND-WRITTEN, unlike What Came First? and Higher or Lower, which are
 * generated because their content is facts that cannot be proofread by eye.
 * These cards are writing. There is no source to derive them from.
 *
 * TWO KINDS OF CARD, and no third. A TASK is something the holder DOES, and its
 * text goes in `answer` because a task IS its own identity - validate.js
 * already rejects two puzzles sharing an answer, so that buys duplicate-card
 * detection for free. No `prompt`, no `ref`.
 *
 * A LIST card is a constrained-recall challenge - "Name a king of Israel or
 * Judah whose name starts with J" - in `prompt`, followed by a screen showing
 * the valid answers, in `answer`, so the room can settle "does that count?".
 * It is NOT trivia and must not turn into it: the challenge is recalling one
 * under pressure, standing up, and it stays fresh because a different person
 * holds the potato each time. The list is a referee, not a lesson.
 *
 * KNOWLEDGE cards stay out. A question is spent the moment the room hears the
 * answer, which is what made the deck run dry; the scripture questions that
 * used to be here are kept, verified, in tools/bible-questions.json. The
 * engine's knowledge-card path still exists in core/views.js for a deck that
 * wants it; tests/hot-potato.test.js is what stops one arriving by accident.
 *
 * THE LISTS ARE FACTS, so every one was checked against fetched KJV and WEB
 * text (api.getbible.net/v2), not written from memory; a name that could not
 * be found in the text was left out. A list that is missing a valid answer is
 * a small unfairness, so lists drawn from an open set (women, places, animals,
 * people who met Jesus, prophets) end "and others", and only the closed sets
 * (kings, books, the twelve, judges) claim to be complete. Where the KJV and
 * the WEB spell a name differently, or scholars differ, the answer carries both
 * (Jehoram (Joram), Zacchaeus (Zaccheus), Mars' Hill (Areopagus)).
 *
 * THE RULE FOR A TASK CARD: it must be performable by whoever is holding the
 * mic, with nothing but a Bible and the people next to them. No props, no
 * phones, no printing. A card that cannot be done is only discovered when it
 * comes up, in front of everyone, which is the worst place to find out.
 *
 * English only for now. `languages` carries the slot, so Tagalog is a deck
 * edit later with no code change - the same as every other game here.
 */
window.DECK = {
  id: 'hot-potato',
  title: 'Hot Potato',
  idPrefix: 'hp',   // shown on the projector, so it must never hint the answer
  shuffle: true,
  sessionSize: 12,
  languages: ['en'],
  // The range the stop is drawn from, in seconds - NOT a fixed duration. Every
  // round draws a fresh number inside it, so nobody can count. Widen it if the
  // room starts sensing the floor.
  musicSeconds: [6, 20],
  howToPlay: [
    'Pass something round while the music plays.',
    'When it stops, whoever is holding it does what the screen says.',
  ],
  puzzles: [
    // A task is something the holder does: text in `answer`, no prompt and no
    // ref. A list card (hp-2xx, below) is a challenge in `prompt` with the valid
    // answers in `answer`. Either way the challenge is doing it from memory,
    // standing up, in front of everyone, which is fresh each time a different
    // person holds the potato.
    // difficulty: 1 anyone can do it on the spot, 2 takes some thought or
    // memory, 3 real recall. The order ramps 1 -> 2 -> 3 within a round, so the
    // Ten Commandments never opens it. The scripture questions that used to be
    // here are kept, verified, in tools/bible-questions.json.
    { id: 'hp-001', answer: 'Recite any two verses from memory', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-002', answer: 'Say John 3:16 out loud, and let the room join in', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-003', answer: 'Say the Lord’s Prayer together, with the room joining in', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-004', answer: 'Read Psalm 117 aloud with the person next to you, one verse each', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-005', answer: 'Say the verse that means the most to you, then say in one sentence why', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-006', answer: 'Find Proverbs 3:5-6 in your Bible and read it aloud', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-007', answer: 'Find the shortest verse in the Bible, John 11:35, and read it aloud', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-008', answer: 'Sing one verse of a hymn with the person on your left', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-009', answer: 'Sing the chorus of a worship song with the person on your right', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-010', answer: 'Name a song you want everyone to sing, then start it off', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-011', answer: 'With a neighbour, hum a few notes of a song and let the room guess it for up to 30 seconds, or until they get it', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-012', answer: 'Name five of the twelve disciples', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-013', answer: 'Name five books of the New Testament', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-014', answer: 'Name five people from the Old Testament', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-015', answer: 'Name four of the ten plagues of Egypt, and ask the room to help if you get stuck', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-016', answer: 'Name three women of the Bible', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-017', answer: 'Name four miracles that Jesus did', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-018', answer: 'Name three stories that Jesus told', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-019', answer: 'Name four animals that appear in the Bible', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-020', answer: 'Name three of the nine fruits of the Spirit', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-021', answer: 'Say in one sentence what grace means', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-022', answer: 'Say in one sentence why we pray', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-023', answer: 'Say in one sentence what the good news is', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-024', answer: 'Finish this sentence out loud: “I know God is faithful because…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-025', answer: 'Say in one sentence what you would tell a friend who asked what church is for', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-026', answer: 'Say a short prayer out loud for a friend or family member, without naming them', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-027', answer: 'Thank God out loud for three things from this week', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-028', answer: 'Say a one-sentence prayer of thanks for this place and the people in it', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-029', answer: 'Pray one sentence for someone who is having a hard week, without naming them', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-030', answer: 'Pray one sentence for the leaders of this group', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-031', answer: 'With the people next to you, freeze in a pose that shows a Bible scene, and let the room guess for up to 30 seconds', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-032', answer: 'With a neighbour, act out a Bible story without words, and let the room guess for up to 30 seconds', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-033', answer: 'With your hands only, show one thing a shepherd does for his sheep, and let the room guess it for up to 30 seconds, or until they get it', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-034', answer: 'Tell everyone your favourite Bible story in one sentence', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-035', answer: 'Say which Bible character you would most like to meet, and why', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-036', answer: 'Say one thing you are thankful for today', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-037', answer: 'Give two verses that have helped you in a hard time', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-038', answer: 'Say out loud one thing you are glad about in this youth group', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-039', answer: 'With the person next to you, find a verse about love and read it to each other', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-040', answer: 'Finish this sentence out loud: “Something I have learned about God lately is…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-041', answer: 'Say a verse you learned as a child, as best you remember it', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-042', answer: 'Open your Bible to a Psalm you like and read two verses from it aloud', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-043', answer: 'Say a verse you would give a friend who is scared', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-044', answer: 'Say a verse that reminds you God is with you', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-045', answer: 'Say one thing that made you smile this week', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-046', answer: 'Say one thing you are looking forward to', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-047', answer: 'Say one thing you enjoy doing when nobody is making you', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-048', answer: 'Say what you would be doing right now if you were not here', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-049', answer: 'Say one thing you would ask God if you could sit with him for five minutes', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-050', answer: 'Say one way you have seen God help someone lately', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-051', answer: 'Say the funniest thing you have seen happen in church, without naming anyone', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-052', answer: 'Say which Bible story would make the best film, and why', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-053', answer: 'Say one thing you hope heaven will be like', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-054', answer: 'Say one sentence you would tell someone who had never heard of Jesus', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-055', answer: 'Finish this sentence out loud: “I feel closest to God when…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-056', answer: 'Finish this sentence out loud: “A church should be a place where…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-057', answer: 'Finish this sentence out loud: “The best advice I ever heard was…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-058', answer: 'Finish this sentence out loud: “One thing Jesus did that surprises me is…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-059', answer: 'Finish this sentence out loud: “If I could say one thing to my younger self, it would be…”', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-060', answer: 'Say a one-sentence prayer for the week ahead', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-061', answer: 'Pray one sentence of thanks for the food you ate today', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-062', answer: 'Pray one sentence for the place where you spend most of your week', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-063', answer: 'Sing one line of a song that makes you feel peaceful', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-064', answer: 'Say one line from a worship song that you like, and why you like it', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-065', answer: 'With a neighbour, read Psalm 136:1-4 aloud one verse each, and let the room join in on the line that repeats', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-066', answer: 'With a neighbour, agree on one verse and read it together out loud', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-067', answer: 'Name three things in creation that you are thankful God made', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-068', answer: 'Say three words that describe what God is like', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-069', answer: 'Name three things you could do this week to show kindness', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-070', answer: 'Stand up, stretch, and thank God for one thing your body can do', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-071', answer: 'Give the room one sentence of encouragement for the week ahead', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-072', answer: 'Recite Psalm 23 from memory, and the room may help if you stall', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-073', answer: 'Recite the Beatitudes, Matthew 5:3-10, from memory, as far as you get', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-074', answer: 'Name the nine fruits of the Spirit from Galatians 5:22-23, in any translation', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-075', answer: 'Say as many of the Ten Commandments as you can in 30 seconds', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-076', answer: 'Say the books of the New Testament in order, as far as you get in 30 seconds', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-077', answer: 'Say five books of the Old Testament in the order they appear in the Bible', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-078', answer: 'Name the twelve disciples, and the room may help if you stall', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-079', answer: 'Ask the room for a letter other than Q, X or Z, then say a verse that begins with that letter', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-080', answer: 'Say two verses from the same chapter of the Bible, and name the chapter', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-081', answer: 'Say a verse from memory, then tell the room which book and chapter it is in', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-082', answer: 'Recite 1 Corinthians 13:4-7 from memory, as far as you get', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-083', answer: 'Recite Isaiah 40:31 from memory', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-084', answer: 'Recite the Great Commission, Matthew 28:19-20, from memory, as far as you get', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-085', answer: 'Recite the blessing in Numbers 6:24-26 from memory', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-086', answer: 'Name six pieces of the armour of God from Ephesians 6', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-087', answer: 'Name what God made on each of the first six days of creation, in order', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-088', answer: 'Name four of the “I am” sayings of Jesus in John’s Gospel', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-089', answer: 'Name five of the twelve minor prophets', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-090', answer: 'Recite Psalm 1:1-3 from memory, as far as you get', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-091', answer: 'Recite John 1:1-3 from memory', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-092', answer: 'Say the Lord’s Prayer from memory on your own, and the room joins in only if you stall', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-093', answer: 'Recite Romans 8:28 from memory', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-094', answer: 'Recite Jeremiah 29:11 from memory', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-095', answer: 'Recite Joshua 1:9 from memory', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-096', answer: 'Recite Proverbs 3:5-6 from memory', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-097', answer: 'Say the first five books of the Bible in order', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-098', answer: 'Name the four Gospels in order, and one thing each is known for', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-099', answer: 'Name five kings of Israel or Judah', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-100', answer: 'Name two or three of the sons of Jacob', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-101', answer: 'Name five of the twelve sons of Jacob', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-102', answer: 'Name as many of the sons of Jacob as you can in 30 seconds', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-103', answer: 'Name two judges of Israel', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-104', answer: 'Name four judges of Israel', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-105', answer: 'Name as many judges of Israel as you can in 30 seconds', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-106', answer: 'Name two of the ten plagues of Egypt', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-107', answer: 'Name as many of the ten plagues of Egypt as you can in 30 seconds', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-108', answer: 'Name two of the twelve disciples', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-109', answer: 'Name two of the nine fruits of the Spirit', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-110', answer: 'Name two pieces of the armour of God', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-111', answer: 'Name four pieces of the armour of God', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-112', answer: 'Name two kings of Israel or Judah', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-113', answer: 'Name as many kings of Israel or Judah as you can in 30 seconds', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-114', answer: 'Name two books written by Paul', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-115', answer: 'Name four books written by Paul', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-116', answer: 'Name as many books written by Paul as you can in 30 seconds', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-117', answer: 'Name two women named in the Gospels', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-118', answer: 'Name four women named in the Gospels', difficulty: 2,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-119', answer: 'Name two miracles that Jesus did', difficulty: 1,
      variants: [{ type: 'card', kind: 'task' }] },
    { id: 'hp-120', answer: 'Name as many miracles of Jesus as you can in 30 seconds', difficulty: 3,
      variants: [{ type: 'card', kind: 'task' }] },

    // LIST CARDS: a challenge, then the valid answers. difficulty follows how
    // many valid answers exist - six or more is 1, three to five is 2, one or
    // two is 3 - and a letter is only used if it has answers (checked, not
    // assumed). The answer is kept to 75 characters because the projector sets
    // it at 12vmin: longer lists ran off the screen, so a longer set shows its
    // best-known names and ends "and others".
    { id: 'hp-201', difficulty: 1,
      answer: 'Jeroboam, Jehu, Jehoram (Joram), Jehoahaz (Joahaz), Jehoash (Joash), Jehoshaphat, Jotham, Josiah, Jehoiakim, Jehoiachin (Jeconiah), and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with J' }] },
    { id: 'hp-202', difficulty: 1,
      answer: 'Ahab, Ahaziah, Asa, Ahaz, Amaziah, Amon, Abijah (Abijam), Azariah (Uzziah), and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with A' }] },
    { id: 'hp-203', difficulty: 2,
      answer: 'Saul, Solomon, Shallum',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with S' }] },
    { id: 'hp-204', difficulty: 2,
      answer: 'Zimri, Zechariah (Zachariah), Zedekiah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with Z' }] },
    { id: 'hp-205', difficulty: 3,
      answer: 'Hezekiah, Hoshea',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with H' }] },
    { id: 'hp-206', difficulty: 3,
      answer: 'Pekah, Pekahiah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with P' }] },
    { id: 'hp-207', difficulty: 3,
      answer: 'Menahem, Manasseh',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with M' }] },
    { id: 'hp-208', difficulty: 3,
      answer: 'Nadab',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a king of Israel or Judah whose name starts with N' }] },
    { id: 'hp-209', difficulty: 1,
      answer: 'Exodus, Ezra, Esther, Ecclesiastes, Ezekiel, Ephesians',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with E' }] },
    { id: 'hp-210', difficulty: 2,
      answer: 'Habakkuk, Haggai, Hosea, Hebrews',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with H' }] },
    { id: 'hp-211', difficulty: 2,
      answer: 'Micah, Malachi, Mark, Matthew',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with M' }] },
    { id: 'hp-212', difficulty: 2,
      answer: 'Numbers, Nehemiah, Nahum',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with N' }] },
    { id: 'hp-213', difficulty: 3,
      answer: 'Zephaniah, Zechariah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with Z' }] },
    { id: 'hp-214', difficulty: 3,
      answer: 'Obadiah',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a book of the Bible that starts with O' }] },
    { id: 'hp-215', difficulty: 2,
      answer: 'James, John, Judas (Iscariot, or the son of James)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name one of the twelve disciples whose name starts with J' }] },
    { id: 'hp-216', difficulty: 3,
      answer: 'Peter, Philip',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name one of the twelve disciples whose name starts with P' }] },
    { id: 'hp-217', difficulty: 3,
      answer: 'Thomas, Thaddaeus (Thaddeus)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name one of the twelve disciples whose name starts with T' }] },
    { id: 'hp-218', difficulty: 2,
      answer: 'Haggai, Habakkuk, Hosea, Huldah, Hananiah (a false prophet), and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a prophet or prophetess whose name starts with H' }] },
    { id: 'hp-219', difficulty: 1,
      answer: 'Elijah, Elisha, Ezekiel, Enoch, Eliezer son of Dodavah, Eldad, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a prophet whose name starts with E' }] },
    { id: 'hp-220', difficulty: 2,
      answer: 'Jeremiah, Joel, Jonah, Jehu son of Hanani, John the Baptist, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a prophet whose name starts with J' }] },
    { id: 'hp-221', difficulty: 3,
      answer: 'Zechariah, Zephaniah, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a prophet whose name starts with Z' }] },
    { id: 'hp-222', difficulty: 2,
      answer: 'Ehud, Elon, Eli',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a judge of Israel whose name starts with E' }] },
    { id: 'hp-223', difficulty: 2,
      answer: 'Jair, Jephthah, Jerubbaal (Gideon), Joel (a son of Samuel)',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a judge of Israel whose name starts with J' }] },
    { id: 'hp-224', difficulty: 2,
      answer: 'Samson, Samuel, Shamgar',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a judge of Israel whose name starts with S' }] },
    { id: 'hp-225', difficulty: 1,
      answer: 'Ruth, Rahab, Rebekah (Rebecca), Rachel, Rhoda, Rizpah, Reumah, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a woman in the Bible whose name starts with R' }] },
    { id: 'hp-226', difficulty: 1,
      answer: 'Hannah, Hagar, Huldah, Hadassah (Esther), Herodias, Hephzibah, Hamutal, Hoglah, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a woman in the Bible whose name starts with H' }] },
    { id: 'hp-227', difficulty: 2,
      answer: 'Priscilla, Phoebe (Phebe), Peninnah, Puah, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a woman in the Bible whose name starts with P' }] },
    { id: 'hp-228', difficulty: 2,
      answer: 'Naomi, Naamah, Nehushta, Noadiah, Naarah, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a woman in the Bible whose name starts with N' }] },
    { id: 'hp-229', difficulty: 3,
      answer: 'Nicodemus, Nathanael, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name someone who met Jesus whose name starts with N' }] },
    { id: 'hp-230', difficulty: 3,
      answer: 'Zacchaeus (Zaccheus), and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name someone who met Jesus whose name starts with Z' }] },
    { id: 'hp-231', difficulty: 3,
      answer: 'Bartimaeus (Bartimeus), Bartholomew, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name someone who met Jesus whose name starts with B' }] },
    { id: 'hp-232', difficulty: 2,
      answer: 'Jairus, John, James, Judas, Joanna, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name someone who met Jesus whose name starts with J' }] },
    { id: 'hp-233', difficulty: 1,
      answer: 'Antioch, Athens, Antipatris, Amphipolis, Apollonia, Assos, Attalia, Achaia, Arabia, Asia, Areopagus (Mars’ Hill), and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with A' }] },
    { id: 'hp-234', difficulty: 1,
      answer: 'Malta (Melita), Miletus, Mitylene, Myra, Macedonia, Mysia, Mars’ Hill (Areopagus), and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with M' }] },
    { id: 'hp-235', difficulty: 1,
      answer: 'Troas, Tarsus, Thessalonica, Tyre, Three Taverns, Trogyllium, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with T' }] },
    { id: 'hp-236', difficulty: 2,
      answer: 'Rome, Rhegium, Rhodes, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with R' }] },
    { id: 'hp-237', difficulty: 3,
      answer: 'Damascus, Derbe, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name a place Paul visited that starts with D' }] },
    { id: 'hp-238', difficulty: 2,
      answer: 'Dog, Dove, Donkey (ass), Deer, Dromedary, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with D' }] },
    { id: 'hp-239', difficulty: 2,
      answer: 'Ox, Owl, Ostrich, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with O' }] },
    { id: 'hp-240', difficulty: 2,
      answer: 'Wolf, Whale, Weasel, Worm, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with W' }] },
    { id: 'hp-241', difficulty: 2,
      answer: 'Fox, Frog, Flea, Fish, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with F' }] },
    { id: 'hp-242', difficulty: 3,
      answer: 'Quail, and others',
      variants: [{ type: 'card', kind: 'list',
                   prompt: 'Name an animal in the Bible that starts with Q' }] },
  ],
};
